### ISSUE TITLE
404 Not Found - refinery/dialogs/Link?wymeditor=true&null

### ISSUE THREAD

**Issue by lpsBetty** [refinery/refinerycms#1555]
If I change a pagetext and want to add an Hyperlink or an Image there is only the ajax loader but I get an 404 error
and this is only in produciton mode (i use the asset pipeline) 

404 Not Found - on the following actions:
http://domain.com/refinery/dialogs/Link?wymeditor=true&null
http://domain.com/refinery/dialogs/Image?wymeditor=true&null

I have no idea what the problem is!?

**Comment by apetitdev** [comment]
@ugisozols I don't think this issue should be closed, this is not fixed for me, after I changed the backend_route I am not able to upload image anymore on my production environment (locale is fine).
![screen shot 2016-07-16 at 4 26 11 pm](https://cloud.githubusercontent.com/assets/11073567/16893650/700c8dc4-4b71-11e6-96bd-9c34c5c21b72.png)

**Comment by dasibre** [comment]
I'm also getting the same error after changing the backend path @apetitdev

**Comment by bricesanchez** [comment]
Hello,

We needs more informations to be able to fix the problem such as :
*  Could you copy/paste your Gemfile.lock ?
*  Do you have a step by step to reproduce?
*  Do you have an error stracktrace to share?

Thanks!

**Comment by dasibre** [comment]
@bricesanchez I was able to resolve the issue, on my local system. Required deleting tmp/cache and restarting server. For the app running on production on Heroku, did something similar; purged cache, redeployed application and it's working fine.

**Comment by bricesanchez** [comment]
@dasibre Good to know :)
