### ISSUE TITLE
t

### ISSUE THREAD

**Issue by peggyc3** [refinery/refinerycms#1572]

**Comment by creativesoul** [comment]
parndt does refinerycms supports  gem 'refinerycms', git: 'https://github.com/refinery/refinerycms'  rails 4 and ruby 2.1.2

**Comment by creativesoul** [comment]
![refinerycms](https://cloud.githubusercontent.com/assets/5693310/6078130/079de90c-ae1c-11e4-9ab4-d011ce4308f8.png) this is the problem I am facing

**Comment by parndt** [comment]
No, master branch support Rails 4.1.5 or greater
