### ISSUE TITLE
Run Rspec in Refinery cms 

### ISSUE THREAD

**Issue by railsfactory-sivamanikandan** [refinery/refinerycms#1683]
How to run rspec in refinery cms 

i had added new engine i want to test whole refinery cms  using rspec or unit testing what are details given in refinerycms site is not working
 can any you help me how to run the test

Please give me one by one step it helps me to run the test (unit or rspec)

Thanks in advance

**Comment by surajit** [comment]
anyone please help, I want to run model spec like vendor/extensions/blogs/spec/models/refinery/blogs/comment_spec.rb. Howo to run this spec.
 rake refinery:testing:spec  not working
 I tried with  bundle exec rspec vendor/extensions/blogs/spec/models/refinery/blogs/comment_spec.rb not working it was showing 
vendor/extensions/blogs/spec/models/refinery/blogs/comment_spec.rb:1:in `require': cannot load such file -- /vendor/extensions/met_orders/spec/spec_helper.rb (LoadError)
I've added the path for 'spec_helper' in "comment_spect.rb" is require '/vendor/extensions/blogs/spec/spec_helper.rb' but it's can't load. So how can I solve this please help.

**Comment by sanychcz** [comment]
This helped me to run test for some extension.
in /vendor/extensions/extension_name/spec/spec_helper.rb 
change: require 'spec_helper' to: require_relative '../../../spec_helper'
and the run tests like:
rspec vendor/extensions/extension_name/spec/models  
or
rspec vendor/extensions/extension_name/spec/models/refinery/services/service_spec.rb

This works only for running test for specific extension.
