### ISSUE TITLE
Error when forking refinery

### ISSUE THREAD

**Issue by ghost** [refinery/refinerycms#1743]
I am interested in contributing to the project, and I've followed the steps outlined in "Contributing to Refinery" here: http://refinerycms.com/guides/contributing-to-refinery but when I run rails s, I get "Could not find table 'refinery_pages'".  It looks the dummy database has not been bootstrapped.  Is there an extra command that I am missing?

I forked the project as described and ran the following commands:

$ git clone <my fork>
$ cd refinerycms
$ bundle
$ bundle exec rake refinery:testing:dummy_app
$ rails s

the error occurs when visiting localhost:3000 in the browser.  Thanks.

**Comment by roschacker** [comment]
Reproduced with fresh (2017) installation:

    ➜  refinerycms cd /home/ubuntu/refinerycms && rails server --environment=test --port=3333
    => Booting WEBrick
    => Rails 4.2.8 application starting in test on http://localhost:3333
    => Run `rails server -h` for more startup options
    => Ctrl-C to shutdown server
    [2017-03-15 08:29:39] INFO  WEBrick 1.3.1
    [2017-03-15 08:29:39] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux-gnu]
    [2017-03-15 08:29:39] INFO  WEBrick::HTTPServer#start: pid=26792 port=3333
    [2017-03-15 08:29:41] ERROR ActiveRecord::StatementInvalid: Could not find table 'refinery_pages'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:501:in `table_structure'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:375:in `columns'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/attributes.rb:93:in `columns'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/attributes.rb:98:in `columns_hash'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/core.rb:173:in `block in find_by'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/core.rb:173:in `each'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/core.rb:173:in `all?'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/core.rb:173:in `find_by'
            /var/lib/gems/2.3.0/gems/refinerycms-pages-3.0.5/app/controllers/refinery/pages_controller.rb:104:in `call'
            /var/lib/gems/2.3.0/gems/refinerycms-pages-3.0.5/app/controllers/refinery/pages_controller.rb:75:in `find_page'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:164:in `block in halting'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
            /var/lib/gems/2.3.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/mapper.rb:51:in `serve'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
            /var/lib/gems/2.3.0/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
            /var/lib/gems/2.3.0/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
            /var/lib/gems/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
            /var/lib/gems/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
            /var/lib/gems/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/etag.rb:24:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/conditionalget.rb:25:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
            /var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/runtime.rb:18:in `call'
            /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
            /var/lib/gems/2.3.0/gems/dragonfly-1.0.12/lib/dragonfly/cookie_monster.rb:9:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/lock.rb:17:in `call'
            /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/sendfile.rb:113:in `call'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
            /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/lock.rb:17:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
            /var/lib/gems/2.3.0/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
            /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
            /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
            /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


    ➜  ~
    ➜  ~ curl localhost:3333
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
    <HTML>
      <HEAD><TITLE>Internal Server Error</TITLE></HEAD>
      <BODY>
        <H1>Internal Server Error</H1>
        Could not find table 'refinery_pages'
        <HR>
        <ADDRESS>
         WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at
         localhost:3333
        </ADDRESS>
      </BODY>
    </HTML>
    ➜  ~

**Comment by parndt** [comment]
@roschacker I can't reproduce that. Here is what I typed:

```
git clone https://github.com/refinery/refinerycms
Cloning into 'refinerycms'...
remote: Counting objects: 115704, done.
remote: Total 115704 (delta 0), reused 0 (delta 0), pack-reused 115704
Receiving objects: 100% (115704/115704), 26.04 MiB | 4.14 MiB/s, done.
Resolving deltas: 100% (59406/59406), done.
➜  cd refinerycms
➜  refinerycms git:(master) bundle
Bundle complete! 22 Gemfile dependencies, 100 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
➜  refinerycms git:(master) bundle exec rake refinery:testing:dummy_app
Copied migration 20170315212039_create_refinerycms_images_schema.refinery_images.rb from refinery_images
Copied migration 20170315212040_remove_image_ext_from_refinery_images.refinery_images.rb from refinery_images
Copied migration 20170315212041_add_title_and_alt_to_refinery_images.refinery_images.rb from refinery_images
Copied migration 20170315212042_translate_refinery_images.refinery_images.rb from refinery_images
Copied migration 20170315212043_create_refinerycms_resources_schema.refinery_resources.rb from refinery_resources
Copied migration 20170315212044_add_translated_title_to_refinery_resources.refinery_resources.rb from refinery_resources
Copied migration 20170315212045_create_refinerycms_pages_schema.refinery_pages.rb from refinery_pages
Copied migration 20170315212046_add_custom_slug_to_refinery_pages.refinery_pages.rb from refinery_pages
Copied migration 20170315212047_add_slug_to_refinery_page_parts.refinery_pages.rb from refinery_pages
Copied migration 20170315212048_update_slug_and_title_in_refinery_page_parts.refinery_pages.rb from refinery_pages
Copied migration 20170315212049_fix_slug_format_in_refinery_page_parts.refinery_pages.rb from refinery_pages
Copied migration 20170315212050_create_seo_meta.seo_meta.rb from seo_meta
Copied migration 20170315212051_remove_meta_keywords_from_seo_meta.seo_meta.rb from seo_meta
== 20170315212039 CreateRefinerycmsImagesSchema: migrating ====================
-- create_table(:refinery_images)
   -> 0.0007s
== 20170315212039 CreateRefinerycmsImagesSchema: migrated (0.0007s) ===========

== 20170315212040 RemoveImageExtFromRefineryImages: migrating =================
-- remove_column(:refinery_images, :image_ext)
   -> 0.0024s
== 20170315212040 RemoveImageExtFromRefineryImages: migrated (0.0025s) ========

== 20170315212041 AddTitleAndAltToRefineryImages: migrating ===================
-- change_table(:refinery_images)
   -> 0.0006s
== 20170315212041 AddTitleAndAltToRefineryImages: migrated (0.0006s) ==========

== 20170315212042 TranslateRefineryImages: migrating ==========================
== 20170315212042 TranslateRefineryImages: migrated (0.0041s) =================

== 20170315212043 CreateRefinerycmsResourcesSchema: migrating =================
-- create_table(:refinery_resources)
   -> 0.0006s
== 20170315212043 CreateRefinerycmsResourcesSchema: migrated (0.0007s) ========

== 20170315212044 AddTranslatedTitleToRefineryResources: migrating ============
== 20170315212044 AddTranslatedTitleToRefineryResources: migrated (0.0015s) ===

== 20170315212045 CreateRefinerycmsPagesSchema: migrating =====================
-- create_table(:refinery_page_parts)
   -> 0.0006s
-- add_index(:refinery_page_parts, :id)
   -> 0.0004s
-- add_index(:refinery_page_parts, :refinery_page_id)
   -> 0.0005s
-- create_table(:refinery_pages)
   -> 0.0007s
-- add_index(:refinery_pages, :depth)
   -> 0.0003s
-- add_index(:refinery_pages, :id)
   -> 0.0004s
-- add_index(:refinery_pages, :lft)
   -> 0.0006s
-- add_index(:refinery_pages, :parent_id)
   -> 0.0026s
-- add_index(:refinery_pages, :rgt)
   -> 0.0009s
== 20170315212045 CreateRefinerycmsPagesSchema: migrated (0.0165s) ============

== 20170315212046 AddCustomSlugToRefineryPages: migrating =====================
== 20170315212046 AddCustomSlugToRefineryPages: migrated (0.0006s) ============

== 20170315212047 AddSlugToRefineryPageParts: migrating =======================
-- rename_column(:refinery_page_parts, :title, :slug)
   -> 0.0056s
-- add_column(:refinery_page_parts, :title, :string)
   -> 0.0002s
== 20170315212047 AddSlugToRefineryPageParts: migrated (0.0059s) ==============

== 20170315212048 UpdateSlugAndTitleInRefineryPageParts: migrating ============
== 20170315212048 UpdateSlugAndTitleInRefineryPageParts: migrated (0.0008s) ===

== 20170315212049 FixSlugFormatInRefineryPageParts: migrating =================
== 20170315212049 FixSlugFormatInRefineryPageParts: migrated (0.0004s) ========

== 20170315212050 CreateSeoMeta: migrating ====================================
-- create_table(:seo_meta)
   -> 0.0009s
-- add_index(:seo_meta, :id)
   -> 0.0004s
-- add_index(:seo_meta, [:seo_meta_id, :seo_meta_type], {:name=>:id_type_index_on_seo_meta})
   -> 0.0004s
== 20170315212050 CreateSeoMeta: migrated (0.0019s) ===========================

== 20170315212051 RemoveMetaKeywordsFromSeoMeta: migrating ====================
-- remove_column(:seo_meta, :meta_keywords)
   -> 0.0043s
== 20170315212051 RemoveMetaKeywordsFromSeoMeta: migrated (0.0043s) ===========

== 20170315212039 CreateRefinerycmsImagesSchema: migrating ====================
-- create_table(:refinery_images)
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /Users/parndt/sandbox/refinerycms/spec/dummy/db/migrate/20170315212039_create_refinerycms_images_schema.refinery_images.rb:13)
   -> 0.0007s
== 20170315212039 CreateRefinerycmsImagesSchema: migrated (0.0008s) ===========

== 20170315212040 RemoveImageExtFromRefineryImages: migrating =================
-- remove_column(:refinery_images, :image_ext)
   -> 0.0025s
== 20170315212040 RemoveImageExtFromRefineryImages: migrated (0.0026s) ========

== 20170315212041 AddTitleAndAltToRefineryImages: migrating ===================
-- change_table(:refinery_images)
   -> 0.0005s
== 20170315212041 AddTitleAndAltToRefineryImages: migrated (0.0005s) ==========

== 20170315212042 TranslateRefineryImages: migrating ==========================
== 20170315212042 TranslateRefineryImages: migrated (0.0039s) =================

== 20170315212043 CreateRefinerycmsResourcesSchema: migrating =================
-- create_table(:refinery_resources)
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in change at /Users/parndt/sandbox/refinerycms/spec/dummy/db/migrate/20170315212043_create_refinerycms_resources_schema.refinery_resources.rb:11)
   -> 0.0007s
== 20170315212043 CreateRefinerycmsResourcesSchema: migrated (0.0007s) ========

== 20170315212044 AddTranslatedTitleToRefineryResources: migrating ============
== 20170315212044 AddTranslatedTitleToRefineryResources: migrated (0.0015s) ===

== 20170315212045 CreateRefinerycmsPagesSchema: migrating =====================
-- create_table(:refinery_page_parts)
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in up at /Users/parndt/sandbox/refinerycms/spec/dummy/db/migrate/20170315212045_create_refinerycms_pages_schema.refinery_pages.rb:10)
   -> 0.0007s
-- add_index(:refinery_page_parts, :id)
   -> 0.0003s
-- add_index(:refinery_page_parts, :refinery_page_id)
   -> 0.0004s
-- create_table(:refinery_pages)
DEPRECATION WARNING: `#timestamps` was called without specifying an option for `null`. In Rails 5, this behavior will change to `null: false`. You should manually specify `null: true` to prevent the behavior of your existing migrations from changing. (called from block in up at /Users/parndt/sandbox/refinerycms/spec/dummy/db/migrate/20170315212045_create_refinerycms_pages_schema.refinery_pages.rb:33)
   -> 0.0007s
-- add_index(:refinery_pages, :depth)
   -> 0.0003s
-- add_index(:refinery_pages, :id)
   -> 0.0004s
-- add_index(:refinery_pages, :lft)
   -> 0.0006s
-- add_index(:refinery_pages, :parent_id)
   -> 0.0006s
-- add_index(:refinery_pages, :rgt)
   -> 0.0008s
== 20170315212045 CreateRefinerycmsPagesSchema: migrated (0.0082s) ============

== 20170315212046 AddCustomSlugToRefineryPages: migrating =====================
== 20170315212046 AddCustomSlugToRefineryPages: migrated (0.0004s) ============

== 20170315212047 AddSlugToRefineryPageParts: migrating =======================
-- rename_column(:refinery_page_parts, :title, :slug)
   -> 0.0042s
-- add_column(:refinery_page_parts, :title, :string)
   -> 0.0003s
== 20170315212047 AddSlugToRefineryPageParts: migrated (0.0046s) ==============

== 20170315212048 UpdateSlugAndTitleInRefineryPageParts: migrating ============
== 20170315212048 UpdateSlugAndTitleInRefineryPageParts: migrated (0.0006s) ===

== 20170315212049 FixSlugFormatInRefineryPageParts: migrating =================
== 20170315212049 FixSlugFormatInRefineryPageParts: migrated (0.0003s) ========

== 20170315212050 CreateSeoMeta: migrating ====================================
-- create_table(:seo_meta)
   -> 0.0005s
-- add_index(:seo_meta, :id)
   -> 0.0003s
-- add_index(:seo_meta, [:seo_meta_id, :seo_meta_type], {:name=>:id_type_index_on_seo_meta})
   -> 0.0005s
== 20170315212050 CreateSeoMeta: migrated (0.0014s) ===========================

== 20170315212051 RemoveMetaKeywordsFromSeoMeta: migrating ====================
-- remove_column(:seo_meta, :meta_keywords)
   -> 0.0042s
== 20170315212051 RemoveMetaKeywordsFromSeoMeta: migrated (0.0043s) ===========

➜  refinerycms git:(master) rails s
=> Booting WEBrick
=> Rails 4.2.8 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2017-03-16 10:20:49] INFO  WEBrick 1.3.1
[2017-03-16 10:20:49] INFO  ruby 2.4.0 (2016-12-24) [x86_64-darwin16]
[2017-03-16 10:20:49] INFO  WEBrick::HTTPServer#start: pid=2449 port=3000
```
I then visited http://localhost:3000/refinery

```
Started GET "/refinery" for ::1 at 2017-03-16 10:20:56 +1300
Processing by Refinery::Admin::CoreController#index as HTML
  Parameters: {"locale"=>:en}
Redirected to http://localhost:3000/refinery/pages
Completed 302 Found in 36ms (ActiveRecord: 0.0ms)


Started GET "/refinery/pages" for ::1 at 2017-03-16 10:20:56 +1300
Processing by Refinery::Admin::PagesController#index as HTML
  Parameters: {"locale"=>:en}
  Rendered /usr/local/lib/ruby/gems/2.4.0/gems/refinerycms-acts-as-indexed-3.0.0/app/views/refinery/acts_as_indexed/admin/_search_header.html.erb (0.4ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/admin/_search_header.html.erb (3.4ms)
   (0.1ms)  SELECT COUNT(*) FROM "refinery_pages"
  Rendered /Users/parndt/sandbox/refinerycms/pages/app/views/refinery/admin/pages/_records.html.erb (12.5ms)
  Rendered /usr/local/lib/ruby/gems/2.4.0/gems/refinerycms-acts-as-indexed-3.0.0/app/views/refinery/acts_as_indexed/admin/_search.html.erb (7.1ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/admin/_search.html.erb (9.8ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM "refinery_pages"
  Rendered /Users/parndt/sandbox/refinerycms/pages/app/views/refinery/admin/pages/_actions.html.erb (16.7ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM "refinery_pages"
  Rendered /Users/parndt/sandbox/refinerycms/pages/app/views/refinery/admin/pages/index.html.erb within layouts/refinery/admin (40.1ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/_html_tag.html.erb (0.3ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/admin/_javascripts.html.erb (200.9ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/admin/_head.html.erb (15269.4ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/admin/_menu_item.html.erb (10.7ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/admin/_menu.html.erb (20.7ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/_site_bar.html.erb (2.3ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/_no_script.html.erb (0.5ms)
  Rendered /Users/parndt/sandbox/refinerycms/core/app/views/refinery/_message.html.erb (0.5ms)
Completed 200 OK in 15387ms (Views: 15386.1ms | ActiveRecord: 0.1ms)
```

Despite the bad speed (assets had to compile) it worked fine for me.  Do you know how I can reproduce your error?

**Comment by ghoppe** [comment]
If I may, it looks like @roschacker used Ruby 2.3.1, and @parndt used Ruby 2.4.0. Could that be the difference?

**Comment by anitagraham** [comment]
Did the migration and seed steps run properly during the `rake refinery:testing:dummy_app` step?

The error is typical of the situation where the database hasn't been created.

Is the db there?  It should be  `spec/dummy/dummy_test`.  Does it have the tables defined?
(There are sqlite tools somewhere that let you look at the database).

**Comment by roschacker** [comment]
> Did the migration and seed steps run properly during the rake refinery:testing:dummy_app step?

I can NOT give more feedback with debug info right now
because i stopped the instance
and working with prebuild one (bitnami).

I saw the base (sqlite file)
but when i opened it and tried to count records in table
it ansered that there is no such table (expected answer).
