### ISSUE TITLE
Could not find generator refinery:cms

### ISSUE THREAD

**Issue by rahul100885** [refinery/refinerycms#1780]
I am trying to install refinerycms into my existing application which is running with Ruby 1.9.3 and Rails 3.2.6, which have it's own devise authentication 

But I am getting this error 

> Could not find generator refinery:cms

 when ever I try to run command 

> rails g refinery:cms

I have added refinerycms gem into Gemfile and also done the bundle install.

Also if I list all available generator I am not able to see any generator related to refinery.

**Comment by creativesoul** [comment]
how to integrate refinery cms in existing rails 4 app
I have already added in gemfile this
gem 'refinerycms-i18n', github: 'refinery/refinerycms-i18n', branch: 'master'
gem 'refinerycms', github: 'refinery/refinerycms', branch: "master"
and I tried to do 
rails g refinery:engine app name:string description:text
but the error is 
Could not find generator refinery:engine.
How to resolve this
Thank you who ever participants

**Comment by bricesanchez** [comment]
Refinerycms gem has to be included before i18n :)

```ruby
gem 'refinerycms', github: 'refinery/refinerycms', branch: "master"
gem 'refinerycms-i18n', github: 'refinery/refinerycms-i18n', branch: 'master'
```
