### ISSUE TITLE
"-page" suffix on slug?

### ISSUE THREAD

**Issue by silent-e** [refinery/refinerycms#1812]
Anyone know under what circumstances a "-page" suffix would be added to the slug of my page under v2.0.5?  I have several pages with titles of "Answers", "Courses", "Downloads" that somehow have slugs of "answers-page", "courses-page", and "downloads-page" respectively.  I also have multiple copies of each page, under different parents.  None of these pages have titles that end in "Page".  It's just the one word.

If I change the title of the "Answers" page to "Answer" then there's no "-page" suffix.  Then if I put the "s" back on to make it "Answers", the "-page" suffix comes back.  If I spell it "Answerss" (note double "s") then there's no "-page" suffix.

I just don't understand.  I'm going to trace the code to figure out where it might be happening but I was hoping one of the devs might know.

I don't want these suffixes.  Is it because they're plural and we don't want to confuse it with a resource?

Thanks in advance.

matte

**Comment by theomarkkuspaul** [comment]
👍
