### ISSUE TITLE
Issue getting images to save to S3 on Heroku

### ISSUE THREAD

**Issue by hallmatt** [refinery/refinerycms#1879]
I've followed the guides (http://refinerycms.com/guides/heroku and http://refinerycms.com/guides/amazon-s3-for-uploads) to try and get my uploads to store on S3, while using Heroku, but they continually save to the file system.

In images.rb, 

```
config.s3_backend = Refinery::Core.s3_backend
config.s3_bucket_name = ENV['S3_BUCKET']
config.s3_access_key_id = ENV['S3_KEY']
config.s3_secret_access_key = ENV['S3_SECRET']
config.s3_region = ENV['S3_REGION']
```

In production.rb

```
Refinery::Core.config.s3_backend = true
```

In application.rb

```
config.assets.initialize_on_precompile = true
```

In the gemfile

```
gem 'fog'
gem 'aws-sdk'
```

Our Heroku config displays all the variables and they checkout fine. The upload looks like it works great, but the images show that the file is being stored locally instead of S3.

The project is on Refinery version 2.0.6

**Comment by drjorgepolanco** [comment]
Make sure you are using a US Standard bucket and then configure your variables this way: 
heroku config:add S3_REGION=us-east-1
I had the same issue and was using S3_REGION=us-standard

I hope this helps everyone fix the issue.
