### ISSUE TITLE
Upload image causes error

### ISSUE THREAD

**Issue by hopewise** [refinery/refinerycms#2121]
When I try to upload an image, I get this error:

IOError in Refinery::Admin::ImagesController#create

closed stream

I am installing from git://github.com/refinery/refinerycms.git

**Comment by lucianosousa** [comment]
Did you guys experience this again?

I've the same error here.

ENV variables fine, imagemagick-6.9.0-10 installed and I've another project running with paperclip and works fine.

Any idea?
