### ISSUE TITLE
Dragonfly Rack::Cache default position

### ISSUE THREAD

**Issue by jokklan** [refinery/refinerycms#2132]
Why are the dragonfly Rack::Cache placed after ActionDispatch::Callbacks as default?
Wouldn't it be better if it was placed in front of the middleware stack, to increase performance?

**Comment by sintro** [comment]
Is it OK that there are two copies of Dragonfly middleware (probably, from refinery images and from refinery resources)? After enabling gem "rack-cache", there will be two different copies of "Rack::Cache" middleware, by one after each Dragonfly. Is not this performance issue?

**Comment by parndt** [comment]
I don't think so, personally.
