### ISSUE TITLE
Internal links not updated when pages' parent changes

### ISSUE THREAD

**Issue by michrome** [refinery/refinerycms#2215]
If a page's parent changes, internal links to that page are not updated.
## Experienced on versions

`2.0.9`, `2.0.10`
## Steps to recreate issue

1) Create this page hierarchy:
- Home
  - Page 1
  - Page 2

2) Create an internal page link inside `Page 1` that links to `Page 2`.

3) Verify via a browser that the link in `Page 1` is `/home/page-2`.

4) Reorder pages to this hierarchy:
- Home
  - Page 1
    - Page 2

5) Reload `Page 1` in a browser. Note the link **has not** been updated to `/home/page-1/page-2`.

**Comment by ahennie** [comment]
@parndt thanks for your update. May I ask why this issue was closed? I have this issue as well. Any workarounds?

**Comment by simi** [comment]
I had this done for very old version of Refinery.

https://github.com/SmartMedia/refinerycms-reference-link

You can see how that works in spec directory.

https://github.com/SmartMedia/refinerycms-reference-link/blob/master/spec/texts/test.txt

is rendered as

https://github.com/SmartMedia/refinerycms-reference-link/blob/master/spec/texts/parsed_test.txt

If I remember well those links were working with page title changes also.
