### ISSUE TITLE
Add/ Edit page UI - Styles toolbar invisible and Advanced Options link not working

### ISSUE THREAD

**Issue by aartikaul** [refinery/refinerycms#2216]
We are using Refinery + Devise
We just upgraded Rails to 3.2.11.
Refinery - 2.0.9
Devise - 2.0.1

Now in the Refinery UI, Adding or editing a page - the style tool bar is not visible anymore and the only link that works is "Save". Clicking on "Advanced Options" or "Preview" just reloads the same page.
I couldn't find any similar issue and was wondering if anyone has any additional info.
It was working fine with Rails 3.2.3. 
Thank you.

![Screen Shot 2013-03-15 at 11 55 04 AM](https://f.cloud.github.com/assets/1313777/264532/1dde5e16-8d91-11e2-918f-2ad55be0b591.png)

**Comment by codetoonarrow** [comment]
I'm facing a similar problem at the moment, how did you fix it? Is it something to do with JQuery ? Any help would be much appreciated .
