### ISSUE TITLE
devise routes not defined after integrating with refinerycms

### ISSUE THREAD

**Issue by hau** [refinery/refinerycms#2217]
I tried to follow the steps described in http://www.refinerycms.com/guides/with-an-existing-rails-31-devise-app on an test rails 3.2 app with devise.

I used refinerycms 2.0.10.  I needed to change a few things to make the app run, but it did eventually run with rails 3.2.12.  e.g.  I needed to make `Role`'s title `attr_accessible` and make all the models derived from `ActiveRecord::Base`, and remove the timestamps in `roles_users` table.  In `routes.rb`, I had:

```
  devise_for :users
  mount Refinery::Core::Engine, :at => '/cms'
```

Before integrating with refinerycms, authenticate_user! worked.  if I direct my browser to http://localhost:3000/vault, it will redirect me to http://localhost:3000/users/sign_in with devise's login form.  but after integrating with refinerycms, that didn't work.  When I pointed the browser to the same url of http://localhost:3000/vault, it simply redirected me back to http://localhost:3000, though with the notice "You need to sign in or sign up before continuing.".  The login form was not shown.  The log file showed

```
Started GET "/vault" for 127.0.0.1 at 2013-03-18 20:29:01 +0800
Processing by RestrictedContentController#vault as HTML
Completed 401 Unauthorized in 0ms
cache: [GET /] miss
cache: [GET /] miss
```

It never tried to redirect me to http://localhost:3000/users/sign_in, as in the case without refinerycms.

When I pointed the browser to to http://localhost:3000/users/sign_in, it showed an error where the error was 

```
 Showing /home/hau/lab/refinery_test1/app/views/devise/sessions/new.html.erb where line #5 raised:

undefined method `user_session_path' for #<ActionDispatch::Routing::RoutesProxy:0x007fbbfb6aa770>
```

It did not have the original `user_session_path`.  How would refinerycms engine take over the rendering of this page?  I wasn't accessing anything under `/cms`, refinerycms' mount point.

**Comment by uneventan** [comment]
scoping views and using ```main_app.new_user_session_path(resource_name)``` & ```main_app.new_user_password_path(resource_name)``` should jump out of refinerycms scope
