### ISSUE TITLE
Stylesheets are not loaded correctly in backend on Heroku

### ISSUE THREAD

**Issue by GCorbel** [refinery/refinerycms#2225]
Hello,

I have a website with a very standard backend. It works fine in local but for heroku I have this :
![Capture du 2013-03-26 06:15:06](https://f.cloud.github.com/assets/1296201/302186/49f4c650-95fe-11e2-9a92-257f931bedd9.png)

It seems the file "admin.css" is not loaded correctly. I followed the procedure on this page : http://refinerycms.com/guides/heroku.

Do you have an issue?

**Comment by divyankk** [comment]
where is this application.rb file? What is its location?

**Comment by GCorbel** [comment]
@divyankk django is evil. This is an issue for Rails.
