### ISSUE TITLE
undefined method `page_path' when linking to page in application.html layout

### ISSUE THREAD

**Issue by jurriaan** [refinery/refinerycms#2264]
When linking to a page in application.html using:

``` ruby
<%=link_to 'Articles', Refinery::Page.find('articles') %>
```

It works perfectly when viewing pages, but when I go to a url generated by an extension I get the following error:

```
undefined method `page_path' for #<#<Class:0x007f8daa9f5328>:0x007f8daa9f7858>
```

**Comment by ezuhaib** [comment]
I use this helper:

    def link_to_page(name)
        @page = Refinery::Page.friendly.find(name)
        link_to @page.title.gsub('-',' ').capitalize , @page.url
    end
