### ISSUE TITLE
HTML5 closing video tag is deleted  / extra source tag added

### ISSUE THREAD

**Issue by stpn** [refinery/refinerycms#2284]
Hello, looked through the issues / googled but didn't find something like this..
Whenever I try to add <video> tag which comes with <source> tag and expect to get something like this:

```
 <video id="my_video_1" class="video-js vjs-default-skin" controls
  preload="auto" width="640" height="264"
  poster="my_video_poster.png"
  data-setup="{}">
  <source src="Beastie.mp4" type='video/mp4'>
</video>
```

I instead get this:

```
  <video id="video_1" class="video-js vjs-default-skin" width="640" height="264" data-setup=" {&quot;autoplay&quot;: false,&quot;controls&quot;: true,&quot;preload&quot;: true,&quot;loop&quot;: true}"><source src="/system/videos/W1siZiIsIjIwMTMvMDUvMjkvMTJfMTlfMTRfNjMyX0JlYXN0aWUubXA0Il1d/Beastie.mp4" type="video/mp4"></source>
```

Meaning - the source tag becomes a block and video looses closing tag.

I tried various whitelist configurations, but no luck.

**Comment by jstaff** [comment]
Can you just totally turn off this whitelisting stuff? I don't want it strip any tags? What is the reason for for stripping them in the first place?

**Comment by parndt** [comment]
The point is to strip out invalid tags, which may not make as much sense anymore with HTML5. I'm sure you could turn it off if you overrode the part of the WYMeditor file that does it.. I'd point you to it but it's been a while and I don't quite remember where it is.

**Comment by mitijain123** [comment]
@jstaff @parndt you can turn it off completely by overriding WYMeditor file classes.js and change the below code:

```
WYMeditor.XhtmlParser.prototype.parse = function(raw)
{
  this._Lexer.parse(this.beforeParsing(raw));
  return this.afterParsing(this._Listener.getResult());
};
```

To

```
WYMeditor.XhtmlParser.prototype.parse = function(raw)
{
  this._Lexer.parse(this.beforeParsing(raw));
  return raw;
};
```

Hope this will help you
