### ISSUE TITLE
Store images on s3 subfolder

### ISSUE THREAD

**Issue by marklazz** [refinery/refinerycms#2287]
Hi guys,

I'm trying to store images on a S3 storage. That works perfectly if we allow the images to be placed right below the bucket folder.

BUT I would like to organize it better, and configure a subfolder like: 'my-bucket/images'. That doesn't work, I tried to make it happened by changing this config attributes (under config/initializers/refinery/images.rb):
- config.s3_bucket_name (tried with: 'my-bucket/images', but this one only allows me to set the higher folder),
- config.datastore_root_path Or 
- config.dragonfly_url_format 

Let me know if I'm looking at the problem the wrong way or this is in fact a bug.

Btw: I have my refinerycms mounted at a custom url (i.e. /cms), which may be completely irrelevant, but just mentioning. Also I tried on a fresh up mounted at '/' at seems to have the same problem.

**Comment by amcritchie** [comment]
Hello, I'm using the latest version of Refinery, and am using the code in the comment above, but I get this error

/Users/alexandermcritchie/.rvm/gems/ruby-2.2.1/gems/dragonfly-1.0.12/lib/dragonfly/model/attachment_class_methods.rb:50:in `method_missing': storage_path is deprecated - use storage_options{|a| {path: ...} } instead (NoMethodError)

**Comment by amcritchie** [comment]
In the latest version of Refinery, you will need to use

    storage_options{|a| {path: "subfolder/#{image_name}"} }

Instead of

    storage_path { "subfolder/#{image_name}" }
