### ISSUE TITLE
[Edge] Bundler could not find compatible versions for gem "activerecord"

### ISSUE THREAD

**Issue by bvsatyaram** [refinery/refinerycms#2417]
I am unable to create a new rails project using the master branch.

I am trying to create a new rails project using refinerycms edge generate as follows:
`rails new application_name -m http://refinerycms.com/t/edge`

I did change the references to the local paths (/code/parndt/...) with the commented out github path.

I get the following error:

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    refinerycms (>= 0) ruby depends on
      activerecord (~> 3.0) ruby

    rails (= 4.0.0) ruby depends on
      activerecord (4.0.0)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    refinerycms (>= 0) ruby depends on
      rails (~> 3) ruby

    rails (4.0.0)
        rake    db:create
git://github.com/refinery/refinerycms.git (at master) is not checked out. Please run `bundle install`
```

Please help me fix this.

**Comment by kiran-exalogic** [comment]
Bundler could not find compatible versions for gem "refinerycms-core":
  In Gemfile:
    refinerycms-authentication-devise (~> 1.0) ruby depends on
      refinerycms-core (>= 3.0.0, ~> 3.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-core (4.0.0.dev)

**Comment by parndt** [comment]
Try:

    rails new myapp -m http://refinerycms.com/t/3.0.3

**Comment by kiran-exalogic** [comment]
Thank you now its working
