### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by bitcoiners** [refinery/refinerycms#2428]
Refinerycms should be made compatible with Rails 4.

**Comment by forever-sumit** [comment]
Hi Guys

I've existing Rails 4 app I need to integrate the Refinery CMS with I18n feature.
I've sussessfully done with the bundle but when I try to install Refinery  I got error for generator not found.

    $ rails generate refinery:cms --fresh-installation
    Could not find generator refinery:cms.

I'm using `ruby '2.1.3', Rails '4.1.5'`

Here is gist url for my complete gem file https://gist.github.com/forever-sumit/4d77fdf9fecbebc8f9cb

**Comment by g2gonzalez** [comment]
Hi Everyone,

I successfully installed Refinery by following the following two lines:

> gem install refinerycms
> refinerycms restaurant_cms

but when I change into the new directory and try and run the server i get the following error

> c:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties
3.2.21/lib/rails/railtie/configuration.rb:85:in `method_missing' : undefined method 'eager_load' for #<Rails::Application::Configuration:0x3aef648> (NoMethodError)

Any ideas? I am on Windows currently running:

* Ruby -> 2.1.5p273
* Rails -> 3.2.21 (although outside the project folder I have rails -> 4.2.0)
* Refinery -> 2.1.5

Thank you

**Comment by parndt** [comment]
If you want to use Rails 4:

```
rails new restaurant_cms -m http://refinerycms.com/t/edge
```

**Comment by g2gonzalez** [comment]
I think I know what I did wrong.

When first installing refinery i installed it within a different application. Not sure if that makes a difference. I have my sites folder where i keep all my apps, should i have ran the install refinery in that folder instead of in a project folder? Because right now i am running the command you suggested and it is looking for the bundles in the old application (that i also deleted). 

Is there a way to uninstall refinery and re-install a fresh install?

**Comment by parndt** [comment]
To uninstall a Refinery application just delete the directory and then you can start over.

**Comment by g2gonzalez** [comment]
I did do that but I'll give it another shot.

Any idea about the error message though?

**Comment by parndt** [comment]
No, I'm not quite sure where that comes from.. unless the project recently updated to a more recent version of the decorators gem and that version of Rails doesn't really support it?

**Comment by g2gonzalez** [comment]
Ok thanks. I'll play around with it some more and post any updates if I
find what was wrong.

Thanks for your help.

**Comment by RatnamRaju** [comment]
I am getting following errors, while upgrading the rails from 3 to 4x

Bundler could not find compatible versions for gem "refinerycms-core":
  In Gemfile:
    refinerycms-shoppingcarts (>= 0) ruby depends on
      refinerycms-core (< 2.2.0, >= 2.0.9) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-core (3.0.0)

**Comment by gwagener** [comment]
@RatnamRaju This looks like an issue with refinerycms-shoppingcarts. Rails 4 is only supported in Refinery 3 (master) and refinerycms-shoppingcarts is locked to Refinery 2. I can't find any reference to refinerycms-shoppingcarts in the usual places so I'm guessing it's something of yours and you should be able to update its dependencies.

**Comment by RatnamRaju** [comment]
@gwagener thanks for your quick response, can you please explain  bit more like what steps i need to do from my end for this 

Thanks for your help

**Comment by gwagener** [comment]
@RatnamRaju Most likely in the `refinerycms-shoppingcarts.gemspec` files there will be a line like `add_dependency "refinerycms-core", ">= 2.0.9, < 2.2.0"`. You'll want to change the second string to "~> 3.0.0". Also any other `add_dependency` lines that refer to Refinery gems will probably want to reference at least 3.

**Comment by RatnamRaju** [comment]
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    refinerycms-pages (~> 3.0.0) ruby depends on
      refinerycms-core (= 3.0.0) ruby depends on
        railties (< 5.0, >= 4.1.5) ruby

    rails (= 4.1.0) ruby depends on
      railties (4.1.0)

**Comment by bricesanchez** [comment]
refinerycms gems are not yet released. Do you use github version ?

You should use rails 4.2.0.

**Comment by RatnamRaju** [comment]
No I am upgrading rails from 3 to 4.1.0

**Comment by RatnamRaju** [comment]
Hello @gwagener I am getting number of dependency errors.

**Comment by RatnamRaju** [comment]
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    refinerycms-letter_to_editors (>= 0) ruby depends on
      refinerycms-settings (~> 2.1.1) ruby depends on
        refinerycms-core (~> 2.1.1) ruby depends on
railties (!= 3.2.0, != 3.2.1, != 3.2.10, != 3.2.11, != 3.2.2, !=
3.2.3, != 3.2.4, != 3.2.5, != 3.2.6, != 3.2.7, != 3.2.8, != 3.2.9, < 3.3, >=
3.1.11) ruby

    rails (= 4.0.0.rc1) ruby depends on
      railties (4.0.0.rc1)

**Comment by gwagener** [comment]
@RatnamRaju You'll need to make similar changes to refinerycms-letter_to_editors as you made to refinerycms-shoppingcarts. Also, for future reference questions such as these would be better asked in the Refinery Gitter room rather than on a GitHub issue.
