### ISSUE TITLE
Change documentation to reflect rails 4 support.

### ISSUE THREAD

**Issue by mijoharas** [refinery/refinerycms#2448]
reading this issue [here](https://github.com/refinery/refinerycms/issues/2428) it seems that rails 4 support is included in the master. Can we change the documentation to reflect this? sorry I would submit a PR for this but don't know enough about the software to trust not messing things up.

**Comment by dallas** [comment]
How can the front page of refinerycms.com say that the latest stable gem version is 2.1.5 and have as the second bullet point item down below that Refinery "Supports Rails 4.1" while the official "Getting Started" guides are a bit more divided on the issue with a note in step 1 stating:

> If you are not using an RVM gemset and you have Rails 4 installed, be sure to read the Rails Application Templates section below.

and the section that the "Rails Application Templates" link takes you to, says this:

> As Refinery CMS is not compatible with Rails 4 you may also need to specify the Rails version in case you are not using an RVM gemset:

So… which is it? Does Refinery support Rails 4? Does it not *officially* support Rails 4? It's a little confusing :disappointed:

**Comment by parndt** [comment]
We need to update our guides.  Refinery officially supports Rails 4, but there's not yet a released gem package for 3.0.0 as there are some APIs we are yet to fully finalise. 

Sorry for the confusion.

**Comment by dallas** [comment]
No problem, I can understand that. I just got really confused (and slightly frustrated) when I read the bullet point on the front page and then tried to follow the "Getting Started" guides only to discover that by default installing the `refinerycms` gem installs `rails` version `3.2.21` when I was fully expecting something in the `4.x` range. 

Will be nice to have version `3.0.0` released!
