### ISSUE TITLE
Content editor crashes IE 11

### ISSUE THREAD

**Issue by renaudleo** [refinery/refinerycms#2529]
With IE 11, entering any page with a WYSIWYG initialized crashes the browser completely. At least that's the common point I found between the different pages that crash the browser. Browsing the dashboard and indexes work just fine, but any page edit kills the browser.

You can reproduce the bug by logging in the demo site and going to http://demo.refinerycms.com/refinery/pages/main-site/edit (or by clicking edit on any page listed [here](http://demo.refinerycms.com/refinery/pages)).

![capture decran 2014-01-24 a 14 25 13](https://f.cloud.github.com/assets/617989/1998059/996f072a-852e-11e3-9daf-9ed4d1a94106.png)

I haven't been able to collect any log information, nothing shows up in the JavaScript console, I'm a bit clueless here.

I first thought it was a problem with WYMeditor itself, but the WYMeditor demos work just fine in IE 11, so I guess it may be a problem in the Refinery code itself, or in the patched (is it?) version of WYMeditor.

Anyway, seems like a major problem to me, if anyone has a clue of what's going on or where to look at, it would be appreciated!

**Comment by CJBrew** [comment]
This workaround isn't working for me at all. Unfortunately my (internal) customers will very likely want to use IE! 

I'm currently trying to identify whether there's an older revision I can safely use. Ruby 2.1.0, Rails 3.2.21, Refinery 2.1.5 crashed IE even with this fix.

**Comment by parndt** [comment]
If they're internal customers can't they use any browser you specify?

**Comment by CJBrew** [comment]
Well... perhaps. But it's not a great confidence booster for selling "Look at the shiny new version of our website" ;-)

It's a fair point. Right now I am not keen to use the 'stable' version as it crashes IE, yet I'm having trouble moving things to Edge / Rails 4. (e.g. see: https://github.com/refinery/refinerycms/issues/2835 -- for which there may be a manual intervention).

What I don't understand is why this fix worked for others but not me!

**Comment by javinto** [comment]
There is a little bit more to it than just the boot_wym.js.erb fix. Your browser will run into a
"ReferenceError: WYMeditor is not defined" javascript error on the front-end (See the browser Console)

For me this was a problem for one website using additional javascript functions that did not work any more. For most installations this error will not be a show stopper. 

To get rid of this error, alter your app/assets/javascripts/application.js file and remove
"require_tree ."
Explicitly require additional Javascript files if needed.

**Comment by CJBrew** [comment]
@javinto  would you be able to post here which extra files have to be `require`d ? If you've already figured that out it could save someone some work.

For now I am working with the `Edge` build, which goes through periods of instability but does seem to have a nicer interface on the Admin side... :)

**Comment by javinto** [comment]
With this patch always remove the Require_tree directive.

Only require extra javascript files if you have placed any. 

So if your javascript folder looks like:

refinery/boot_wym.js.erb
application.js
custom.js

Your application.js would look like this:
//= require jquery
//= require jquery_ujs
//= require custom


Op 28 jan. 2015, om 11:49 heeft CJBrew <notifications@github.com> het volgende geschreven:

**Comment by ryno1234** [comment]
Has this fix been implemented into the edge version of Refinery? I didn't see this issue referenced in any commits. I'm currently making a point to recommend Refinery but this is a show stopper and I'd prefer to know that the fix was implemented into the source vs having to patch it with the patch above.

**Comment by CJBrew** [comment]
Yes it's ok in the edge. The wym editor is also now in its own Gem.

**Comment by ryno1234** [comment]
Ok, thanks you @CJBrew !

**Comment by f3ndot** [comment]
Maintaining a legacy Rails 3.2 application and Refinery CMS 2.0.9 where the customer must use IE11.

I found the following things needed to be done:

```
$ bundle exec rake refinery:override javascript=refinery/boot_wym # the file you'll patch
$ bundle exec rake refinery:override javascript=refinery/wymeditor # the file that'll include override into pipeline
$ bundle exec rake refinery:override javascript='wymeditor**/{**/}*' # required for overriding wymeditor.js
```

Now patch the IE guard, because the authors of Internet Explorer were pricks and fooled `$.browser` to return mozilla instead of msie. So the original MSIE guard fails for IE11:

On approx. line 238 in boot_wym.js.erb change

```javascript
  if (!$.browser.msie) {
```

to

```javascript
  // IE11 lies and calls itself "mozilla" version 11.0
  if (!$.browser.msie && !($.browser.mozilla && $.browser.version === '11.0')) {
```

Not doing all of this resulted in the quick patch/override not actually getting compiled into wymeditor.js

* * *

Days like this makes me sad I maintain legacy systems. Best of luck to you Googlers who are in a similar position as I!
