### ISSUE TITLE
refinery helpers and variables not defined in other engines controllers for production environment

### ISSUE THREAD

**Issue by waiting-for-dev** [refinery/refinerycms#2534]
- I have refinery installed as an engine in a Rails application.
- In this application there is another engine
- In my layout file there are calls to three refinery helpers or variables: `browser_title`, `refinery_user?` and `@meta`

If I visit an action from the controller of that other engine in production environment, I get `browser_title` and `refinery_user?` non defined errors, or calls to nil for `@meta`. This doesn't happen in development environment.

In fact, I had think that the error would happen always. So I think the strange thing is that they are working for the development environment...

Is it a bug or am I confused?

Thanks a lot

**Comment by Kagetsuki** [comment]
I think @waiting-for-dev is doing something wrong. We're refinery_user? in production just fine. @waiting-for-dev can you be more specific/give some code samples?

@parndt maybe go ahead and close this again unless we can verify it as an issue. Stale issues drive me nuts.

**Comment by waiting-for-dev** [comment]
Sorry, not working with refinerycms anymore.

**Comment by simi** [comment]
@parndt can't be this related to latest reload bug?

**Comment by parndt** [comment]
It's possible but probably caused by something else due to the age of the issue

**Comment by Kagetsuki** [comment]
@simi even if it was related there's a huge lack of information here. I think it's best to not try and relate issues without any obvious direct connection.
