### ISSUE TITLE
Error with Pages - "save and continue editing"

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2616]
Could you try to simulate my error pls? I don't have clear Refinerycms and in my Refinery is this error.

Workflow:

Refinerycms > Pages (default locale = :cs)

> - Main page
> - edit title + uncheck "Show in menu"
> - "Save and continue with editing"
> - Switch to ":en" locale

Maybe it doesn't matter what language is default and the second.

**Comment by prokopsimek** [comment]
Refinerycms 3 is ok...

**Comment by parndt** [comment]
Hooray!
