### ISSUE TITLE
authentication.rb.erb template doesn't get executed for a dummy app

### ISSUE THREAD

**Issue by darmenise** [refinery/refinerycms#2648]
When the dummy app is generated, an `authentication.rb` initializer should be generated, based on the `authentication.rb.erb` template.

But, presently, only the `core.rb` and `i18n.rb` initializers are generated.

**Comment by parndt** [comment]
You're totally right, and this is still an issue.

**Comment by parndt** [comment]
Removed authentication extension in #2940
