### ISSUE TITLE
Move tab reordering to the edit user page

### ISSUE THREAD

**Issue by awagener** [refinery/refinerycms#2663]
As discussed in https://github.com/refinery/refinerycms/pull/2597 and https://github.com/refinery/refinerycms/pull/2634, moving this rarely used item would simplify both shifting the admin tabs to the left hand side, and removing the dashboard.

On the edit user page, should it be:
a) a button that activates the current functionality, so that the tabs can be moved in place; or
b) a list of tab names, that can be dragged and dropped in a similar way to page reordering

a) is more intuitive; b) would allow easy reordering of other users tabs by an admin.

Other options suggested were removing the feature entirely (presumably allowing developers to set a site wide order somewhere programmatically).  If it was removed, could it live on as a plugin for the rare site that requires it?

**Comment by parndt** [comment]
Anyone want to tackle this?

**Comment by stefanspicer** [comment]
I actually had a different approach.  I found that the first thing I did every time when I created a new user was login as them and reorder their menu to something that made sense.  I couldn't imagine any of our clients actually looking to change the order, so I built a "plugin sorter" in code.  It is simply a weighting system from 1-100 that you can specify when you register the plugin, or override it in the site config.  You can see the details in #2999.  Basically, I've moved the plugin sorting to a "per site" basis, and not a "per user" basis.  What do you think of that?

**Comment by anitagraham** [comment]
1. I like the idea of a heading in the menu - I am thinking about implementing a megamenu again, and this may be a useful option.
2. I have started - but paused - transforming the Refinery backend to the Zurb Foundation Framework. Following @ghoppe 's new design (and now yours), and the proposal from @awagener  from last year I held off looking at design and focussed on the js instead.  (Also real life.)
3. Quo vadis? (Google translate tells me it should be "Ubi imus?, but then who would understand?)

**Comment by stefanspicer** [comment]
If you look at our design in #2999, we've considered a second layer to it, like submenus.  Sort of like wordpress, but better.  Is this what you mean by megamenu @anitagraham?

**Comment by anitagraham** [comment]
@stefanspicer I think my comment could equally well have gone to #2999. 
 I am just wondering - with several redesign options presented - which way Refinery will go - and where to focus my effort. I had done some work towards reworking the current backend into Foundation, but obviously with these lovely new designs I'd be better off looking at the js. 

A megamenu (for me) is a front end menu that is more like a panel of menu items. It is easier to handle than a flyout menu (you don't lose focus so easily etc. 
![Uploading Megamenu.png…]()

**Comment by stefanspicer** [comment]
The Megamenu.png didn't appear to upload correctly.

**Comment by anitagraham** [comment]
Hmmm first upload didn't work. The second appeared to. I will try again.
![megamenu](https://cloud.githubusercontent.com/assets/397118/8248214/c88c6eec-168e-11e5-885a-30d4f3e1fb04.png)

**Comment by parndt** [comment]
I believe that in #2940 we've removed the reordering from Refinery and it's now up to authentication solutions to implement it.
