### ISSUE TITLE
Image broken in Rails 4, Refinerycms Edge

### ISSUE THREAD

**Issue by oshovah** [refinery/refinerycms#2681]
HI, since you have added the alt and title attribute to the Images, its seems to be broken.

Every time i restart the Server, all the Images that are included via the image picker to the wymeditor have a broken link.

Bad Request 400 (The SHA parameter you gave (f6321f708287aa9b) is incorrect)

Then i have to re insert the Image and it works until i restart the Server....

Regards Dino

EDIT: 
Its a very strange behavor. Sometime the images disapear by just refreshing the Page. And sometimes they re apear... In the Backend Image library, the url of the Original images are always working. But if you insert them into the page, its seems a little bit broken...

**Comment by bsodmike** [comment]
Thanks for the tip @anitagraham and I've got this set in `config/initializers/refinery/images.rb`, however, on each request the SHAs change and sometimes the images render, sometimes they do not.  When a broken image is rendered, the Dragonfly app returns 400 `The SHA parameter you gave (90a61826b4ba3d66) is incorrect`.

I'm on refinerycms (3.0.0), master branch SHA f453944e17ab7

**Comment by bsodmike** [comment]
@anitagraham Hi Anita, I'va set the secret for Dragonfly but this issue continues.  We are not a lone it seems:
https://github.com/markevans/dragonfly/issues/387#issuecomment-108263982

I've further described my issue there ^^

**Comment by ddean** [comment]
After migrating to Rails 4, and the newest version of refinerycms, this issue is breaking a bunch of our old images in production.  Is there a way via the Refinery initializers to disable the Dragonfly SHA check until this gets fixed? We've tried the above solutions and nothing is working.

**Comment by bsodmike** [comment]
Hi @ddean, follow my steps here (https://github.com/refinery/refinerycms/issues/2931#issuecomment-111683767) to disable DOS protection in Dragonfly.  I also had older content with the SHA param attached and they are rendering fine.

**Comment by ddean** [comment]
@bsodmike that seems to be working great. Thanks, much appreciated. I was thinking that I would have to scrape all the img elements in our pages and recalculate their src values.

**Comment by bsodmike** [comment]
My pleasure @ddean.  Also dropped you an email :)
