### ISSUE TITLE
Pretty-Urls on extension

### ISSUE THREAD

**Issue by mattherick** [refinery/refinerycms#2684]
Hi!
If I follow this guide

http://refinerycms.com/guides/pretty-urls

I always get errors in the admin backend.

    ActiveRecord::RecordNotFound in Refinery::MyExtension::Admin::ProductsController#edit 

I configured my model like following:

      # translations with globalize3
      translates :name, :slug
      
      extend FriendlyId
      friendly_id :name, :use => :slugged

For getting the correct object I use following method in the frontend:

    def self.by_slug(slug)
      self.joins(:translations).where("refinery_my_extension_product_translations.locale = ? AND refinery_my_extension_product_translations.slug = ?", ::Globalize.locale.to_s, slug).readonly(false).first
    end

The frontend is working, and the backend always throws the ActiveRecord not found error.

And my backend controller simple contains following:

    module Refinery
      module MyExtension
        module Admin
          class ProductsController < ::Refinery::AdminController
          
            crudify :'refinery/my_extension/product',
                :title_attribute => 'name',
                :xhr_paging => true
          end
        end
      end
    end

Is there something broken or the pretty-url guide not correct anymore?

**Comment by prokopsimek** [comment]
@mattherick I need to have :finders in friendly_id initializer

```
  config.use :finders
```
& use globalize
```
      extend FriendlyId
      translates :title, :slug
      friendly_id :title, :use => [:globalize]
```
