### ISSUE TITLE
Problems with documentation (Relating resources in an extension)

### ISSUE THREAD

**Issue by CJBrew** [refinery/refinerycms#2691]
It appears there may be some step missing from the documentation here
http://refinerycms.com/guides/relating-resources-in-an-extension,
or perhaps things have changed to break it...
I'd be happy to update the documentation if someone can diagnose the problem, as I'm having the same issue with one of the sites I'm working on.

After following this guide (after the "Multiple Resources" guide) I can add some `event types`. However, on attempting to create a new Event, the "collect" function that creates the selection widget in the form fails, since the set of `event_types` is not populated.

```
NoMethodError in Refinery/events/admin/events#new

Showing /home/chris/Dev/refineryTest/vendor/extensions/events/app/views/refinery/events/admin/events/_form.html.erb where line #11 raised:

undefined method `collect' for nil:NilClass
Extracted source (around line #11):

8:     <%= f.text_field :title, :class => 'larger widest' -%>
9:   </div>
10: 
11:   <div class='field'>
12:     <%= f.label :date -%>
13:     <%= f.datetime_select :date -%>
14:   </div>
Trace of template inclusion: vendor/extensions/events/app/views/refinery/events/admin/events/new.html.erb

Rails.root: /home/chris/Dev/refineryTest

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"locale"=>:en}
Show session dump

Show env dump

Response

Headers:

None
```

Also, I noticed the line in event_type.rb ` acts_as_indexed :fields => [:name]` and the corresponding `acts_as_indexed` line in event.rb model no longer exist. Adding them results in an error

```
Routing Error

undefined method `acts_as_indexed' for #<Class:0x000000027779a8>
Try running rake routes for more information on available routes.
```

**Comment by bricesanchez** [comment]
This issue is outdated, i close it.
