### ISSUE TITLE
Engine is not loading helper

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2718]
Hi, Refinerycms 3 is not loading all engines helpers? Or why it isn't loaded?

Ref.: http://stackoverflow.com/questions/9809787/why-is-my-rails-mountable-engine-not-loading-helper-methods-correctly

**Comment by parndt** [comment]
This works fine for me:

```
[2.2.0p0] ~/sandbox/application_name
$ cat app/helpers/foo_helper.rb 
puts "blah"

module FooHelper
end

[2.2.0p0] ~/sandbox/application_name
$ bin/rails console
blah
Loading development environment (Rails 4.1.9)
irb(main):001:0> 
```

Note that if you have spring started then it won't print anything on subsequent loads.

**Comment by parndt** [comment]
@prokopsimek are you still able to reproduce this issue?

**Comment by prokopsimek** [comment]
@parndt  Yes, I'm. Sorry, I am in a hurry! I will reproduce it to the end of week... Be patient pls :)

**Comment by parndt** [comment]
I will wait!

**Comment by prokopsimek** [comment]
If I moved my gem in separate repository, I need to include e.g. ReservationsHelper in ApplicationHelper:

```ruby
module ApplicationHelper
	include ::Refinery::Reservations::ReservationHelper
end
```

but I found a solution...

[gem_path]/lib/refinery/reservations/engine.rb
```ruby
      before_inclusion do
        ::ApplicationController.send :helper, Refinery::Reservations::ReservationsHelper
        Refinery::AdminController.send :helper, Refinery::Reservations::ReservationsHelper
      end
```

because I need this helper in BE & FE too :-)
