### ISSUE TITLE
images and resource files on s3 lands in same folder

### ISSUE THREAD

**Issue by andelo** [refinery/refinerycms#2719]
It seems that all files uploaded into /images and /resources are placed in the bucket under the same folder. 

Example of file uploads.
An image `x.jpg` is uploaded and is being created in `s3://bucket/2014/01/02/03/04/05//06/x.jpg`
A pdf (resource) `x.pdf`is uploaded and is being created in `s3://bucket/2014/01/02/03/04/05/06/x.pdf`

And it works on the public site as I can download images and resources (pdf files). 
Albeit I currently get HTTP ERROR 502 on some newly uploaded .pdf files (maybe related to this).

When I want to make a local copy of all data, refinery expects 'resource-fies' to be in `public/system/refinery/resources`and images in `public/system/refinery/images`. So now I first have to move files to their correct destination folder depending on file extension.

I was expecting refinery to mirror the folder structure you have locally also in the s3 bucket so that doing a recursive copy back would work seamlessly. 

What I want, and expect, is that refinery maps the /system folder structure as it is on the s3://bucket.

**Comment by wmakley** [comment]
I'd be interested in whether anyone had a solution to this? I don't see why we couldn't change the default dragonfly config. It's a huge pain to figure this out for the first time, and it's not like dragonfly should care about Refinery. I suppose I could use two buckets.

**Comment by parndt** [comment]
@wmakley what would you propose?

**Comment by wmakley** [comment]
I'll do a pull request if I can figure out how to get Dragonfly working properly. I see some other conversations about using Cloudfront with Dragonfly, but no definitive "basic" S3 setup. Ideally I want, like OP, for my S3 bucket to look exactly like my public folder and not combine files and images. I am still trying to get Dragonfly to do this.

**Comment by andelo** [comment]
this should be reopened

**Comment by wmakley** [comment]
I never figured it out, I just used the merged folder for a while and eventually gave up on the project because Heroku was too slow.
