### ISSUE TITLE
New look and feel idea for editing interface

### ISSUE THREAD

**Issue by simmerz** [refinery/refinerycms#2731]
We've spent quite some time using and working with Refinery, and we feel a key area that lets it down is its editing interface - the bit our clients use day to day. With that in mind, and after some lengthy discussions with @parndt, I'd like to propose an overhaul of the admin interface, and I've put together some wireframes to showcase those ideas.

Dashboard
---------------
![000_dashboard](https://cloud.githubusercontent.com/assets/24327/4861439/1f97343e-6103-11e4-9c41-0846bdba0b58.png)
An idea for the dashboard would allow extensions to add "Quick Add" links, and add certain items to the activity feed. I feel the current activity feed leaves a little to be desired, but this would allow extensions to bring their key features to the front of the site. There's also scope for extensions to add separate "sections" as they can now, as shown by the "Quick Blog Post Draft" block.

The new nav can collapse to just the icons, and extensions can push user configurable settings into the "Settings" menu option, in the same way iOS does for apps.

Pages
--------
![010_pages](https://cloud.githubusercontent.com/assets/24327/4861495/a0029460-6103-11e4-8d90-881c446ad3bd.png)
This simple pages list takes a minimally different view to what's there already, but makes the interface a little easier to use, and allows wider screens to take advantage.

![020_new_page_no_sections](https://cloud.githubusercontent.com/assets/24327/4861497/a60a0a32-6103-11e4-9520-553af1867c14.png)
Sometimes, your page doesn't want any sections, so a mini interface to still make it straight forward to add one if your page has none to start with (this will mostly be seen on pages that forward on).

![030_new_page_sections](https://cloud.githubusercontent.com/assets/24327/4861499/aa9db4a4-6103-11e4-967d-c96deed9a4df.png)
We've gone with removing the tabs. When reading a page, clicking tabs is somewhat more difficult a user action than scrolling a wheel mouse or swiping on a tablet or phone screen. It's also easier to copy and paste from one to the other if needs be. You can see the wireframe incorporates extensions such as `refinerycms-copywriting` and `refinerycms-images`, which can place their blocks either in the main content column, or in the settings and additional features column. This isn't supposed to suggest that these specific extensions should go there, but it shows the possibilities.

I've not gone further than this, but the idea to me is sound. I'd welcome feedback, and any help in making this happen for 4.0 would be much appreciated too.

Tom

**Comment by CJBrew** [comment]
@gwagener I quite often find it useful to be able to edit websites on my phone, typically someone asks me for an urgent fix just as I've got on a train... Anyway, anything we do here will still be better than the dog-awful Drupal admin pages.
