### ISSUE TITLE
Bug in "Home" page button when mounting to a directory other than root

### ISSUE THREAD

**Issue by alexrwave** [refinery/refinerycms#2740]
I've been deploying Refinery CMS 2.1.4 and I found a bug when I try to change it to "/subfolder" instead of "/". I follow the steps from your guide 5, changing the "mount" line in config/routes.rb file to "/subfolder" and everything seems to work. But in the "new application root" I click on "Home", it redirects me to the old root, where there is nothing, giving a Routing Error.
I add some screenshots
![home - company name - mozilla firefox_002](https://cloud.githubusercontent.com/assets/4057165/4924752/a2102224-6525-11e4-8869-acffb34e5248.png)
![action controller exception caught - mozilla firefox_006](https://cloud.githubusercontent.com/assets/4057165/4924758/a5b942f2-6525-11e4-8356-1c8c29005600.png)
Then I tried to change the link propertie for the Home page. Now the link is correct but I get a 404 error clicking on it or simply accessing to the main url.
![home - page not found - company name - mozilla firefox_007](https://cloud.githubusercontent.com/assets/4057165/4924864/756410d6-6526-11e4-8b6e-c5027600aab6.png)
I also tried to overwrite the root rule in routes.rb with a custom one without success.
Could you say me if I'm doing something wrong?
Thank you very much.

**Comment by parndt** [comment]
Perhaps related to rails/rails#5122
