### ISSUE TITLE
Non-Default Page Parts look funky!

### ISSUE THREAD

**Issue by parndt** [refinery/refinerycms#2741]
I don't know when exactly this crept in, but it's a real problem:

![screenshot 2014-11-05 20 54 51](https://cloud.githubusercontent.com/assets/10128/4929753/fe417c50-6557-11e4-8233-4a72bc32dbdf.png)

**Comment by bricesanchez** [comment]
@ghoppe I've seen you have made change to Fix MSIE bug https://github.com/ghoppe/refinerycms-wymeditor/commit/6e2173ad620620a8acab2d845e7ef47ea6410c79 is it working now ? Could you provide a pull request ?

**Comment by simi** [comment]
Fixed by https://github.com/parndt/refinerycms-wymeditor/pull/18. 

![screenshot-localhost 3000 2015-01-21 01-58-34](https://cloud.githubusercontent.com/assets/193936/5829333/0a75f9e8-a111-11e4-9a9a-3d8001d03bca.png)

send :two_hearts: to @ghoppe
