### ISSUE TITLE
Delete page translation gives error

### ISSUE THREAD

**Issue by javinto** [refinery/refinerycms#2782]
I have a page in three languages: NL,EN,DE but I want to remove the german (DE) translation for that page only. If I remove the german body text and title and save the page I get an error: no to_slug method for nil class. 

RefineryCMS: 2.1.5

**Comment by parndt** [comment]
@javinto would you be interested in working on adding one?

**Comment by javinto** [comment]
Hi Philip,

I would certainly be interested but the next two weeks I will have a lack of time to participate.

If that is no problem I will let hear of me in two weeks time.

Best regards,

Jan


Op 26 jan. 2015, om 09:48 heeft Philip Arndt <notifications@github.com> het volgende geschreven:

**Comment by prokopsimek** [comment]
:+1: Good one feauture!

**Comment by prokopsimek** [comment]
@javinto ? :)

**Comment by evenreven** [comment]
Did this ever get fixed or just closed, @parndt ? I can't get it to work, but I think this should be the default behaviour when deleting from inside the editor window. My site (on 4.0.3 now) has many pages with erroneously added translations due to a bug in 2.1.5, and I'd love to remove some of those without having to delete and re-add all of them.

**Comment by parndt** [comment]
@evenreven I can't recall, exactly, but I think this was simply closed. Would love to know if you can achieve what you're after though?

**Comment by evenreven** [comment]
@parndt I could take a crack at it, but I think it's a bit too complex for me, I'm just a website editor/project manager (client-side, so to speak) with rudimentary Ruby knowledge. The agency we hire could probably do it, but I can't justify the expense right now. Sad, but that's the way it goes. Maybe later.

Can you give me any pointers if I should look at it myself? We need to delete the current translation only, shouldn't be THAT different from finding the page id and deleting that? It can even be another button, doesn't necessarily have to dynamically/conditionally affect the existing button.

**Comment by parndt** [comment]
It would need some sort of endpoint added in the pages admin for handling a translations DELETE HTTP request
