### ISSUE TITLE
RefineryCMS with Rails 4.1

### ISSUE THREAD

**Issue by GinBlades** [refinery/refinerycms#2795]
I'm using Rails 4.1 with Ruby 2.1.5, and I've come across a few issues. I followed the recommended setup on [RefineryCMS.com](http://refinerycms.com/download), and I'm working with a fresh install.

1. If I set `config.backend_route` to anything other than `refinery`, I can't update the tab order in the  backend. This is the error from the console when I try.

        Started POST "/refinery/update_menu_positions" for 127.0.0.1 at 2014-12-07 07:54:17 -0600
        ActionController::RoutingError (No route matches [POST] "/refinery/update_menu_positions")

2. The second tab, by default named "Side Body", has it's `visual_editor_box` width set to 97px by something in the JavaScript. The problem persists even if you change the name of the second tab, but it does not affect a 3rd tab.
3. When I added the `bootstrap-sass` gem, Sprockets could not find the required javascript file. The javascript is usually included in `application.js` using the line: `//= require bootstrap-sprockets`. The error is simply:

        ActionView::Template::Error (couldn't find file 'bootstrap-sprockets'
        (in /home/shaun/sites/test/ref4/app/assets/javascripts/application.js:16))

    I tried the AngularJS gem, `angularjs-rails`, and the JavaScript files were loaded using the standard require statements without error. I double checked that this version of `bootstrap-sass` wasn't causing the error on a fresh Rails project, and the JavaScript loaded without error as instructed.

There are workarounds for each of these, though they are somewhat limiting.

1. Don't rename the backend route.
2. Ignore the second tab, add a third.
3. Import javascript

I checked to make sure version 2.1.5 for Rails 3.2 did not have these issues. It did not. Attached is a screenshot of the second tab width issue.
![refinery-second-tab](https://cloud.githubusercontent.com/assets/6261671/5331297/7d3611f6-7dea-11e4-9811-7a922a087733.png)

**Comment by CJBrew** [comment]
Has there been an issue created for the bootstrap-sprockets.js problem? I'm encountering this and it doesn't happen with a clean Rails app.

I'm not sure what the reason for it would be, other than perhaps Refinery does something different with assets...?

**Comment by CJBrew** [comment]
Here's a Gist with tests that I hope reproduce the bootstrap-sprockets problem as a minimal example.

https://gist.github.com/CJBrew/23183647e23386d4800f

get the files
run `./testRails` to build a basic rails app -- this should load the /hellos page OK
run `./testRefinery` to build a refinery app -- this breaks on loading bootstrap

**Comment by ghoppe** [comment]
@CJBrew FYI I was able to fix this issue by moving `gem 'bootstrap-sass', '~> 3.3.1'` to the top of the Gemfile, underneath the `gem 'rails'` line. I don't know why it breaks if it's after `refinerycms` in the Gemfile.

**Comment by CJBrew** [comment]
@ghoppe odd, but I'll try that fix. Currently I have to remember about manually copying the bootstrap javascript files in ;-)

**Comment by bsodmike** [comment]
I'm seeing this in Rails 4.1.8, and Refinery fetched from the master branch SHA f453944

**Comment by bsodmike** [comment]
Managed to fix this by getting this CSS rendered in the admin,

```css
.wym_skin_refinery {
	border: 1px solid #CCCCCC;
	background: #F2F2F2;
	padding: 5px 5px 0px 5px;
	width: 100% !important;
}

.wym_skin_refinery .wym_iframe iframe {
	width: 100% !important;
	background: white;
}
```
