### ISSUE TITLE
Edit current page link on site_bar

### ISSUE THREAD

**Issue by darmens** [refinery/refinerycms#2800]
I think it would be nice to have an "edit this page" link next to "Switch to your website editor".

Something like:

```
link_to t('.edit_this_page', site_bar_translate_locale_args), refinery.edit_admin_page_path(@page), data: { no_turbolink: true } if @page 
```

**Comment by bricesanchez** [comment]
Hello all ! when i use the "Edit page button", the page is redirected to the admin but the admin CSS is not loaded. I think it's a turbolinks problem because when a reload the final page the admin CSS appears.

In my Gemfile, i call Turbolinks like this : 
```ruby
[...]
# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-turbolinks'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
[...]
```

And in the applications.js, i call it like that : 
```ruby
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require turbolinks
[...]
```

What is wrong ?

**Comment by simi** [comment]
I think `data: { no_turbolink: true }` should be used for that link if turbolinks are enabled.

**Comment by bricesanchez** [comment]
I'm agree with @simi, we doesn't need turbolink for this link because we are going to the admin who have a completely different CSS.

**Comment by bricesanchez** [comment]
@darmens By the way, your Edit current page link is a cool feature :)

**Comment by parndt** [comment]
@simi @bricesanchez cool please send a Pull Request (PR) to fix it :)

I have a turbolinks branch where I'm attempting to get the admin working properly with turbolinks but as per usual there are weird bugs.

**Comment by darmens** [comment]
So I think I should add `data: { no_turbolink: true }` to the [site_bar_edit_link helper](https://github.com/darmens/refinerycms/blob/60e2cb5d5ea7c7ec7b12f032a45b9bc1b3b9bd54/core/app/helpers/refinery/site_bar_helper.rb#L14) right ?

PS: Thank you @bricesanchez.
