### ISSUE TITLE
Can't insert images from search results

### ISSUE THREAD

**Issue by darmens** [refinery/refinerycms#2817]
How to reproduce:

* `rails new app_name -m http://refinerycms.com/t/edge`

Start server, login to backend and then:

* upload some images from the Images tab
* create a new page
* click on "Add Image" to open the Add Image dialog
* search for an image using the top right search form in the dialog
* select an image from the search results
* click on "Insert"

No effect..

**Comment by parndt** [comment]
I can confirm this issue.

**Comment by oshovah** [comment]
is there a workaround? Strugle with same Issue...

**Comment by darmens** [comment]
Yes: fon now you can search them from the main Images tab instead.

**Comment by oshovah** [comment]
You cant insert a image from the main images tab into a page. Thats not a workaround.

The Search function works fine. Even on the Add image dialog

**Comment by darmens** [comment]
I know, you also have to manually copy and paste the image src from the search results to your page in the html editing view.
I find it easier to do that from the Images tab because there you have the eye-shaped link to view the image in another browser tab.

**Comment by parndt** [comment]
This was fixed by refinery/refinerycms-acts-as-indexed#3
