### ISSUE TITLE
jquery-rails dependency

### ISSUE THREAD

**Issue by jpbullalayao** [refinery/refinerycms#2822]
Hello! I attempted to do a bundle install for this gem since I'd like to use it. However, I get this dependency error:

![screen shot 2015-01-06 at 10 32 27 am](https://cloud.githubusercontent.com/assets/3538024/5633767/60d46d3e-958f-11e4-86e3-c8acec87a377.png)

Is there a way to make this gem bundle install successfully and work with jquery-rails 3.1.1, which is the latest version that I have in my app's Gemfile?

**Comment by parndt** [comment]
@jpbullalayao maybe, but this is a stable branch so it would have to be fully backward compatible.  Do you know if jquery-rails 3.1.1 has any backward incompatibilities since 2.3.0?
