### ISSUE TITLE
ActiveRecord::RecordNotFound in Refinery::Admin::PagesController#edit when I set the i18n.rb locale to 'zh-CN'

### ISSUE THREAD

**Issue by FlowerWrong** [refinery/refinerycms#2828]
Hi! I an using the refinerycms. But I have some problem.
And the refinerycms version is the `master`.
`gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'`
After I set the `i18n.rb` in `config/initializers/refinery` locale to 'zh-CN', like this
```ruby
  # config.default_locale = 'zh-CN'

  # config.current_locale = 'zh-CN'

  # config.default_frontend_locale = 'zh-CN'

  # config.frontend_locales = ['zh-CN']
```
I get the `ActiveRecord::RecordNotFound in Refinery::Admin::PagesController#edit` error when I edit the page.
After I switch to `en`, it's ok.

**Comment by parndt** [comment]
After you do this, you have to re-seed the pages as the existing pages all have `:en` locales.

Alternatively, you could run something like this in your `rails console`:

```ruby
Refinery::Page::Translation.where(locale: 'en').update_all(locale: 'zh-CN')
```

Thank you for your detailed report! I hope this helps you.

**Comment by FlowerWrong** [comment]
@parndt Thx. But `Refinery::Page::Translation.where(locale: 'en').update_all(locale: 'zh-CN')` can not solve my problem. After I change `config.frontend_locales = ['zh-CN']` to `config.frontend_locales = [:'zh-CN', :en]`, it's ok. I think that I can not use str here, just symbol.

**Comment by parndt** [comment]
Oh, excellent! Thanks for posting your solution.

**Comment by parndt** [comment]
Do you think it'd be a good idea for it to raise an exception if you try to pass a string?

**Comment by FlowerWrong** [comment]
@parndt I think we can use both string and symbol to config it.
This maybe better.

**Comment by parndt** [comment]
True.

**Comment by parndt** [comment]
I think I found [the relevant code](https://github.com/refinery/refinerycms-i18n/blob/master/lib/refinery/i18n/configuration.rb#L17-L21)

**Comment by FlowerWrong** [comment]
@parndt It is work for me. Change [this line](https://github.com/refinery/refinerycms-i18n/blob/master/lib/refinery/i18n/configuration.rb#L19) to `config.locales.keys.include?(locale.try(:to_sym))`
