### ISSUE TITLE
issues with refinerycms gem 

### ISSUE THREAD

**Issue by sagarghai** [refinery/refinerycms#2830]
i am trying to use refinerycms and i keep getting these errors  whenever i do bundle install
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    refinerycms (~> 2.1.5) ruby depends on
      refinerycms-authentication (= 2.1.5) ruby depends on
        actionmailer (!= 3.2.0, != 3.2.1, != 3.2.10, != 3.2.11, != 3.2.2, != 3.2.3, != 3.2.4, != 3.2.5, != 3.2.6, != 3.2.7, != 3.2.8, != 3.2.9, < 3.3, >= 3.1.11) ruby

    rails (= 4.1.7) ruby depends on
      actionmailer (4.1.7)

**Comment by parndt** [comment]
You can't use version 2.1.5 with Rails 4.
If you wish to use Rails 4, install this way:

    rails new appname -m http://refinerycms.com/t/edge

**Comment by sagarghai** [comment]
then which version supports rails 4

**Comment by mattherick** [comment]
only the edge version.. the master branch of this github repo..

**Comment by sagarghai** [comment]
how do i include it as a gem in my gemfile

**Comment by mattherick** [comment]
@parndt already told you to use following command:

    rails new appname -m http://refinerycms.com/t/edge

take a look at the script:

    http://refinerycms.com/t/edge

and you can see what will be executed, if you generate your new rails application with this template..
