### ISSUE TITLE
Admin CSS rewrite

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#2833]
Hello all!

After #2731 and #2832 issues, i would like to rewrite the CSS of the admin, my goal are :
* to fix responsive issue,
* to use the full width of the window
* to clean or reorganize CSS for the admin.
* to use neat/bourbon in order avoid HTML rewrite.
* to make it a little more A11Y.

I don't want to rewrite all HTML because i don't want to break the engine generator.
That's why i want to use Neat/Bourbon and perhaps bitters.

If someone wants to help me to define the goals, i'm really open to consider them in my dev.

I will begin to work when we are agree with the main goals.

I think, i will start with : 
* ~~new site bar CSS (responsive and framework free)~~ #2848
* login page : Could we change the way we style it ? And instead use the frontend CSS of the website?
* Admin layout
* Admin index
* Admin show

## Requests ##
* Titles on top of pages (@parndt)
* Improve all cases of pipes in unordered list (What happens if all pages are inside root page - @parndt)

**Comment by anitagraham** [comment]
* The dark grey tabs aren't very clear on the black background. 
* -1 for unaligned icons.
* The whole edit box needs ...something... a border? a title? It is a bit underwhelming at the moment.

**Comment by bricesanchez** [comment]
I close this issue because it's outdated.
