### ISSUE TITLE
Multiple tabbed fields css broken?

### ISSUE THREAD

**Issue by jess** [refinery/refinerycms#2852]
Just me or is this happening with anyone else? I have a custom engine with multiple html editor fields. Refinery (nicely) tabbed them all together for me, but the css seems off...or possibly there is some js editing the elements' width.

![image](https://cloud.githubusercontent.com/assets/91473/5882923/d5d51162-a31b-11e4-85c7-6a10bf7a20e3.png)

![image](https://cloud.githubusercontent.com/assets/91473/5882931/e71a8588-a31b-11e4-9a5e-934e0717c37a.png)

**Comment by bricesanchez** [comment]
Hello, this bug is normally fixed in #2741. You should do a bundle update.

**Comment by jess** [comment]
Thanks @bricesanchez !

I case anyone else happens upon this, I had already run `bundle update refinerycms` before posting the issue. To get the fix I had to `bundle update refinerycms-wymeditor`
