### ISSUE TITLE
Can't create a new rails app anywhere

### ISSUE THREAD

**Issue by jsmarshall** [refinery/refinerycms#2854]
I can't use rails new anywhere because the lines

  gem 'refinerycms-wymeditor', version
  load Gem.bin_path('refinerycms-wymeditor', 'rails', version)

were added to my rails command under ~/.rvm/

What is going on here??

Thanks

**Comment by jsmarshall** [comment]
It's also in the global rake command

**Comment by jsmarshall** [comment]
I guess this might not be the right place for this and I'm not sure how these bootstrap commands get written/generate but it seems like the refinerycms-wymeditor gem is somehow clobbering rails and rake commands.

**Comment by CJBrew** [comment]
That's interesting...

I suspect this is something behind the binstubs warning/error I'm seeing here:
https://github.com/refinery/refinerycms/issues/2847#issuecomment-71273204

**Comment by CJBrew** [comment]
@jsmarshall do you know more than I about gemspec files? 

My guess is there's something here which is causing this issue:
https://github.com/parndt/refinerycms-wymeditor/blob/master/refinerycms-wymeditor.gemspec

but I don't understand the file well enough.

**Comment by CJBrew** [comment]
It's pretty clear that the `.rvm/gems/ruby-x.y.z/bin/rails` file is getting overwritten by the version from the wymeditor gem. Raising an issue on the wymeditor.

**Comment by jsmarshall** [comment]
Yeah it seems so. I was out all day. Thanks for doing that.

**Comment by parndt** [comment]
Fixed by parndt/refinerycms-wymeditor#23
