### ISSUE TITLE
"Edit this page" is misleading for extension pages

### ISSUE THREAD

**Issue by parndt** [refinery/refinerycms#2858]
```
As a refinery user
When I visit a blog post's page
And I click "Edit this page"
I should be on the edit form for this post (Refinery::Blog::Posts#edit) and not for the extension's page.
```

Technically what this will mean is that in the site bar helper we will need to use another thing other than `@page`, but default to `@page` or have `@page` be the default thing registered as this other thing.  Kind of how we handle `@meta` now.

**Comment by parndt** [comment]
@bricesanchez @simi

**Comment by bricesanchez** [comment]
Could we have 2 buttons ? One to edit the page, the other to edit the blog post ?

**Comment by parndt** [comment]
@bricesanchez yes, we probably could.  Or we could remove the button for pages with `link_url` set?
