### ISSUE TITLE
Dragonfly S3 support need not be required by default

### ISSUE THREAD

**Issue by parndt** [refinery/refinerycms#2859]
When @simi migrated us to version 1.0.0 of Dragonfly (thanks!) `dragonfly-s3_data_store` came along for the ride.

This comes with an enormous amount of sub-dependencies (i.e. all of fog) which isn't required unless s3 is actually being used.

Is there any way that we can optionally support it? Maybe if `--heroku` is specified when using the installer templates or if `--s3` is specified (which doesn't currently exist)?

Or, we can just carry on like we have..

**Comment by simi** [comment]
I think it should be removed as a hard dependency and properly documented (actually link to http://markevans.github.io/dragonfly/data-stores/ is enough IMHO).

**Comment by parndt** [comment]
We'll have to make the `--heroku` installation option work as before, though.. or maybe this doesn't rely on S3 to get started?
