### ISSUE TITLE
Upgrading from 0.9* series to 2.1.5

### ISSUE THREAD

**Issue by ryno1234** [refinery/refinerycms#2860]
I'm going to upgrade from 0.9* to the 2.1 series. I realize this is not straight-forward at all and will essentially be creating a new site. Given that I'll have to re-create everything, I'm curious as to how far out 3.0 is and with 3.0, will I need to re-create my 2.1 site for 3.0 or is there going to be a clearly defined upgrade path?

**Comment by parndt** [comment]
Personally, I'd go with 3.0 right now.  We're gearing up to release this as soon as we can get everything that is blocking it finished off.  Here's how:

```
rails new application_name -m http://refinerycms.com/t/edge
```

**Comment by ryno1234** [comment]
:+1:
