### ISSUE TITLE
Browser crash when editing page, IE 11 / Win 7 64 bit

### ISSUE THREAD

**Issue by ryno1234** [refinery/refinerycms#2869]
When editing a page on the demo site, the WYSIWYG editor displays an error message. This has been confirmed on 3 separate systems.

![ie_crash](https://cloud.githubusercontent.com/assets/92051/5942317/96acf3b6-a6cb-11e4-9a67-468765318082.JPG)

**Comment by ryno1234** [comment]
The actual error being reported is:

Unhandled exception at 0x62C9AAED (mshtml.dll) in iexplore.exe: 0xC0000005: Access violation reading location 0x00000018.

**Comment by ghoppe** [comment]
see https://github.com/refinery/refinerycms/issues/2529

**Comment by ryno1234** [comment]
Thanks @ghoppe!
