### ISSUE TITLE
Refactor page_title_with_translations method

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#2870]
Hello !

I would like to make this method more generic in order to be used by page engine and others like blog,...

Could we do this  : 
```ruby
def title_with_translations(record)
  record.title.presence || record.translations.detect { |t| t.title.present?}.title
end
```

Instead of : 
https://github.com/refinery/refinerycms/blob/master/pages/app/helpers/refinery/admin/pages_helper.rb#L52
```ruby
def page_title_with_translations(page)
  page.title.presence || page.translations.detect { |t| t.title.present?}.title
end
```

And move it in another helper who is load on every admin controllers like : 
https://github.com/refinery/refinerycms/blob/master/core/app/helpers/refinery/admin_helper.rb

**Comment by bricesanchez** [comment]
What if the title of the record has "fullname" as field name and not title, could we deal with it?

**Comment by parndt** [comment]
The official solution is to alias it to title but we could probably do better.

This whole situation would be better off as not a helper anyway as something like this: (cc @robyurkowski ?)

```ruby
class TranslationPresenter
  def initialize(record)
    @record = record
  end

  def call(field)
    record.send(field).presence || 
      record.translations.select {|t| t.send(field).presence}.compact.first
  end

  private
  attr_accessor :record
end
```

**Comment by gwagener** [comment]
Oo, nice presenter solution :+1:

**Comment by parndt** [comment]
@bricesanchez if you still want this, can you implement the presenter and perhaps a test or two? If you don't still want it, then I guess we'll close the issue :smile:

**Comment by bricesanchez** [comment]
I still want this but after my other but after my other PR be merged.

**Comment by bricesanchez** [comment]
Please continue discussion in the PR #3125
