### ISSUE TITLE
refinery:form don't work with mysql

### ISSUE THREAD

**Issue by aribeiro** [refinery/refinerycms#2872]
Hi, I've been try create a simple contact form for my project, but after I follow all the steps, every time I try go to the contact form, the server go into a loop, and I got a error in the browser.
I tested it using sqlite3, and it works, than I try to only replace the database, run the migrations, and the problem start.

It is a new project, but must to run in mysql, this is the steps I did:
```code
rails new project -m http://refinerycms.com/t/edge
cd project
rails g refinery:form Contacts name email message:text
bundle install
rails generate refinery:contacts
rake db:migrate
rake db:seed
```
Of course I follow I the steps to create the user, was able to access the admin interface, etc. The only problem is the form, I also add the ```strong_parameters``` for the form when I was using the ```sqlite3```, so only option is a Database issue.

Thanks

**Comment by CJBrew** [comment]
@aribeiro  I have pushed a PR for the Forms that fixes many issues. 
https://github.com/refinery/refinerycms/pull/2922
It's pending a merge (and possible rework) but maybe you can test it out.
