### ISSUE TITLE
[Feature request] Custom/Translate page part title

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#2873]
When we add a page part, the title is generated from the slug, but in french countries, we love coding in english but seeing a french tab name. 

Could we have 2 fields, the first like now and the second "Custom title different from the slug" ?
And/or able to translate this field.

**Comment by parndt** [comment]
Possibly, but.. could you open this as a pull request instead? :smile:

**Comment by bricesanchez** [comment]
#2875 :)
