### ISSUE TITLE
Heroku production cache pages and extensions configuration

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#2876]
Hello,

I'm deploying 3 RefineryCMS 3.0 websites on Heroku in production mode in the next week and i've a big problem to make cache working correctly on my apps.

I've added `Memcached cloud 25` in the heroku add-on .

Added this config in config/environnements/production.rb
```ruby
...
# Use a different cache store in production.
  # config.cache_store = :mem_cache_store
  if ENV["MEMCACHEDCLOUD_SERVERS"]
      config.cache_store = :dalli_store, ENV["MEMCACHEDCLOUD_SERVERS"].split(','), { :username => ENV["MEMCACHEDCLOUD_USERNAME"], :password => ENV["MEMCACHEDCLOUD_PASSWORD"] }
  end
...
```

Added those gems in Gemfile : 
```ruby
...
group :production do
  gem 'dragonfly-s3_data_store'
  gem 'rails_12factor'
  gem 'rails_on_heroku'
  gem 'newrelic_rpm'
  gem 'actionpack-page_caching'
  gem 'dalli'
end
...
```

What i'm missing ?

If i would like to cache images and pages in my extensions like refinery-products, do i have to add this method in my product controller : 
https://github.com/refinery/refinerycms/blob/master/pages/app/controllers/refinery/pages_controller.rb#L8-L9 ?

Is image are cacheable, if yes, how?

Thanks !

**Comment by parndt** [comment]
For image caching, read through the Dragonfly documentation. Usually it's as easy as having this:

```ruby
group :production do
  gem 'rack-cache'
end
```

**Comment by bricesanchez** [comment]
Thank you @parndt, i thought it was more complex to install cache for Heroku on production. After your input i've followed this guide : https://devcenter.heroku.com/articles/rack-cache-memcached-rails31

It works great ! 
Soon, I will PR you a guide for this.

=)
