### ISSUE TITLE
Does reorder cross pages not work?

### ISSUE THREAD

**Issue by pengisgood** [refinery/refinerycms#2880]
@jokklan @parndt 
I search the issue list and found #2254, #2255, which discuss about this issue. 
But I found the reorder cross pages still doesn't work. Does anyone has the same problem with me?

Here is my gemfile.lock:
GIT
  remote: https://github.com/refinery/refinerycms
  revision: 114fdd1a71f18cbcc6e0ac7df2eade4144fade99
  branch: master
  specs:
    refinerycms (3.0.0)
      bundler (>= 1.2.2)
      refinerycms-authentication (= 3.0.0)
      refinerycms-core (= 3.0.0)
      refinerycms-images (= 3.0.0)
      refinerycms-pages (= 3.0.0)
      refinerycms-resources (= 3.0.0)
    refinerycms-authentication (3.0.0)
      actionmailer (>= 4.0.2, < 4.2)
      devise (~> 3.0, >= 3.2.4)
      friendly_id (>= 5.0.0.rc1)
      refinerycms-core (= 3.0.0)
    refinerycms-core (3.0.0)
      actionpack (~> 4.1.5)
      activerecord (~> 4.1.5)
      awesome_nested_set (~> 3.0.0)
      coffee-rails (~> 4.0.0)
      decorators (~> 1.0.0)
      jquery-rails (>= 2.3.0)
      jquery-ui-rails (~> 5.0.0)
      railties (~> 4.1.5)
      refinerycms-i18n (~> 3.0.0.dev)
      sass-rails (~> 4.0.0)
      truncate_html (~> 0.9)
      will_paginate (~> 3.0.2)
    refinerycms-images (3.0.0)
      dragonfly (~> 1.0.0)
      dragonfly-s3_data_store (~> 1.0.0)
      refinerycms-core (= 3.0.0)
    refinerycms-pages (3.0.0)
      awesome_nested_set (~> 3.0.0)
      babosa (!= 0.3.6)
      friendly_id (~> 5.0.1)
      globalize (~> 4.0.0)
      refinerycms-core (= 3.0.0)
      seo_meta (~> 2.0.0.rc.1)
    refinerycms-resources (3.0.0)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 1.0.0)
      dragonfly-s3_data_store (~> 1.0.0)
      refinerycms-core (= 3.0.0)

**Comment by parndt** [comment]
Unfortunately we never got this working

**Comment by tgspears** [comment]
Hi there!
I ran into the same problem where I needed to reorder engine entries between pages.

I wasn't able to find a solution but I did find a work-around.

By putting ```WillPaginate.per_page = 100``` (or whatever number makes sense) in ```app/controllers/application_controller.rb``` you can avoid the problem. You don't have to worry about reordering between pages if there's only one page!

Hope this helps!

**Comment by pengisgood** [comment]
actually, we did it like this also.
