### ISSUE TITLE
unable to update to rails 4.2.0

### ISSUE THREAD

**Issue by sagarghai** [refinery/refinerycms#2881]
here is my gemfile: 
source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'sqlite3'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do

  gem 'byebug'

  gem 'web-console', '~> 2.0'

  gem 'spring'
end

gem 'refinerycms-i18n', github: 'refinery/refinerycms-i18n', branch: 'master'
gem 'refinerycms', github: 'refinery/refinerycms', branch: "master"

gem 'protected_attributes'

i keep getting this error :

esolving dependencies...
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    refinerycms (>= 0) ruby depends on
      refinerycms-authentication (= 3.0.0) ruby depends on
        actionmailer (< 4.2, >= 4.0.2) ruby

    rails (= 4.2.0) ruby depends on
      actionmailer (4.2.0)

**Comment by bricesanchez** [comment]
Hello,

Refinery is not yet compatible with 4.2.0 but it will be soon : #2816

You can contribute if you want :)

**Comment by sagarghai** [comment]
thanks @bricesanchez , but now i have manually chnged the version of rails to 4.0.0 and a new error has occured:  

Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    refinerycms (>= 0) ruby depends on
      refinerycms-core (= 3.0.0) ruby depends on
        actionpack (~> 4.1.5) ruby

    rails (= 4.0.0) ruby depends on
      actionpack (4.0.0)

**Comment by bricesanchez** [comment]
You should change for `gem 'rails', '4.1.8'` and run `bundle update`

**Comment by bricesanchez** [comment]
Could i close this issue @sagarghai ?
