### ISSUE TITLE
Crudify with consistency

### ISSUE THREAD

**Issue by bsodmike** [refinery/refinerycms#2885]
Hi @parndt,

In my latest project, I've extracted something I've done in the past and that's to alter the admin views to refer to the collection via a consistent `@items` instance variable; quick example

``` erb
<section id='records' class='tree'>
  <%= render 'records' %>
</section>
<aside id='actions'>
  <%= render 'actions' %>
</aside>
<%= render '/refinery/admin/make_sortable', options: {tree: true, replaceContentsAfterUpdate: true} if !searching? and ::Refinery::Frontends::Admin::TaxonsController.sortable? && @items.many? %>
```

Here's the concern,

``` ruby
module Refinery
  module Crud
    module Items

      class << self
        def append_features(base)
          super
          base.extend(ClassMethods)
        end
      end

      module ClassMethods

        def crudify_as_items
          module_eval %(
            prepend_before_action :set_singular_alias,
              :only => [:update, :destroy, :edit, :show]
            prepend_before_action :set_plural_alias

            def set_singular_alias
              find_#{self.crudify_options[:singular_name]}
              @item = @#{self.crudify_options[:singular_name]}
            end

            def set_plural_alias
              find_all_#{self.crudify_options[:plural_name]}
              paginate_all_#{self.crudify_options[:plural_name]} if #{self.crudify_options[:paging]}
              @items = @#{self.crudify_options[:plural_name]}
            end

            # Ensure all methods are protected so that they should only be called
            # from within the current controller.
            protected :set_singular_alias,
                      :set_plural_alias
          )
        end

      end

    end
  end
end
```

...and for now, I've got it loading via an initialiser (v3.0.0 off master)

``` ruby
require 'refinery/crudify_as_items'

Rails.application.config.before_initialize do
  ::Refinery::ApplicationController.module_eval do

    puts "Overriding ::Refinery::ApplicationController - #{__FILE__[/(app[\/\w\.]+|config[\/\w\.]+|vendor[\/\w\.]+)/]}"

    def self.included(base) # Extend controller
      base.helper_method :home_page?, :local_request?, :just_installed?,
                         :from_dialog?, :admin?, :login?

      base.protect_from_forgery # See ActionController::RequestForgeryProtection

      base.send :include, Refinery::Crud # basic create, read, update and delete methods
      base.send :include, Refinery::Crud::Items # get crudify instances as `@items` and `@item`

      if Refinery::Core.rescue_not_found
        base.rescue_from ActiveRecord::RecordNotFound,
                         ::AbstractController::ActionNotFound,
                         ActionView::MissingTemplate,
                         :with => :error_404
      end
    end

  end
end
```

I couldn't think of something better than `Refinery::Crud::Items`, may be `Refinery::Crud::WithConsistency`

Thoughts?

**Comment by bsodmike** [comment]
P.S. `set_plural_alias` and `set_singular_alias` could do with some guards to prevent running those finders each time the filters run, i.e. they should only run if the instance variable hasn't already been set.

**Comment by parndt** [comment]
So in terms of an interface, are you asking for this sort of thing:

```ruby
crudify :something, as: :item
```

Which would set the singular to `@item`  and the plural to `@items` ?

?

**Comment by bsodmike** [comment]
Yes, exactly.  and that would be an alias to `something` in the above example.  This allows the views to be a bit more generic.

We tend to work with a fair bit of common views (in the admin area at least); it just becomes more work when partials start to take on the name of the extension generated, hence this approach.

**Comment by parndt** [comment]
Well, rather than being an alias it would just completely change the variable name.

**Comment by parndt** [comment]
Do you still want this?

**Comment by bsodmike** [comment]
Hi @parndt - may end up depending on the exactly use-case. Now, `as: :item` simply changes the variable name, but the case that I encountered was that I wanted the views to be generic, or to be precise data-agnostic.

Some may consider that controller/views references should reflect the resource, but this makes it a lot more work when switching the resource for the same boilerplate views.

I suppose, looking at this from the way Refinery extensions follow Rails' model/resource, the way it's done now is OK.  I'd leave this up to your final decision, of course.  It might be worth checking if others would prefer resource agnostic controller/views, i.e. partials are given a generic name, and simply changing the `crudify` model won't cause breakage.

**Comment by anitagraham** [comment]
I've thought before that the views and css might benefit from more consistency between record types.
A qualified +1 (qualified because perhaps I don't know enough about this)

**Comment by parndt** [comment]
@bsodmike that is a bigger change! However, I understand why you'd want that and I'm not opposed to it. But I won't implement it :smile:

**Comment by parndt** [comment]
I'm closing this as a pull request would be a better medium to discuss it - as it's not really an issue that needs fixing.
