### ISSUE TITLE
Can't use refinerycms as an engine inside an existing rails 4 application.

### ISSUE THREAD

**Issue by hzbadr** [refinery/refinerycms#2887]
I'm trying to install refinerycms in an existing rails 4 application, but it seems engine works only with rails 3.2 applications.
Do you have plans to support rails 4? If so, would you give an estimate when it will be available?

**Comment by parndt** [comment]
You can use it now:

```ruby
gem 'refinerycms', '~> 3.0.0', git: 'https://github.com/refinery/refinerycms', branch: 'master'
```

We're working on getting it out as a released gem, just a few things to tidy up, but it is working pretty well from GitHub too.
