### ISSUE TITLE
generated form doesn't work

### ISSUE THREAD

**Issue by loaighoraba** [refinery/refinerycms#2896]
I have created a form using refinery:form schedule_demos [some fields], ran db:migrate and db:seed and everything is ok.

Now when I set my app to point to /schedule_demos (as this is the link generated in the menu for me), it says no page is found. When I checked the routes in the generated form, I found the following:
```ruby
  namespace :schedule_demos do
    resources :schedule_demos, :path => '', :only => [:new, :create] do
      collection do
        get :thank_you
      end
    end
  end
```
so there is no index action supported! I thought of adding it myself, and now the error generated is
```
No route matches {:action=>"new", :controller=>"refinery/schedule_demos/schedule_demos", :locale=>:en}
```
so what to do? and by the way, there is a method in the controller:

```ruby
      def find_page
        @page = Refinery::Page.where(link_url: "/schedule_demos/new").
                               includes(:parts).first_or_create!
      end
```
when tried to call schedule_demos/new it throw exception because there is no title given to the created page, which is required, so I'm not sure if I'm missing something.

Thanks a lot

**Comment by parndt** [comment]
By convention, because it's a form, it uses the `new` action.  If you want to change that, the easiest way may be to alias your route.  This would look like:

```ruby
# Frontend routes
namespace :schedule_demos do
  resources :schedule_demos, :path => '', :only => [:create] do
    collection do
      get :new, path: '', as: :new
      get :thank_you
    end
  end
end
```

**Comment by parndt** [comment]
You'd then have to update the seeds to set the page's link_url to `/schedule_demos` instead of `/schedule_demos/new`

**Comment by parndt** [comment]
And of course anywhere that the `link_url` is mentioned it'll have to be modified.

**Comment by loaighoraba** [comment]
when pointing it to /schedule_demos/new it gives the exception: Validation failed: Title can't be blan

seems find_page has something to do with this.

**Comment by parndt** [comment]
Why are you pointing to `/schedule_demos/new`?

**Comment by loaighoraba** [comment]
I don't get it. What should I do now to use the form? what is the url I should point to ? The code is as was generated, I didn't change it

**Comment by parndt** [comment]
You were saying you wanted the form to be at `/schedule_demos` instead of `/schedule_demos/new`? Or were you saying that the menu links to the wrong place?

If it's just the menu link, edit the page for it and under advanced options set its "forward this page" setting to `/schedule_demos/new`

**Comment by loaighoraba** [comment]
ok thanks a lot it works now :)
