### ISSUE TITLE
Help: Overriding views from my private engine.

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2899]
I have my private gem called "refinerycms-skeleton". It is something like refinerycms-core, but a little bit modified. 
I have there modified initializers and so on... 
I created my own edge file, which I use to generate my application.
I would like to override my gem's modified view with "rake refinery:override", but it is still overriding from refinerycms

It does mean e.g.:
1) refinerycms = app/views/refinery/_head.html.erb
2) my own gem "skeleton" = app/views/refinery/_head.html.erb
3) run "rake refinery:override" > copied view from "skeleton", not from refinerycms!
but if
1) refinerycms = app/views/refinery/_footer.html.erb
2) my own gem "skeleton" = does not have _footer.html.erb
3) run "rake refinery:override" > copied view from "refinerycms"!

My project is loading gems this way:
1) Have I my own _head view? No!
so next step 2) Has gem "refinerycms-skeleton" views _head? No!
so next step 3) So load view _head from refinerycms-core! Yes!

@parndt Could you help me how to get it? :) Is it needed to modify anything there: https://github.com/refinery/refinerycms/blob/master/core/lib/refinery/cli.rb#L113?

**Comment by simi** [comment]
Look at
https://github.com/refinery/refinerycms/blob/master/core/lib/refinery/cli.rb#L8-L12

2015-02-18 15:05 GMT+01:00 Prokop Simek <notifications@github.com>:

**Comment by prokopsimek** [comment]
```
2.1.5 :015 >   Refinery::Plugins.registered.pathnames.map{|p| %w(app vendor).map{|dir| puts p.join(dir, "views" )} }.flatten.uniq
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-i18n-d085574f6a29/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-i18n-d085574f6a29/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/core/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/core/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/gems/refinerycms-wymeditor-1.0.6/app/views
/home/user/.rvm/gems/ruby-2.1.5/gems/refinerycms-wymeditor-1.0.6/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/skeleton-7880abaf422a/skeletors/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/skeleton-7880abaf422a/skeletors/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-page-images-dbf841a2a30f/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-page-images-dbf841a2a30f/vendor/views
/home/user/Sites/example_cz/vendor/extensions/products/app/views
/home/user/Sites/example_cz/vendor/extensions/products/vendor/views
/home/user/Sites/example_cz/vendor/extensions/tags/app/views
/home/user/Sites/example_cz/vendor/extensions/tags/vendor/views
/home/user/Sites/example_cz/vendor/extensions/case_studies/app/views
/home/user/Sites/example_cz/vendor/extensions/case_studies/vendor/views
/home/user/Sites/example_cz/vendor/extensions/people/app/views
/home/user/Sites/example_cz/vendor/extensions/people/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/authentication/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/authentication/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/images/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/images/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/resources/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/resources/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/pages/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-6a3fb0afedf7/pages/vendor/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-settings-10c12da53e0c/app/views
/home/user/.rvm/gems/ruby-2.1.5/bundler/gems/refinerycms-settings-10c12da53e0c/vendor/views
```

My private gem is on 7th row and refinerycms-core is on the 3rd row...

It should be ok, isn't it?

**Comment by simi** [comment]
That's the spirit.

2015-02-18 16:14 GMT+01:00 Prokop Simek <notifications@github.com>:
