### ISSUE TITLE
Full path for url_for

### ISSUE THREAD

**Issue by IvanVP** [refinery/refinerycms#2910]
Hello

I have - for example two pages

  - ExamplePage
      -  InnerExamplePage

In console I have

refinery.url_for(examplepage)
 => "http://www.example.com/pages/examplepage" 

refinery.url_for(examplepage.url)
 => "/examplepage" 
and /examplepage/innerexamplepage"  for innerpage

Is here some method to recieve uri without "pages" but with hostname like
"http://www.example.com/examplepage" 
"http://www.example.com/examplepage/innerexamplepage" ?

**Comment by parndt** [comment]
This had some refactoring recently, can you please reopen this if you're still facing issues?
