### ISSUE TITLE
Not able to delete page 

### ISSUE THREAD

**Issue by andywenk** [refinery/refinerycms#2911]
I am trying to delete a page and receive the following error:

https://friendpaste.com/5Xl3q51uvi6uMU7KpNUKXh

I have tried to debug this but I can't figure out what the problem is. Not sure which model is missing the `name` attribute. This is affecting all pages what is a bot of a blocker for the CMS ;-)

Some version info:

  * refinerycms (2.1.5)
  * refinerycms-acts-as-indexed (1.0.0)
  * refinerycms-authentication (2.1.5)
  * refinerycms-core (2.1.5)
  * refinerycms-dashboard (2.1.5)
  * refinerycms-i18n (2.1.0)
  * refinerycms-images (2.1.5)
  * refinerycms-pages (2.1.5)
  * refinerycms-resources (2.1.5)

Thanks for any help!

Cheers

Andy

**Comment by parndt** [comment]
How strange, do you get the same result when you try to delete it from the rails console?

**Comment by andywenk** [comment]
ugh! I can't use the rails console ...

    $ rails c                                                                                              ⏎ ✭ ✱
    /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
    /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- test/unit/testcase (LoadError)
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/test_case.rb:1:in `<top (required)>'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/railties-3.2.17/lib/rails/console/app.rb:2:in `<top (required)>'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/railties-3.2.17/lib/rails/application.rb:312:in `initialize_console'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/railties-3.2.17/lib/rails/application.rb:152:in `load_console'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/railties-3.2.17/lib/rails/commands/console.rb:27:in `start'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
      from /Users/userblabla/.rvm/gems/ruby-2.2.0@myproject/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
      from script/rails:6:in `require'
      from script/rails:6:in `<main>'

**Comment by parndt** [comment]
okay, that's a new one.. I am not sure why that is - some problem with Rails and Ruby 2.2?

**Comment by andywenk** [comment]
I have switched to 2.1.4 and now I get this:

    Rendered /Users/andwen/.rvm/gems/ruby-2.1.4@schule-neugraben-rails/gems/refinerycms-pages-2.1.5/app/views/refinery/admin/pages/index.html.erb within layouts/refinery/admin (21.9ms)
    Completed 500 Internal Server Error in 39.7ms

    NoMethodError - undefined method `title' for nil:NilClass:
      refinerycms-pages (2.1.5) app/helpers/refinery/admin/pages_helper.rb:53:in `page_title_with_translations'

I can now use the rails console but this is really strange.

Which ruby version do you suggest?

**Comment by parndt** [comment]
how bizarre! Which version of globalize is being used?

**Comment by andywenk** [comment]
git:master ❯❯❯ bundle list | grep global                                                                                  ✭ ✱
      * globalize (3.1.0)

Yeah it's really strange and I am not sure how to fix this. I have Ruby 2.2 on the server so that seems to be a no go. But having this error now with 2.1.4 is strange ...
