### ISSUE TITLE
How-To: Rails 4.2 + domain-specific language switching + /blog URL translation

### ISSUE THREAD

**Issue by LouisStAmour** [refinery/refinerycms#2916]
So the following is in part because I needed to language-specific override blog URLs at run-time and part because I couldn't figure out an easier way to do it (yet).

We'll start with the RefineryCMS admin. If you want some domain name matching for localization setting, it ended up requiring the following. (I used the ENV part for testing...)

```ruby
# admin_controller_decorator.rb
Refinery::AdminController.class_eval do
  before_filter :set_locale

  def set_locale
    locale = if ENV['LANG'] == 'FR' || request.host.match(/frdomainname/)
               :fr
             else
               :en
             end
    Refinery::I18n.default_locale = Refinery::I18n.current_locale = I18n::locale = locale
    Refinery::Blog.page_url = I18n.t('routes.news')
    Globalize.locale = params[:switch_locale] ||= Refinery::I18n.current_locale
  end
end
```

Note the `:switch_locale` setting above, this is to workaround an issue where the default was being set for me as Globalize.locale but that wasn't carried over in the link_to partial when creating blog posts. This was the easiest way to ensure it was set, and that its setting carried over to the rest of the app by also setting Globalize.locale. (What can I say, it's an incantation that seems to work for me right now.)

My routes file ended up looking something like this, so it could still receive requests at non-/blog URLs before it was switched over. There's a side-effect in that sometimes /cms/<custom url> works and sometimes (more often) it prefers /cms/blog. Haven't pinned this one down yet. The good news is it only seems to have affected bookmarks so far.

```ruby
# routes.rb
  mount Refinery::Core::Engine, at: '/'

  Refinery::Core::Engine.routes.draw do
    # override refinerycms-blog routes here manually for both languages
    namespace :blog, as: 'blog_en', path: 'news' do
      root :to => "posts#index"
      resources :posts, :only => [:show]
    end
    namespace :blog, as: 'blog_fr', :path => 'nouvelles' do
      root :to => "posts#index"
      resources :posts, :only => [:show], path: 'articles'
    end
  end if Refinery::Blog.page_url == '/blog'
```

That last if statement is there to avoid a (Rails?) bug where making changes to files would end up reloading things and causing a "routes already defined" error for my custom added routes above. I figure if Blog.page_url isn't actually /blog, then I don't need the work-around routes as one or the other will have already been set. Devise was mentioned often as an example of an engine with easy-to-override routes. Either that or the page URL for blogs somehow has to be locale-aware. I'm just glad I didn't also have to translate crud operation names in the admin area.

Note also that all of this code isn't currently thread-safe I suspect. But this has been tricky enough that I've been tempted quite a few times to simply switch to io.js ;-)

So finally we get to the ApplicationController where the usual language selection resides:

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  def set_locale
    locale = if ENV['LANG'] == 'FR' || request.host.match(/frdomainname/)
               :fr
             else
               :en
             end
    Refinery::I18n.current_locale = Globalize.locale = I18n::locale = locale
    Refinery::Blog.page_url = I18n.t('routes.news')
  end
end
```

Again, very similar, except this time we override Globalize.locale too -- in all cases, I want content served on this domain to be in French, no exceptions. In theory, I shouldn't need to go through all this, but ... this works in practice and that's all I care about.

Finally, we've the i18n.rb config file, it's short:

```ruby
# encoding: utf-8

Refinery::I18n.configure do |config|
  config.frontend_locales = [:en, :fr]
  config.locales = { en: "English", fr: "Français" }
  config.url_filter_enabled = false
end
```

The config.url_filter_enabled is what hides the /en/ or /fr/ prefixes on URL paths. It almost works. I'm currently running with a patch submitted as #2914.

The above is what I figured out through trial and error the past day or two. It's running on a Gemfile with the latest versions of everything below (as of right now) via git, since I couldn't be bothered to look up actual version numbers and needed to Rails 4.2-compatible all the things.

```ruby
gem 'rack', :git => 'https://github.com/rack/rack.git'
gem 'rails', :git => 'https://github.com/rails/rails.git', :branch => '4-2-stable'
gem 'devise', :git => 'https://github.com/plataformatec/devise.git'
gem 'routing-filter', :git => 'https://github.com/svenfuchs/routing-filter.git'
gem 'refinerycms', :git => 'https://github.com/refinery/refinerycms'
gem 'refinerycms-blog', :git => 'https://github.com/refinery/refinerycms-blog', :branch => 'rails-4-2'
gem 'refinerycms-acts-as-indexed', :git => 'https://github.com/refinery/refinerycms-acts-as-indexed'
gem 'globalize', :git => 'https://github.com/globalize/globalize.git'
gem 'friendly_id', :git => 'https://github.com/norman/friendly_id.git'
gem 'friendly_id-globalize', :git => 'https://github.com/norman/friendly_id-globalize.git'
```

Posting this here as a snapshot in time, in case anyone else happens to need domain-specific language switching and/or language-specific blog URLs and wanted a quick workaround. Might also help folks trying to get running under Rails 4.2 as I was.

Finally, I encountered a bug in refinerycms-blog where the edit URLs weren't working on the admin panel. A switch to force lookups by ID number like everywhere else seemed to do the trick (and doesn't affect the front-end because it's a, what, meta monkey patch?)

```ruby
# posts_controller_decorator.rb
Refinery::Blog::Admin::PostsController.class_eval do
  before_filter do
    Refinery::Blog::Post.class_eval do
      def to_param
        id.to_s
      end
    end
  end
end
```

**Comment by parndt** [comment]
@LouisStAmour I think the `refinerycms-blog` edit URL bug you mentioned should be solved by a `bundle update`

**Comment by prokopsimek** [comment]
:+1:
