### ISSUE TITLE
Page part title propagates into other page parts

### ISSUE THREAD

**Issue by anitagraham** [refinery/refinerycms#2917]
When a new page part (content section) is created a new editor tab is created with the tab header having the title of the page part.    If, before saving the page, the user looks at another page part, it will have the new page part name inserted into any lists it holds. Once the page is saved and refreshed the extra text is not present.

![new page part](https://cloud.githubusercontent.com/assets/397118/6545029/5751e01c-c5a9-11e4-95c4-0ab35ec26980.png)

PR to follow.

**Comment by bricesanchez** [comment]
#2918 should fix this bug, thanks @anitagraham :)
