### ISSUE TITLE
Deprecation: Use_route in refinery::testing

### ISSUE THREAD

**Issue by CJBrew** [refinery/refinerycms#2927]
Causes the following noise on running controller specs

```
DEPRECATION WARNING: Passing the `use_route` option in functional tests are deprecated. Support for this option in the `process` method (and the related `get`, `head`, `post`, `patch`, `put` and `delete` helpers) will be removed in the next version without replacement. Functional tests are essentially unit tests for controllers and they should not require knowledge to how the application's routes are configured. Instead, you should explicitly pass the appropiate params to the `process` method. Previously the engines guide also contained an incorrect example that recommended using this option to test an engine's controllers within the dummy application. That recommendation was incorrect and has since been corrected. Instead, you should override the `@routes` variable in the test case with `Foo::Engine.routes`. See the updated engines guide for details.
```

Seems to be declared in `testing/lib/refinery/testing/controller_macros/methods.rb`, but I've not tested what happens if you remove it.

**Comment by parndt** [comment]
We can get rid of these if we change [this file](https://github.com/refinery/refinerycms/blob/a0d8052d487a77678cdf9230759a6d417d5c6eca/testing/lib/refinery/testing/controller_macros/methods.rb) to this:

```ruby
module Refinery
  module Testing
    module ControllerMacros
      module Methods
        extend ActiveSupport::Concern

        included do
          routes { Refinery::Core::Engine.routes }
        end
      end
    end
  end
end
```

But then we get all of the crud dummy tests failing because their routes don't exist for some reason (because they're magic I guess)

So if we can have both of these things, then we can fix the deprecation warning.

**Comment by CJBrew** [comment]
@parndt see attached PR: the tests just needed routes adding as per the documentation:
http://www.relishapp.com/rspec/rspec-rails/v/3-2/docs/controller-specs/engine-routes-for-controllers
