### ISSUE TITLE
Add custom links in "page_dialogs/link_to"

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2930]
There could be fine to have an initializer with more options to set what engines will show there. E.g. I would like to have links of my blog posts there.

Any ideas how to refactor this 2 views (https://github.com/refinery/refinerycms/tree/master/pages/app/views/refinery/admin/pages_dialogs)?

Is it good idea or? What do you think? Tips how to begin? :)

**Comment by bricesanchez** [comment]
I think it could be good idea :smile:

**Comment by anitagraham** [comment]
Good idea.   
One option: Add it to the things a plugin can register. 
````ruby
plugin.offer_links = proc { whatever it takes}
````
You could do that now.

In the future you might maintain a separate register of "linkable objects".

Now, in `pages/app/views/refinery/admin/pages_dialogs/link_to.html.erb` there is a hard-coded list of things to link to:
page, url, email, file

You could generalise this:
* 'core refinery' will register pages, urls, emails and files
* plugin/extension can register their object which can be linked_to, along with finding and presentation ideas.

and `link_to`  will present a list of registered objects, etc etc.

Finally, decouple `link_to`  from pages and allow other containers to call a list of linkable objects.

**Comment by parndt** [comment]
This needs an overall goal + someone to own the feature

**Comment by parndt** [comment]
I'm closing this because nobody volunteered in 1.5 months
