### ISSUE TITLE
Bug - Images: SHA is changed, if I change uploaded image

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2931]
I uploaded image called "prokop.jpg" and I added it in my page content via WYM. But now I want to change this image without to have to changing content of page, I want only edit image and to change the source file... But the SHA is changed, if I change the source file, so there is 404 image on my page...

How to resolve? Any ideas?

**Comment by bricesanchez** [comment]
It's a missing feature.
It could be great to find a solution :)

**Comment by prokopsimek** [comment]
What about to substitute image url with something like {{IMG:5}} in HTML source code of a page and this would by substituted for an image url? (this example returns image with id == 5)

**Comment by anitagraham** [comment]
How did you do this? 
I just tried to duplicate it, and ended up with the original image still on my page.
To get the second image on the page I had to insert it.

**Comment by prokopsimek** [comment]
It's only idea, I don't know how to do it.

**Comment by anitagraham** [comment]
If you are going to start offering templating in the page you will end up having to offer a lot more than that!
(Useful things always grow)

**Comment by prokopsimek** [comment]
@anitagraham You don't understand me... Try this steps:
1) upload img (your first img)
2) add img into page part content (your second img)
3) edit your uploaded img
4) change source file of this img
5) SHA is changed, so your img in page part content returns err404

**Comment by anitagraham** [comment]
Simi, off to singing practise now. Will try when I get back.

Can you label the later steps so that I can tell which one is image 1 and which is image 2?
Thanks.

**Comment by bsodmike** [comment]
Guys, @parndt @anitagraham I did some code spelunking through the latest commit on `master` 29ab03669a0 and find that a rather old version of dragonfly's still the dependency of Refinery, v1 from 2013-11-24.  This version is so old it still has `protect_from_dos_attacks` as the option for enabling its SHA-based protection, rather than the newer `verify_urls`.

Of course, there's chatter of SHA related issues with version `1.0.7` (https://github.com/markevans/dragonfly/issues/387) but the latest version is `1.0.10`.  Any chance we could use the latest version?

A recent project of mine was based off the master branch, and for the time being I've had to kill the DOS protection in Dragonfly from causing a mess in production (the usual 'invalid SHA' provided message, even though a secret has been set).

These are from `master` 29ab03669a0
```
images/refinerycms-images.gemspec
22:  s.add_dependency 'dragonfly',               '~> 1.0.0'

resources/refinerycms-resources.gemspec
23:  s.add_dependency 'dragonfly',               '~> 1.0.0'
```

**Comment by parndt** [comment]
That dependency specification should allow `1.0.10` just fine?

Run `bundle update dragonfly`.

**Comment by bsodmike** [comment]
Hey @parndt I was suggesting changes were made to their specification in the master branch, let me know if you need a PR!

**Comment by brooks** [comment]
@bsosmike , how were you able to remove the DOS protection? We're having the same problem in a production app. Is there a configuration setting in refinery core config or do I need to fork refinery and patch the fork?

**Comment by bsodmike** [comment]
hey @brooks,

I added an initialiser to override both the Refinery Images and Resources modules - as they both use Dragonfly.  The upgrade from 1.0.7 to 1.0.10 Dragonfly didn't help the SHA issue, so I went with this

```ruby
require 'dragonfly'

Rails.application.config.before_initialize do

  module Refinery
    module Images
      module Dragonfly

        class << self
          def configure!
            # copy the method's code over from your version of Refinery
          end
        end

      end
    end
  end

  module Refinery
    module Resources
      module Dragonfly

        class << self
          def configure!
            # copy the method's code over from your version of Refinery
          end
        end

      end
    end
  end

end
```

Inside each `configure!` call, you need to set `verify_urls false`.  I feel this is somewhat better than adding a monkey patched dependency to your codebase.

**Comment by brooks** [comment]
Thanks @bsodmike. Much appreciated.

**Comment by anitagraham** [comment]
Refinery could offer `verify_urls` as a config option for any dragonfly plugin. An initializer would only have to set that to `false`.

**Comment by bsodmike** [comment]
@anitagraham +1

**Comment by bsodmike** [comment]
Pleasure @brooks

**Comment by parndt** [comment]
OK, so who is keen to write the patch?

**Comment by anitagraham** [comment]
I thought I had done that! Let me investigate

**Comment by anitagraham** [comment]
PR #3017. However this test fails:
````ruby
      context "when Dragonfly.verify_urls is false" do
        Refinery::Images.dragonfly_verify_urls = false
        it "returns a url without an SHA parameter" do
          expect(created_image.url).not_to match(/\?sha=[\da-fA-F]{16}\z/)
        end
      end
````
I think because you can't change a config value mid-stream, so to speak. 

The url returned has got an SHA parameter. Testing in an application did work though.

I was investigating how to get this to work about a month ago, but have been too busy to follow up.

**Comment by parndt** [comment]
When mocking config values, you might want to use RSpec's allow feature:

```ruby
context "when Dragonfly.verify_urls is false" do
  before { allow(Refinery::Images).to receive(:dragonfly_verify_urls).and_return(false) }
  it "returns a url without an SHA parameter" do
    expect(created_image.url).not_to match(/\?sha=[\da-fA-F]{16}\z/)
  end
end
```

**Comment by parndt** [comment]
@anitagraham hopefully my previous comment helps you?

**Comment by bsodmike** [comment]
@parndt +1 RSpec's stub/mocking also allows [use of `expect`](https://github.com/rspec/rspec-mocks); `allow` is technically a stub, whereas `expect` itself is an assertion, and would work just as well.  Cheers for the patch @anitagraham.

**Comment by bricesanchez** [comment]
Is it fixed ? @parndt and @anitagraham

**Comment by parndt** [comment]
@bricesanchez the commit f444811d59729a1e2609c49ed394f92af02b26c2 was merged which should mean this is fixed.

**Comment by parndt** [comment]
@bricesanchez though, the commit just gives you a config option, so I'm not sure if that qualifies as fixing the underlying issue.

**Comment by anitagraham** [comment]
That's what I was going to say.

**Comment by bsodmike** [comment]
Indeed, for now it seems best to disable SHA verification via the config option until it's fixed here & Refinery's dependency is updated as well https://github.com/markevans/dragonfly/issues/387#issuecomment-128141529

**Comment by simi** [comment]
Just to sumarize this: It is not bug in Refinery, but Dragonfly feature and it can be bypassed with new config in Refinery configuring Dragonfly to not use SHA in URL. Am I right and can we close this?

/cc @anitagraham @bsodmike @prokopsimek

**Comment by bsodmike** [comment]
@simi correct.  The change in f444811 allows by-passing the underlying issue in Dragonfly, at least until Refinery's dependency is upgraded once it's sorted in Dragonfly itself.  I've not had time to dig into this further, but I hope to do so soon (https://github.com/markevans/dragonfly/issues/387)

**Comment by bricesanchez** [comment]
"... at least until Refinery's dependency is upgraded...."

@bsodmike if you run bundle update, you will be able to use the latest version of dragonfly 1.0.10

**Comment by bsodmike** [comment]
As I recall the issue has yet to be fixed, even in the latest tagged
release of Dragonfly. Issue is not the use of the pessimistic version
constraint in Refinery. Sorry for the confusion!

On Wednesday, 19 August 2015, Brice Sanchez <notifications@github.com>
wrote:

> "... at least until Refinery's dependency is upgraded...."
>
> @bsodmike <https://github.com/bsodmike> if you run bundle update, you
> will be able to use the latest version of dragonfly 1.0.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/refinery/refinerycms/issues/2931#issuecomment-132713419>
> .
>


-- 
--
Mike's on the move!

**Comment by simi** [comment]
@bsodmike do you mean https://github.com/refinery/refinerycms/blob/master/resources/refinerycms-resources.gemspec#L23 and https://github.com/refinery/refinerycms/blob/master/images/refinerycms-images.gemspec#L22? Why we need to lock it to specific minimal version?

**Comment by bsodmike** [comment]
Oh right, my mistake.  I should have said

"The change in f444811 allows by-passing the underlying issue in Dragonfly, at least until ~~Refinery's dependency is upgraded once it's sorted in Dragonfly itself~~ a patched version is released.  Until such time, the config option is your friend."  @bricesanchez good catch mate, thanks for clarifying that!  Apologies for the confusion @simi

**Comment by simi** [comment]
@bsodmike as I said I think it is not bug, but it is feature of Dragonfly.
