### ISSUE TITLE
Breadcrumbs in refinerycms engines

### ISSUE THREAD

**Issue by codertux** [refinery/refinerycms#2932]
I'm using something like this to render breadcrumbs:
```
<div id="page-header">
  <div class="container">
    <h1><%# @page.title %><%= yield :body_content_title %></h1>
    <ul class="breadcrumbs">
      <li><%= link_to "Acasă", refinery.root_path %></li>
      <% @page.ancestors.collect do |p| %>
        <li><%= link_to p.title, p.url %> </li>
      <% end %>
      <li><%= @page.title %></li>
      <%=  %>
    </ul>
  </div>
</div>
```

There are two issues with this aproach:
1) I had to hardcode "Acasă" for the refinery.root_path since I wasn't sure how to get the root_path page's name.
2) Custom engines do not have a proper `@page` variable, it seems that a record in a custom engine inherits the `@page` of the refinery page where the engine is mounted.
 So instead of getting a breadcrumb like
```
Home / Engine / Record
```
I'm getting something like:
```
Home / Engine
```

Any ideas how to fix this? Is there some way to make my engine's records act like refinery subpages?

Thanks,
Andrei

**Comment by parndt** [comment]
> 1) I had to hardcode "Acasă" for the refinery.root_path since I wasn't sure how to get the root_path page's name.

```ruby
Refinery::Page.find_by(link_url: "/").title
```

**Comment by parndt** [comment]
My suggestion is to expose an instance variable like `@breadcrumb` in your controller and then in your template you can do:

```erb
<li><%= @breadcrumb.presence || @page.title %></li>
```

**Comment by bricesanchez** [comment]
Is there a way to publish this snippet of code in Refinery ? As a guide ? As a partial in core/app/views/refinery ? or something else ?

Displaying breadcrumb is a really good practice.

We should find a way to add engines records in sitemap too : 
https://github.com/refinery/refinerycms/blob/f0f43e973e5c9735a262156bb08e438c3ba53398/core/app/views/refinery/sitemap/index.xml.builder

**Comment by parndt** [comment]
Code that we don't use in the core shouldn't live in the core, so we'd have to use it somehow for it to be included.
