### ISSUE TITLE
New styling

### ISSUE THREAD

**Issue by chrise86** [refinery/refinerycms#2934]
Not really an issue, but didn't really know where else to put it, sorry...

Anyway, I'm working on a new interface for the back end, would you like me to put in a pull request when it's done?

![refinery-admin](https://cloud.githubusercontent.com/assets/616956/6761996/718a6c68-cf51-11e4-90bf-3197910b2666.png)

**Comment by parndt** [comment]
Wahoo! Yes, please! If you'd like to discuss anything there's also [the Gitter room](https://gitter.im/refinery/refinerycms)

**Comment by parndt** [comment]
cc @anitagraham who is also working on backend CSS

**Comment by chrise86** [comment]
Cool ok, thanks! :)

**Comment by anitagraham** [comment]
Hi Chris,
I have added font-awesome icons to replace the png icons. It's in this PR: #2920 . I am also looking at using zurb-foundation for the backend.

At the moment I am not making any decisions about colouring and layout.
I am using (mostly) the zurb-foundation default colours and keeping the current backend layout.

Your layout is very nice... and would be easy to implement (she says) using foundation. 

I was thinking last night that the search bar would be better out of the actions and above the main index.

Here is a screen shot of where I am up to...

![screen shot 2015-03-21 at 10 21 51 am](https://cloud.githubusercontent.com/assets/397118/6763372/2f0b515a-cfb4-11e4-8fd5-28258c194b42.png)

**Comment by chrise86** [comment]
Hi @anitagraham,

I've very close to finishing what I'm doing. When I do I'll push to Heroku so you can have a play with it :)

**Comment by parndt** [comment]
Will you also open a pull request for it?

**Comment by chrise86** [comment]
I will indeed :)

**Comment by bricesanchez** [comment]
@chrise86 any update ? :)

**Comment by anitagraham** [comment]
Also wondering - I have switched to focussing on the js objects in foundation (dialogs, sortable lists, etc) as your design is so well advanced.

**Comment by ofazomi** [comment]
Nice! Thanks @chrise86 and @anitagraham!

**Comment by parndt** [comment]
@chrise86 hey, how's this going?

**Comment by chrise86** [comment]
Sorry guys, been a bit preoccupied recently, but I am working on something big and will update you as soon as I can.

**Comment by parndt** [comment]
@chrise86 thanks! :smile:

**Comment by bricesanchez** [comment]
@chrise86 any news?

**Comment by chrise86** [comment]
@bricesanchez afraid not, I wasn't really happy with the results in the end. I'm looking at using [this](http://www.creative-tim.com/product/light-bootstrap-dashboard-pro) for my next project, but I'm not sure how the licensing would work...

**Comment by bricesanchez** [comment]
Ok, i'm closing the issue. Thanks!
