### ISSUE TITLE
Update RefineryCMS demo

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2938]
It would be fine to update DEMO app (http://demo.refinerycms.com/refinery) because of admin layout after refactor looks better!

**Comment by parndt** [comment]
You want http://edge-demo.refinerycms.com/ :)

**Comment by prokopsimek** [comment]
https://github.com/refinery/refinerycms/blame/master/readme.md#L50

**Comment by simi** [comment]
@prokopsimek it is not done yet. We need to migrate it from https://github.com/simi/refinerycms/commit/42288ed837bd226777e9c7423e45ddcae60662ff to origin.

**Comment by prokopsimek** [comment]
ok
