### ISSUE TITLE
Page menu generator

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#2952]
I think it could be great to have a page menu generator, and you what do you think ?

**Comment by simi** [comment]
Can you describe this?

**Comment by bricesanchez** [comment]
Yep, in fact i would like convert this guide : 
http://refinerycms.com/guides/menu-presenter

to a script like : 
```shell
rails generate refinery:menu footer_menu
rake db:migrate
```

**Comment by parndt** [comment]
Is it really difficult to write one currently?

**Comment by bricesanchez** [comment]
My goal is not to remove this guide but after creating a menu presenter generator i would like to update this guide :)

It´s because at this time, i copy/paste every menus configs between my projects.

**Comment by bricesanchez** [comment]
In order to keep refinerycms-core lightweight, i'm starting by updating the guide of menu presenter : #2953
