### ISSUE TITLE
How to configure CDN for serving Refinery images properly?

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#2955]
I have set:

in "/config/environments/production.rb"
```ruby
  config.action_controller.asset_host = "cdn.example.cz"
```
to delivery CSS & JS from CDN.

How to set "refinerycms-images" gem for serving images from CDN too?
I tried to set:
in "/config/initializers/refinery/images.rb"
```ruby
  config.dragonfly_url_host = Rails.application.config.action_controller.asset_host
```
but there is URL something like: 
```
http://cdn.example.cz/images/cdn.example.cz/system/images/W1siZiIsIjIwMTUvMDQvMDMvM21oZG05Y21jb19iYW5uZXJ0eXJvbC5qcGciXSxbInAiLCJ0aHVtYiIsIjkwMHgxNDUjYyJdXQ/bannertyrol.jpg?sha=f942dbcee2588e1c
```

How to set url format?
```
  # config.dragonfly_url_format = "/system/images/:job/:basename.:ext"
```
Should I to change it or not for my CDN?

**Comment by parndt** [comment]
That is the correct config setting to use, Refinery will convert it to `url_host` when it invokes Dragonfly.

Here are all the docs from Dragonfly about using CDN: http://markevans.github.io/dragonfly/cache/#using-a-cdn
