### ISSUE TITLE
New icons breaks extensions visuals like Blog and Copywriting

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#2963]
Hi all !

New icons are but they breaks extensions like refinerycms-blog and refinerycms-copywriting.

Any idea to fix it quickly ?

![refinery-icons-blog](https://cloud.githubusercontent.com/assets/1678530/7397168/a765011c-ee74-11e4-8467-a0d474d1136a.png)

![refinery-icons-copywriting](https://cloud.githubusercontent.com/assets/1678530/7397135/67f4f82a-ee74-11e4-99bc-d6d3e0c56c48.png)

@anitagraham

**Comment by simi** [comment]
fixes per engines will be needed

**Comment by mhtremblay** [comment]
There a pull request in blog extension for that: https://github.com/refinery/refinerycms-blog/pull/432
