### ISSUE TITLE
View Generated by Reginery:Engine missing helper method

### ISSUE THREAD

**Issue by timstephenson** [refinery/refinerycms#2968]
Hi

I'm using Refinery 3.0.0 with Rails 4.1.8.

After generating an engine as follows:

```
rails generate refinery:engine project title:string  thumbnail:image poster:image sub_title:string description:text lift:string
```

I am able to go to the new Projects tab in the admin section and create a new project. However, when it redirects to the index page, it appears a helper method is being called: Undefined method icon. 

```
NoMethodError in Refinery::Projects::Admin::Projects#index
Showing /Users/timstephenson/Projects/cl/wearelift/vendor/extensions/projects/app/views/refinery/projects/admin/projects/_project.html.erb where line #8 raised:

undefined method `icon' for #<#<Class:0x007fa032a63748>:0x007fa032a52858>
```

I can certainly update the view that was generated to fix the problem. Should I look in an older version of Refinery to determine what the icon helper was doing? For now I am just rendering a string, but would like to do it right for forward compatibility.

Thanks in advance.

**Comment by parndt** [comment]
cc @anitagraham

**Comment by anitagraham** [comment]
Looking now.

**Comment by anitagraham** [comment]
PR #2969
