### ISSUE TITLE
Pages admin throws ActiveRecord::StatementInvalid when using SQL Server

### ISSUE THREAD

**Issue by BrandonJoyce356** [refinery/refinerycms#2980]
Seems to be caused by the 'lft' column being included in the order by twice.  Sql Server doesn't like this.  I can fix it by just removing [this line of code](https://github.com/refinery/refinerycms/blob/master/pages/app/controllers/refinery/admin/pages_controller.rb#L7)  Is that sort necessary here?

```
ActionView::Template::Error (TinyTds::Error: A column has been specified more than once in the 
order by list. Columns in the order by list must be unique.: EXEC sp_executesql N'SELECT [refin
ery_pages].* FROM [refinery_pages] WHERE [refinery_pages].[parent_id] IS NULL ORDER BY lft ASC,
 [refinery_pages].[lft] ASC'):
    1: <ul id='sortable_list'>
    2:   <%= render :partial => 'page', :collection => @pages.roots  %>
    3: </ul>
    4: <%= render '/refinery/admin/sortable_list', :continue_reordering => !!local_assigns[:con
tinue_reordering] %>
```

**Comment by parndt** [comment]
What else is specifying it?

**Comment by BrandonJoyce356** [comment]
From what I can tell, I think it's this from the nested set library: https://github.com/collectiveidea/awesome_nested_set/blob/3838ceeb1ec2e3e9ac60b6707a981d6b37bb7cab/lib/awesome_nested_set/model.rb#L82

**Comment by parndt** [comment]
Ok well if you'd like to look at opening a pull request for that then we can see if it breaks anything else? :)

**Comment by BrandonJoyce356** [comment]
Sure thing.

**Comment by parndt** [comment]
Thank you!!
