### ISSUE TITLE
Entire back end UI is broken

### ISSUE THREAD

**Issue by nickmjones** [refinery/refinerycms#2986]
![screen shot 2015-05-26 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/563451/7817588/f155aeea-03a3-11e5-9c5e-e8f917539117.png)

I've just updated my bundle, and suddenly the entire backed UI is broken. `refinery.css` is asking for files that are obviously not there. I've pulled the missing files from the repository, but they don't fix the issue. The UI is still unusable. Can anyone tell me how to use a stable version of Refinery until this gets resolved? I can't ship a broken UI to our client.

**Comment by nickmjones** [comment]
A little more info about this issue. Removing the folder `app/assets/stylesheets/refinery` fixes this issue, but it begs the question of how it got there in the first place?

**Comment by anitagraham** [comment]
Nick, what did you update from and to?  
The current master is for Refinery 3.0 and there are changes in several areas. 

One of these areas is stylesheets, which are now split into a main stylesheet (refinery.scss) and partials (_layout.scss, etc).

**Comment by parndt** [comment]
Ah, so an override was causing the issue..
