### ISSUE TITLE
Upgrade guide from RefineryCMS 2.x to 3.0

### ISSUE THREAD

**Issue by deepj** [refinery/refinerycms#2990]
I'm not much an active user of RefineryCMS, but I've been maintaining  only one website of father's company based on RefineryCMS.

I've tried to upgrade RefineryCMS master but without success. Unfortunately, I have limited time to go deep and try to figure a way out myself. There have been made several changes in data structure in RefineryCMS 3.0 against 2.1.

I think more users of RefineryCMS would appreciate something like a upgrade guide.

**Comment by parndt** [comment]
Yes, I agree.  Can you tell us what made your attempt unsuccessful? This would help us to fix common problems.

**Comment by anitagraham** [comment]
I wrote [notes](https://gist.github.com/anitagraham/a6d1b14bd10b5737493e) for my upgrade from 2.1 to 3.0.
