### ISSUE TITLE
refinerycms-products

### ISSUE THREAD

**Issue by Andrew22222** [refinery/refinerycms#2991]
Hi, how install refinerycms-products i'm not understand. This extension not  installed, please say me how installed this  extension

**Comment by parndt** [comment]
Hi! You can follow their instructions here: https://github.com/julesce/refinerycms-products#requirements

**Comment by Andrew22222** [comment]
Thanks, I will try

2015-06-02 12:24 GMT+03:00 Philip Arndt <notifications@github.com>:
