### ISSUE TITLE
Flash message duplicated in dialog

### ISSUE THREAD

**Issue by anitagraham** [refinery/refinerycms#2995]
1.  Edit page content and `save and continue`
A flash message "`page_name` was successfully updated" appears.
2. Without closing the flash container select "Add image" or "Add link".
A dialog opens with the same flash message at the top. The flash container obscures part of the dialog content.
![flash message in dialog box](https://cloud.githubusercontent.com/assets/397118/8105638/695d2f28-106d-11e5-8ddb-02f0a5c53265.png)

Possibly the flash containers need ids to distinguish one from the other. 
If the flash container is visible it shouldn't obscure other content.

I will look in more detail when time permits.

**Comment by parndt** [comment]
Perhaps dialogues shouldn't show flash messages at all?

**Comment by bricesanchez** [comment]
:+1: @parndt
