### ISSUE TITLE
Minor GUI bug when inserting image incase no image is selected...

### ISSUE THREAD

**Issue by KshitizGIT** [refinery/refinerycms#2996]
Minor bug in master branch.
'fa fa-circle-o-notch fa-spin' class persists incase 'Insert' is clicked without any image being selected..
Either a image should be selected by default or 'fa fa-circle-o-notch fa-spin' should be destroyed when insert is attempted without any selected image

![minor bug](https://cloud.githubusercontent.com/assets/8330582/8143691/8dc18032-11d8-11e5-8713-2b9938953ffe.png)

**Comment by anitagraham** [comment]
I can make it so the spinner only appears once, but I can't make it disappear once it appears.
I don't think I can tell when alert box with "Please select an image" appears or is acknowledged.
Someone who knows more about wymeditor might be able to change how that box is triggered.

In the meantime I will see ensure that the spinners aren't multiplying... :beetle: is the closest I can get to a spider or web.

**Comment by KshitizGIT** [comment]
Thank you..  As I am new to refinerycms and rails for that matter, I would love to contribute any was as I can   :+1:
