### ISSUE TITLE
undefined method `display_site_bar? exception : Only on production

### ISSUE THREAD

**Issue by nuno84** [refinery/refinerycms#3001]
Dear all,
I have the refinery working well on my local machine.
So, I tried to deploy to production.
I can create a page, but when I try to see the page live, it throws an exception:

```
ActionView::Template::Error (undefined method `display_site_bar?' for #<#<Class:0xb5d88780>:0xbb725ab8>):
    1: <% if display_site_bar? %>
    2:   <% unless admin? # all required JS included by backend. %>
    3:     <% content_for :stylesheets, stylesheet_link_tag('refinery/site_bar') unless !!local_assigns[:exclude_css] %>
    4:     <%= yield(:stylesheets) unless local_assigns[:head] || local_assigns[:exclude_css] %>
  /home/farmacostore/farmacoWebStore/shared/bundle/ruby/2.1.0/bundler/gems/refinerycms-c5e7a052c867/core/app/views/refinery/_site_bar.html.erb:1:in `_c4f3de59155aea98cdbd4502307195f8'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  deface (1.0.1) lib/deface/action_view_extensions.rb:41:in `render'
```

I don't know what is happening! It works fine on my machine.
My gemfile is:

```
#Refinery cms
gem 'refinerycms',         github: 'refinery/refinerycms', branch: 'auth-for-real-yo-tmp'
gem 'zilch-authorisation', github: 'parndt/zilch-authorisation', branch: 'master'
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']
gem 'refinerycms-wymeditor',   github: 'parndt/refinerycms-wymeditor',        branch: 'master'#, ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-inquiries',   github: 'refinery/refinerycms-inquiries',       branch: 'master'
gem 'refinerycms-settings',    github: 'refinery/refinerycms-settings',        branch: 'master'
gem 'refinerycms-search',      github: 'refinery/refinerycms-search',          branch: 'master'
gem 'refinerycms-image_slideshows', github: 'bisscomm/refinerycms-image-slideshows', branch: '3-0-stable'
gem 'refinerycms-news',        github: 'refinery/refinerycms-news',            branch: 'master'
gem 'refinerycms-retailers',   github: 'bisscomm/refinerycms-retailers',       branch: '3-0-stable'
```
Am I missing some gem? It doesn't make much sense since it works on my end.
Thank you for your help,
Best regards
Nuno

**Comment by ghoppe** [comment]
Where did you get that template? As far as I know, `display_site_bar?` isn't a method refinery uses. Did you copy the template from some other project which defined it?

**Comment by nuno84** [comment]
I am using the spree integration branch: 
https://github.com/refinery/refinerycms/tree/auth-for-real-yo-tmp

It is defined here:
https://github.com/refinery/refinerycms/blob/auth-for-real-yo-tmp/core/app/helpers/refinery/site_bar_helper.rb

Do you have any idea? Is it a bug?
Thank you

**Comment by bricesanchez** [comment]
As i remember, if you set eager load option to false in production.rb, this error is hotfixed

**Comment by nuno84** [comment]
Brice,
As you suggested, I set config.eager_load = false in config/environments/production.rb and it worked!!
Thank you so much :D

**Comment by parndt** [comment]
Hmm, that's a strange solution.. Ideally we should be able to set that to true.

**Comment by bricesanchez** [comment]
@parndt Yes, i prefer to say "hotfix" instead of "solution", i don't know what cause this bug. It could be great to find a clean solution.
