### ISSUE TITLE
Dragonfly version conflict for 2.1.5 when using with AS3

### ISSUE THREAD

**Issue by khacanh** [refinery/refinerycms#3002]
```
In Gemfile:
    refinerycms (~> 2.1.5) ruby depends on
      refinerycms-resources (= 2.1.5) ruby depends on
        dragonfly (~> 0.9.12) ruby

    refinerycms (~> 2.1.5) ruby depends on
      refinerycms-images (= 2.1.5) ruby depends on
        dragonfly (~> 0.9.14) ruby

    dragonfly-s3_data_store (>= 0) ruby depends on
      dragonfly (~> 1.0) ruby
```

Should I use edge `3.0.0` which supports `dragonfly 1.0` or should I fork and fix dependency for `2.1.5`. This is quite a common configuration (refinerycms and AS3) yet I see any complaint. Or did I just do something wrong?

Thanks

**Comment by bricesanchez** [comment]
@khacanh, if it's a new project, you should use edge `3.0.0`, it's pretty stable.

**Comment by khacanh** [comment]
It's a legacy project, but I'm going to give `3.0.0` a try anw. Thanks @bricesanchez
