### ISSUE TITLE
Full-Page Cache with NGINX 

### ISSUE THREAD

**Issue by darmenise** [refinery/refinerycms#3006]
In the guide there is an [article about Full-Page Cache with Apache](https://github.com/refinery/refinerycms/blob/master/doc/guides/7%20-%20Hosting%20and%20Deployment/3%20-%20Full-Page%20Cache%20with%20Apache.textile). What about Nginx? Does anybody already know how to configure it with confidence please?

**Comment by parndt** [comment]
Please search for this or post this to the [user group](https://groups.google.com/group/refinery-cms/) :smile: thanks!
