### ISSUE TITLE
admin search not working on refinery engines.

### ISSUE THREAD

**Issue by mlinfoot** [refinery/refinerycms#3012]
RefineryCMS 3.0.0, Rails 4.2.3

Ran into a problem on the backend -- searching pages (for example) from the admin ui works as expected, but throws an error when trying to search in an engine. The problem can be reproduced by:

    rails new myapp -m http://refinerycms.com/t/edge
    cd myapp
    rails generate refinery:engine sample title:string
    <bundle, generate, migrate, and seed>
    rails server

Switch to the backend, add a few samples, and try to search. 

The error is:

    undefined method `with_query' for #<Refinery::Samples::Sample::ActiveRecord_Relation:0x007f94e471eb40>
    Extracted source (around line #136):
    134        arel.public_send(method, *args, &block)
    135      else
    136        super
    137      end
    138    end
    139  end

**Comment by prokopsimek** [comment]
Error too...

Model:
```ruby
      acts_as_indexed :fields => [:title]
```

Controller is default.

Error:
```
ArgumentError at /admin/campaigns
wrong number of arguments (1 for 0)
```

in:
```
Refinery::Campaigns::Admin::CampaignsController#search_all_campaigns
(eval), line 150
```

**Comment by mlinfoot** [comment]
I found the answer to this and for my case, it's working properly now. I discovered this comment line in a newly created model:
      # To enable admin searching, add acts_as_indexed on searchable fields, for example:
      #
      # acts_as_indexed :fields => [:title]

When I uncomment  "acts_as_indexed :fields => [:title]", searching in the admin ui works as expected.

Sorry for the confusion.

**Comment by prokopsimek** [comment]
My error is still if this line is uncommented...

**Comment by parndt** [comment]
@prokopsimek can you give us a sample application with this problem please?
