### ISSUE TITLE
Cannot expand/collapse child pages in the admin Pages

### ISSUE THREAD

**Issue by mlinfoot** [refinery/refinerycms#3025]
In the admin ui, on the Pages tab, a folder icon appears next to pages with children. Clicking on the folder icon should expand/collapse the page's children, but it does not have any effect. 

Setting the value of config.auto_expand_admin_tree to be false shows the tree collapsed, and a branch can be opened by clicking on the folder icon, but once opened it can't be closed. 

Another, minor, thing is the tooltip that appears when the mouse is hovered over a folder icon says "i18n: Expand Collapse" -- missing a translation?

Reproduced with a clean fresh install.

**Comment by anitagraham** [comment]
OK...found both of those.
Will get a PR going.

**Comment by parndt** [comment]
Fixed by #3027
