### ISSUE TITLE
Testing multiple extensions with rspec

### ISSUE THREAD

**Issue by AdeIa** [refinery/refinerycms#3028]
Hi,

I'm starting with refinery and I would like to ask you how to test my application's extensions with one command running from the root folder of the application.

 E.g. I have 10 extensions, I want to write tests in extension's spec folder but I want to run all these tests with one command from the root of the application. 

In your guide I found only instructions for testing extension from its folder (/vendor/extensions/events), but I don't want e.g. ten times run these commands in extension folder.

Is there any way how to do it more efficient?

**Comment by anitagraham** [comment]
Refinery itself does this using a rake task.

**Comment by parndt** [comment]
Normally I run this command from my application's directory:

    bundle exec rspec ./spec ./vendor/extensions/**/spec
