### ISSUE TITLE
WYM on FE

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms#3029]
Hi, I want to init wymeditor on FE, how I can to do it? What JQ fction to call? How to init it with another options than in admin?

Thx

**Comment by parndt** [comment]
wymeditor support was extracted to a separate extension at [parndt/refinerycms-wymeditor](https://github.com/parndt/refinerycms-wymeditor)

Everything we initialise it with is in the [boot_wym](https://github.com/parndt/refinerycms-wymeditor/blob/master/app/assets/javascripts/refinery/boot_wym.js.erb) file
