### ISSUE TITLE
Bundler could not find compatible versions for gem "actionpack" (rails 4.1.8)

### ISSUE THREAD

**Issue by sabre1409** [refinery/refinerycms#3032]
Hi,

I am new to Rails and trying to install Refinery CMS but bundle can't find compatible versions for gem "actionpack" (Added the full error below). I would really appreciate some help, thanks in advance! 

I am using RVM 1.26.11, rails 4.1.8 and tried using ruby 2.0.0 and 2.2.2 
I followed the instructions at http://www.refinerycms.com/download. During the initial installation it told me to install execjs, so I installed execjs 2.5.2. Might this be part of the problem?

The generated gemfile looks like:
source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'

gem 'quiet_assets', group: :development
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-authentication-devise', '~> 1.0'

The full error:
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails (= 4.1.8) ruby depends on
      railties (= 4.1.8) ruby depends on
        actionpack (= 4.1.8) ruby

    rails (= 4.1.8) ruby depends on
      railties (= 4.1.8) ruby depends on
        actionpack (= 4.1.8) ruby

    rails (= 4.1.8) ruby depends on
      railties (= 4.1.8) ruby depends on
        actionpack (= 4.1.8) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          actionpack (< 5.0, >= 4.1.5) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          refinerycms-i18n (~> 3.0.0) ruby depends on
            routing-filter (>= 0.4.0) ruby depends on
              actionpack (~> 4.2) ruby
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    rails (= 4.1.8) ruby depends on
      activerecord (= 4.1.8) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          activerecord (< 5.0, >= 4.1.5) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        friendly_id (~> 5.1.0) ruby depends on
          activerecord (>= 4.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          awesome_nested_set (~> 3.0.0) ruby depends on
            activerecord (< 5, >= 4.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-resources (= 3.0.0) ruby depends on
        globalize (< 5.2, >= 4.0.0) ruby depends on
          activerecord (< 4.3, >= 4.2.0) ruby
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (= 4.1.8) ruby depends on
      railties (= 4.1.8) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          railties (< 5.0, >= 4.1.5) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        seo_meta (~> 2.0.0.rc.1) ruby depends on
          railties (>= 3.0.0) ruby

    coffee-rails (~> 4.0.0) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          refinerycms-i18n (~> 3.0.0) ruby depends on
            rails-i18n (~> 4.0.1) ruby depends on
              railties (~> 4.0) ruby

    coffee-rails (~> 4.0.0) ruby depends on
      railties (< 5.0, >= 4.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          jquery-ui-rails (~> 5.0.0) ruby depends on
            railties (>= 3.2.16) ruby

    refinerycms-acts-as-indexed (>= 2.0.0, ~> 2.0) ruby depends on
      decorators (~> 2.0.0) ruby depends on
        railties (< 5.0.0, >= 4.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        speakingurl-rails (~> 1.1.2) ruby depends on
          railties (>= 3.1) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-pages (= 3.0.0) ruby depends on
        refinerycms-core (= 3.0.0) ruby depends on
          jquery-rails (>= 2.3.0) ruby depends on
            railties (< 5.0, >= 4.2.0.beta) ruby
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    rails (= 4.1.8) ruby depends on
      actionmailer (= 4.1.8) ruby

    refinerycms-authentication-devise (~> 1.0) ruby depends on
      actionmailer (>= 4.2.0, ~> 4.2) ruby

**Comment by bricesanchez** [comment]
Could you update to `gem 'rails', '~> 4.2.3'` ?

**Comment by sabre1409** [comment]
That did the trick. Thanks!

**Comment by bricesanchez** [comment]
@parndt Should we recommand rails 4.2 + only ?

**Comment by parndt** [comment]
@bricesanchez looks like we support 4.1.5 and above though: https://github.com/refinery/refinerycms/blob/master/core/refinerycms-core.gemspec#L5 and it's jquery-rails forcing us up.

I'm fine with supporting Rails version 4.2.3+ but we need to specify this in the core gemspec as well as change the description for the gem in this file: https://github.com/refinery/refinerycms/blob/master/refinerycms.gemspec#L10

@bricesanchez can you handle that please?

**Comment by bricesanchez** [comment]
@parndt done : https://github.com/refinery/refinerycms/pull/3034

**Comment by parndt** [comment]
Thanks!

**Comment by FabricioFernandes** [comment]
It works fine with **gem 'rails', '~> 4.2.3'**
Thanks, bricesanchez.

**Comment by BalveerCSL** [comment]
I am using RVM 2.3.0, rails 4.1.5 and tried using ruby 2.3.0 and 2.5.2
I followed the instructions at http://www.rvm.io. During the initial installation it told me to install execjs, so I installed execjs 2.5.2. Might this be part of the problem?
source 'https://rubygems.org'
gem "zendesk_api"
gem 'galetahub-simple_captcha', :require => 'simple_captcha'
gem "rake"
gem 'rails', '4.1.5'
gem 'devise'
gem "friendly_id"
gem "exception_notification", '4.0.0'
gem 'kaminari'
gem 'swfobject-rails'
gem 'ckeditor_rails'
gem 'activemerchant'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'sendgrid'
gem 'mysql2','~> 0.3.15'
gem 'json'
gem "paperclip", '3.4.2'
gem 'whenever', :require => false
#gem 'omniauth-facebook', '>=0.2.6'
gem "rmagick", "~> 2.13.2", :require=>'RMagick'
gem "omniauth", "~> 1.1.1"
gem "omniauth-facebook", "1.4.0"
gem 'oauth2'
gem 'nokogiri', "1.5.10"
gem 'passenger'
gem 'fancybox2-rails', '~> 0.2.8'
gem 'jquery-ui-rails' , '4.1.1'

 gem "net-ssh", "~> 2.7.0"
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '4.0.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :production do
 gem 'therubyracer'
 gem 'execjs'
end


gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'
# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano', '~> 2.15.5'

# To use debugger
# gem 'ruby-debug'
#gem 'clockwork', :git => "https://github.com/tomykaira/clockwork.git"

The full error 

Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.......
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    exception_notification (= 4.0.0) was resolved to 4.0.0, which depends on
      actionmailer (>= 3.0.4)

    rails (= 4.1.5) was resolved to 4.1.5, which depends on
      actionmailer (= 4.1.5)

Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    paperclip (= 3.4.2) was resolved to 3.4.2, which depends on
      activemodel (>= 3.0.0)

    rails (= 4.1.5) was resolved to 4.1.5, which depends on
      activemodel (= 4.1.5)

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    friendly_id was resolved to 5.2.4, which depends on
      activerecord (>= 4.0.0)

    paperclip (= 3.4.2) was resolved to 3.4.2, which depends on
      activerecord (>= 3.0.0)

    rails (= 4.1.5) was resolved to 4.1.5, which depends on
      activerecord (= 4.1.5)

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    activemerchant was resolved to 1.78.0, which depends on
      activesupport (< 6.x, >= 3.2.14)

    exception_notification (= 4.0.0) was resolved to 4.0.0, which depends on
      activesupport (>= 3.0.4)

    kaminari was resolved to 1.1.1, which depends on
      activesupport (>= 4.1.0)

    paperclip (= 3.4.2) was resolved to 3.4.2, which depends on
      activesupport (>= 3.0.0)

    rails (= 4.1.5) was resolved to 4.1.5, which depends on
      activesupport (= 4.1.5)

Bundler could not find compatible versions for gem "net-ssh":
  In Gemfile:
    net-ssh (~> 2.7.0)

    capistrano (~> 2.15.5) was resolved to 2.15.9, which depends on
      net-ssh (>= 2.0.14)

Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    nokogiri (= 1.5.10)

    activemerchant was resolved to 1.78.0, which depends on
      nokogiri (~> 1.4)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.1.5)

    swfobject-rails was resolved to 2.0, which depends on
      rails (>= 3.0)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (= 4.1.5) was resolved to 4.1.5, which depends on
      railties (= 4.1.5)

    sass-rails (~> 3.2.3) was resolved to 3.2.3, which depends on
      railties (~> 3.2.0.beta)

**Comment by BalveerCSL** [comment]
any solution

**Comment by bricesanchez** [comment]
@BalveerCSL Refinery 3.x is compatible with Refinery 4.2.x. You should update your Rails version.

**Comment by bournsh** [comment]
@bricesanchez , I am getting a command line error with the 
`gem 'rails' '~> 4.2.3'`
Error: While executing gem .. (Gem::CommandLineError)
then I tried with `gem install rails`
outcome:Done installation successfully.
But, trying the same `bundle update`
Error: Bundler could not find compatible version for gem "actionpack"
                                                                                             "capistarno"
                                                                                             "i18n"
                                                                                              "saas"

**Comment by bricesanchez** [comment]
Hi @bournsh, you should lock some gems in your Gemfile

**Comment by jimmythakkar-dev** [comment]
Did you get any solution @bournsh ?

**Comment by TorvaldsDB** [comment]
![image](https://user-images.githubusercontent.com/12232166/76843415-b75d5c00-6876-11ea-9450-1e7e756e3df4.png)
I have fixed it almost the whole day.

**Comment by parndt** [comment]
@TorvaldsDB Looks like `wulin_audit` is holding you back to `activemodel ~> 3.x` through the mongoid version, but rails wants `actionpack = 5.20`
These are incompatible with `activemodel ~> 3.x` so you'll need to address/update `wulin_audit` (which isn't a public gem so I can't help)

**Comment by deadstar1** [comment]
is this error related here:
```
Bundler could not find compatible versions for gem "actionmailer":
  In Gemfile:
    rails (~> 6.0.3, >= 6.0.3.2) was resolved to 6.0.3.2, which depends on
      actionmailer (= 6.0.3.2)

    refinerycms-authentication-devise (~> 2.0) was resolved to 2.0.0, which depends on
      actionmailer (< 5.2, >= 5.0.0)
```

**Comment by SebSwan** [comment]
@pwnedDesal Did you find a fix to your problem, i have the same when i do `rails new website -m https://www.refinerycms.com/t/4.0.0`  
Did you find an alternative to refinerycms ? Thanks

**Comment by Apra235** [comment]
Hi @SebSwan   i am new to rails and having same issuues, any solution?
undler could not find compatible versions for gem "actionmailer":
  In Gemfile:
rails (~> 7.0.2, >= 7.0.2.3) x86_64-linux was resolved to 7.0.2.3, which
depends on
      actionmailer (= 7.0.2.3) x86_64-linux

refinerycms-authentication-devise (~> 2.0) x86_64-linux was resolved to
2.0.0, which depends on
      actionmailer (< 5.2, >= 5.0.0)

**Comment by parndt** [comment]
@Apra235 the version of [refinerycms-authentication-devise](https://github.com/refinery/refinerycms-authentication-devise) you're trying to use is only compatible with Rails 5.x; it's compatible with Rails 6.x if you use it from GitHub (apparently we haven't released a gem yet!) but isn't compatible with Rails 7.x (refinerycms isn't yet) so you'll have problems if you try to use Rails 7.

**Comment by SebSwan** [comment]
It seems this gems is not maintained anymore, i've just change the approach of my problem and make pages myself. Rails suck for CMS.

**Comment by parndt** [comment]
@SebSwan it is maintained but the maintainers (hi 👋) have far less time than they used to. We can't rush out to support every release of Rails immediately like we once were able to. Open source projects, given the lack of sponsorship/funding which is available to most closed source projects, rely on a lot of time given freely .
