### ISSUE TITLE
Could not find table 'refinery_settings' after adding Blog

### ISSUE THREAD

**Issue by slavajacobson** [refinery/refinerycms#3042]
Using master branches for refinerycms and the blog.

After adding the blog gem and running bundle, it says to run
 "rake acts_as_taggable_on_engine:install:migrations"

But when I run it, i get: 

"Don't know how to build task 'acts_as_taggable_on_engine:install:migrations'"

So I just ran rake db:migrate and rake db:seed and when I try to access Blog in the Admin section, I am getting "Could not find table 'refinery_settings'"

**Comment by simi** [comment]
Do you have refinerycms [settings](https://github.com/refinery/refinerycms-settings#installation) properly installed?

**Comment by slavajacobson** [comment]
I've never included it in the Gemfile, I am guessing it's included in the Blog?

**Comment by simi** [comment]
Yup, it is dependency of Blog, but you need to install it. We should write that into Blog readme. Can you handle that?

**Comment by parndt** [comment]
I've gotta close this - but can you add this to the [blog extension issues tracker](https://github.com/refinery/refinerycms-blog/issues/)?
