### ISSUE TITLE
"rails generate refinery:form ..." creates invalid code

### ISSUE THREAD

**Issue by mlinfoot** [refinery/refinerycms#3045]
Rails 4.2.3, latest Refinery 3.0 from master. 

When using `rails generate refinery:form contact_form` to create a contact form, the code produced has 3 errors that need correcting:

1. In the front-end, visiting the form page gives `undefined method 'required_label' for #<ActionView::Helpers::FormBuilder:0x007f44a96685b0>`
In file: ../views/../contact_forms/new.html.erb
Change: `<%= f.required_label :name %>`
To: `<%= f.label :name  %>`

2. In the front-end submit a form gives: `Validation failed: Title can't be blank`
(due to an error in thank_you page slug)
In Pages>Contact Forms>Thank You>Toggle advanced options
Change: `/contact_forms/new/thank_you`
To: `/contact_forms/thank_you`

3. In the back-end, Contact Forms>Update who gets notified gives: `undefined local variable or method 'users_manager' for ...`
In file: ../models/../contact_forms/setting.rb
Change: `(users_manager.primary_user.try(:email)).to_s)`
To: `(Refinery::Authentication::Devise::User.first.try(:email)).to_s)` or something else that makes sense.

**Comment by simi** [comment]
great catch, we need to cover **all** generators with integration tests

**Comment by parndt** [comment]
Please review #3009 which exists for this reason

**Comment by bricesanchez** [comment]
@mlinfoot is it ok for you?

**Comment by mlinfoot** [comment]
@bricesanchez Yes, fine with me, as long as it's okay with you. I created a custom form generator for my needs so this really doesn't affect me any more.

**Comment by bricesanchez** [comment]
@parndt has covered those bugs here : https://github.com/refinery/refinerycms-forms/commits/master :)
