### ISSUE TITLE
Does it Refinery supports taxonomies?

### ISSUE THREAD

**Issue by diaspar** [refinery/refinerycms#3048]
Does it refinery supports taxonomies like drupal?

https://www.drupal.org/documentation/modules/taxonomy

How challenging could it be to roll a taxonomy system inside refinery?

Is there any other way on refinery to group content?

What about using something like this https://github.com/mbleigh/acts-as-taggable-on and attach it to articles? could that be done?

Not sure if this is the right place to ask these questions. Please confirm.

**Comment by bricesanchez** [comment]
There is many way to group content on refinery, where do want taxonomies ? Why ?

Pages could be nested, blog posts could be categorized, every record type could be created inside an extension.

**Comment by parndt** [comment]
Since you asked.. it'd be best to ask questions in [Gitter](https://gitter.im/refinery/refinerycms) or [the user group](https://groups.google.com/group/refinery-cms/) :smile:
