### ISSUE TITLE
The selector ".fa-plus-circle" was not found.

### ISSUE THREAD

**Issue by GCorbel** [refinery/refinerycms#3050]
Hello,

When I go on the admin page, I have this issue : 

    ActionView::Template::Error (".add_icon" failed to @extend ".fa-plus-circle".
    The selector ".fa-plus-circle" was not found.
    Use "@extend .fa-plus-circle !optional" if the extend should be able to fail.
    ):
        4:   <%= yield :meta %>
        5:   <title><%= Refinery::Core.site_name -%> - Refinery</title>
        6:   <%= csrf_meta_tags %>
        7:   <%= stylesheet_link_tag 'refinery/refinery' %>
        8:   <% visual_editor_stylesheets.each do |css| %>
        9:     <%= stylesheet_link_tag css.path, css.options %>
       10:   <% end %>

This is a fresh install of refinery on the master branch.

It seems to be related to sass and font-awesome. What can I do?

**Comment by anitagraham** [comment]
Have you done a `bundle update`?

**Comment by GCorbel** [comment]
I did it it does not work.

This is my Gemfile : 

    source 'https://rubygems.org'


    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.3'
    # Use sqlite3 as the database for Active Record
    group :development, :test do
      gem 'sqlite3'
    end
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    gem 'therubyracer', platforms: :ruby

    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0', group: :doc

    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'

    # Use Unicorn as the app server
    # gem 'unicorn'

    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development

    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'

      # Access an IRB console on exception pages or by using <%= console %> in views
      gem 'web-console', '~> 2.0'

      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'
    end


    # Refinery CMS
    gem 'refinerycms', github: 'refinery/refinerycms'

    # Optionally, specify additional Refinery CMS Extensions here:
    gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']
    gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
    gem 'refinerycms-authentication-devise', '~> 1.0'
    #  gem 'refinerycms-blog', ['~> 3.0', '>= 3.0.0']
    #  gem 'refinerycms-inquiries', ['~> 3.0', '>= 3.0.0']
    #  gem 'refinerycms-search', ['~> 3.0', '>= 3.0.0']
    #  gem 'refinerycms-page-images', ['~> 3.0', '>= 3.0.0']

    gem 'slim-rails'
    gem "less-rails"
    gem "twitter-bootstrap-rails"
    gem 'font-awesome-rails'

**Comment by anitagraham** [comment]
Your gemfile should specify refinery from master.

`gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'`

I'm still building a copy from your gemfile, but with master, so I'll see how that goes.

**Comment by anitagraham** [comment]
Seems to be OK for me.

````
rails new my_app -m http://refinerycms.com/t/edge
(edit Gemfile)
bundle install
rails s -p 3001 -b 127.0.0.1
````
browsing to http://127.0.0.1:3100/refinery/users and registering on the way gives me
![screen shot 2015-09-16 at 9 29 51 am](https://cloud.githubusercontent.com/assets/397118/9894370/90878f6a-5c55-11e5-9d9b-6a01ae116b62.png)

which includes the font-awesome icons.  Just testing now to see if your line `gem font-awesome-rails` is required.

**Comment by GCorbel** [comment]
It works. I had `font-awesome.css` in my stylesheets. I think I copied it from a them. The bug was not related to refinerycms.

Thanks for your help.

**Comment by ITDevMohsin** [comment]
@GCorbel Could you please explain how did you fix this issue? 

I am also suffering the same problem at the moment. More related to `font-awesome.css`

**Comment by GCorbel** [comment]
@ITDevMohsin Sorry but I don't remember. I can't help you.
