### ISSUE TITLE
Demo website is broken 

### ISSUE THREAD

**Issue by dfabreguette-ap** [refinery/refinerycms#3058]
![image](https://cloud.githubusercontent.com/assets/7055931/10069393/563a5e0c-62ac-11e5-9ed3-d55052167ab3.png)

**Comment by bricesanchez** [comment]
What is broken ?

The demo seems to work as expected.

There is no frontend CSS/JS in order to let you the choice of your CSS framework (Bootstrap, Foundation, Neat,...)

**Comment by dfabreguette-ap** [comment]
Allright, my bad, sorry about that !

**Comment by simi** [comment]
But it will be great to add some basic theme as a gem to use it in the demo and also as a example how to theme Refinery CMS.
