### ISSUE TITLE
Image link and size issues

### ISSUE THREAD

**Issue by diogoo296** [refinery/refinerycms#3060]
Hello everyone,

I'm using Rails 4.2.3 and the RefineryCMS gem from the branch master and I'm having some trouble regarding to image links and size in the admin page.

First of all, the html attributes width and height of the images uploaded on the Image tab in the admin menu are being set to 0. I don't know exactly why but after overriding the method *thumbnail_dimensions* of the model *refinery/image* by changing the images width and height values on ```dimensions = ThumbnailDimensions.new(geometry, image.width, image.height)``` to any random value, it seems to work fine (maybe these values are nil?).

Anyway, I wasn't able to find out what's the problem with my image links. The image preview link is working fine but the image link set for the image thumbnail in the admin Image tab and in the image picker on the page edit tab is broken. I've checked [Issue #2716](https://github.com/refinery/refinerycms/pull/2716) and [Issue #2681](https://github.com/refinery/refinerycms/issues/2681) but none of the solutions there worked out for me: there's no random integer in the end of my image path and I've already set  ```config.dragonfly_verify_urls``` to *false*.

I'm developing my app from 2 different computers - say M1 and M2 - using the same repository and, to make things worse, all the images uploaded from M1 become broken when I load the DB for M2 (even the preview link) and vice-versa. And the weirdest part is that the image links work fine in M1 (when they are upload from M1) but doesn't work at all in M2 (except the image preview). These machines are running the project on development environment. The image links also didn't work when I uploaded my app on Heroku on production environment.

I'm new to Rails and RefineryCMS and sorry if this isn't the proper place to address this issue, but I'm trying to solve this problem for some time and haven't found anything relevant anywhere (except the cited issues) and, for me, it looks like some problem in the Refinery code (or maybe something wrong with Dragonfly?).

Cheers!

**Comment by bricesanchez** [comment]
Could you paste us your Gemfile.lock and the server log or the stacktrace of the errors?

Do you have imagemagick installed on both computers?

Heroku has a temp filesystem, don't expect to see uploaded images in your app after a `heroku reboot`. You have to use a third-part assets storage like Amazon S3.

**Comment by diogoo296** [comment]
It seems the problem was imagemagick, sorry for the trouble. And thanks for the tip about heroku =]

**Comment by bricesanchez** [comment]
You're welcome :)

**Comment by AkshayGoyal022** [comment]
Hi @diogoo296 
I am facing the same issue. Can you please tell us how did you solve this?

Thanks
