### ISSUE TITLE
Bundler could not find compatible versions for gem refinerycms-image_slideshows

### ISSUE THREAD

**Issue by moisesnandres** [refinery/refinerycms#3063]
I tried to add this gem but the console show me this: 

```ruby
Bundler could not find compatible versions for gem "refinerycms-core":
  In Gemfile:
    refinerycms-image_slideshows (>= 2.0.2, ~> 2.0) ruby depends on
      refinerycms-core (~> 2.0.9) ruby```

    refinerycms-blog (>= 0) ruby depends on
      refinerycms-core (3.0.0)

**Comment by bricesanchez** [comment]
What is your version of Refinery ?

Your trying to install the 2.x version of refinerycms-image_slideshows
and you've a 3.0 version refinerycms-blog

I've update refinerycms-image_slideshows for Refinery 3.0 :  https://github.com/bisscomm/refinerycms-image-slideshows

**Comment by moisesnandres** [comment]
It works, thanks a lot !
