### ISSUE TITLE
How to migrate data form v2 to v3 ?

### ISSUE THREAD

**Issue by andywenk** [refinery/refinerycms#3065]
Hi all, 

I am having hard times migrating data from a refinery v2 to a refinery v3 database. I have everything running but am now at the point that I compare the migration files from v2 with v3. I recognised, that there are more migration files now. But am I right, that the schema also changed? The names of the migration files are very different compared to the v2 files. 

How can I migrate my existing data from a v2 database to a v3 database?

Thanks 

Andy

**Comment by andywenk** [comment]
To make this a bit clearer, I screenshot the differences. I renamed the new migration files to the name of the old migration. On the right side are the different migration files with a date starting from 2015 ...

![refinery-v2_vs_v3_migrations](https://cloud.githubusercontent.com/assets/51517/10743606/62273a22-7c34-11e5-85e1-cad5de30001f.jpg)

**Comment by anitagraham** [comment]
Have you run the refinery update: 
`rails generate refinery:cms --update`
this should run any new migrations.

**Comment by andywenk** [comment]
Hi Anita,

thanks for your answer. Unfortunately there is not much documentation about that. So I decided to simply create a new rails application with 

    rails new app_name -m http://refinerycms.com/t/edge

as suggested. I moved all the assets and logic over what worked perfectly. So the db schema is already there. What is left now, is the data migration. Please note, I am migrating from a v2 to a v3 refinery app. The reason I did this is the fact, that the old application is a rails 3.x application and I need to upgrade to Rails 4.x.

What does `rails generate refinery:cms --update` do? Does it expect a v2 refinery app? Or does it simply create some migrations I can throw in? What about my old db data in the old schema? 

Thanks and all the best

Andy

**Comment by anitagraham** [comment]
I think it will create any missing migrations - and run them. 
I have migrated from a Refinery 2 to Refinery 3 app. I took notes, which I've converted to a [guide](https://gist.github.com/anitagraham/a6d1b14bd10b5737493e).

Sorry Andy, I wrote this yesterday, but must have been interrupted as I picked up the url.

**Comment by andywenk** [comment]
@anitagraham thanks a lot. I think I will retry to update the old Rails app. But I will also try to use the old migrations in the new app I created (what works already) and run the refinery:cms --update task ... I will report  ;-)

**Comment by andywenk** [comment]
This is really a frustrating process. Ok what do I have. 

* I was not able to use `rails generate refinery:cms --update` in the v2 application. 
* I copied the old migrations from the v2 app to the v3 app. Then I used `rails generate refinery:cms --update` there to get the missing migrations. This is not a problem because the old migrations are existing in the production database `schema_migrations` table
* I was able to run the migrations
* I was able to deploy the application to a preview environment (I copied the production db)

I now have the problem, that there are missing assets from refinery. 

<img width="493" alt="screen shot 2015-11-02 at 00 18 22" src="https://cloud.githubusercontent.com/assets/51517/10871966/4a0fcf86-80f7-11e5-998b-4d606715c49c.png">

Why is this? Do I have to change anything in my nginx config regarding assets? This is strange because locally it works (without precompiled assest though)

Then I am not able to open a page in the cms. Even though the URL's stayed the exact same except the fact, that there is a locale switcher:

before: pages/aktuelles/herbstferien/edit
now:    pages/aktuelles/herbstferien/edit?switch_locale=de

Any idea why I can't edit the page and get a 404 instead?

Thanks a lot for more help. Maybe @anitagraham has ideas?

Cheers

Andy

**Comment by andywenk** [comment]
**first update:**

I was able to solve the problem with not being able to edit pages by setting the locale in the refinery initializer to :de . This was the locale I used before.

**Comment by andywenk** [comment]
*second (final) update:*

after a lot of trying, I was able to get the migration running. The path to migrate a old Rails 3 application to Rails 4 is imho not recommended because it will never be a real Rails 4 application. So if you have the chance, create a new one. It is less effort in the end.

#1 the not found assets was an issue with the assets precompilation configuration. By adding:

    Rails.application.config.assets.precompile += %w( lib/selectivizr-min.js wymeditor/lang/de.js \
    wymeditor/skins/refinery/wymiframes.css refinery/themes.css refinery/formatting.css  )

the problem with the not shown images was fixed

#2 I had to add also

   Rails.application.config.assets.precompile << /\.(?:svg|eot|woff|ttf)\z/

in lib/congi/assets.rb

#3 finalyly there have been some "selfmade" issues I had to fix. At the end, it was not easy but it worked. So the important conclusion is this:

If you want to migrate with using a fresh Rails 4.2 installation 

* in your old refinery installation run:

    rails generate refinery:cms --update

* create a fresh refinery application 

    gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'
    gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']
    gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
    gem 'refinerycms-authentication-devise', '~> 1.0'

* remove all migrations in config/db/migrate in the new application
* copy all migrations from the old application into the new one. This is important because you want the old timestamped migrations for you existing production database and in addition the update migrations.
* run `bundle exec db:migrate`

The rest is just copying the assets and your code into the new one. This was a minimal effort in my case because I just had very few code.

I hope this helps someone. Thanks a lot to @anitagraham for help ;-)

Cheers

Andy
