### ISSUE TITLE
Unable to use Refinery CMS with rails 4.1.6 version

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [refinery/refinerycms#3070]
Hi,

I have a rails app whose version is 4.1.6, at that time I have used refinerycms gem in my Gemfile as below.

gem 'refinerycms', git: 'git@github.com:refinery/refinerycms', branch: 'master'
gem 'refinerycms-i18n', git: 'git@github.com:refinery/refinerycms-i18n', branch: 'master'
gem 'refinerycms-blog', git: 'git@github.com:refinery/refinerycms-blog', branch: 'master'
gem 'refinerycms-settings', github: 'git@github.com:refinery/refinerycms-settings', branch: 'master'

At the time I added these to my Gemfile I am able to work with CMS without any issue.

Now suddenly I noticed that https://github.com/refinery/refinerycms's master branch is supporting rails 4.2+ onwards.

Kindly give me branch name or commit ID that makes my refinerycms go with rails 4.1.6

Thanks,
Bhaskar

**Comment by bricesanchez** [comment]
You should upgrade to rails 4.2+ if your app is just a Refinery CMS app.

If not, you could use the commit before this https://github.com/refinery/refinerycms/commit/5bc9ecbb8d4544953f16ef2e9f5ccf3e15a866b4
