### ISSUE TITLE
Can't use active admin with refinerycms 

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [refinery/refinerycms#3073]
I have my app already integrated with refinerycms gem and when I install active admin and navigated to 
locahost:3000/admin/login got the below error.
undefined method `new_admin_user_password_path' for #<ActionDispatch::Routing::RoutesProxy:0x00000006a9cbc0>
Please tell me
1. why devise routes for active admin are not identified.
2. Is it good having both refinerycms and activeadmin in the same app.
I am sure I am not having smooth journey integrating activeadmin in the app which is already having refinerycms
If both refinerycms and activeadmmin can't fit in same app, I have to rebuild the app to use activeadmin alone.
Note: Both activeadmin & refinerycms uses devise for login

**Comment by bricesanchez** [comment]
Could you paste us your `Gemfile.lock` ?

Since 3.0, Refinery CMS is decoupled from devise, so the refinerycms-authentication-devise is now available in this gem : https://github.com/refinery/refinerycms-authentication-devise

I don't use ActiveAdmin on specific apps, i'm working with RailsAdmin (and i don't know if it's better or not). I think it is possible to fit refinerycms in an admin generator but it will needs work and tests.

IMHO, it could be great to made changes on refinerycms to be able to install or not the backend controllers/views of Refinery CMS like Spree is doing. What do you think of that @parndt ?

**Comment by railsfactory-bhaskararao** [comment]
source 'https://rubygems.org'
ruby "2.2.1"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'

# Background jobs
gem 'sidekiq'
gem 'sidetiq'
gem 'sidekiq_mailer'
gem 'sinatra', '>= 1.3.0', :require => nil

# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'font-awesome-sass'
gem 'will_paginate-bootstrap'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Backbone as JavaScript MVC framework
gem 'backbone-on-rails'
gem 'bootstrap-slider-rails'
gem 'maskedinput-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Authorization
gem 'cancancan'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-gplus'

gem 'activeadmin', '1.0.0.pre1'
# Plus integrations with:
# gem 'cancan' # or cancancan
gem 'draper'
gem 'pundit'
# Pagination
gem 'will_paginate'

# File upload / attachments
gem 'carrierwave'

#the Ruby cloud services library.
gem 'fog', '~> 1.29.0'

# Serialization
gem 'active_model_serializers'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'has_scope', '~> 0.6.0.rc'


# Use unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# state machine
gem 'workflow'

gem 'haml'
gem "haml-rails"

# Payment library
gem 'activemerchant'

gem 'geocoder'

#redis setup
gem 'redis'
gem 'redis-namespace'
gem 'redis-rails'
gem 'redis-rack-cache'
group :development do
  gem 'spring'

  gem 'annotate'
  gem 'letter_opener'

  # Better errors handler
  gem 'better_errors'
  gem 'binding_of_caller'

  gem 'rails_best_practices'

  gem 'let'
end

group :development, :test do
  gem 'coveralls'
  gem 'spinach-rails'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'pry'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'database_cleaner'
  gem 'launchy'

  # seedings
  gem 'factory_girl'
  gem 'factory_girl_rails'

  # Generate Fake data
  gem 'ffaker'

  # Guard
  gem 'guard-rspec', require: false
  gem 'guard-spinach', require: false

  # Notification
  gem 'rb-fsevent'
  gem 'growl'

  # PhantomJS driver for Capybara
  gem 'poltergeist'

  gem 'spork'
  gem 'jasmine'
end

group :production do
  gem 'rails_12factor'
end

gem 'refinerycms', git: 'git@github.com:refinery/refinerycms', ref: 'c42e835bbd7c72f07beb6c6410c478ad09546fe0'
gem 'refinerycms-i18n', git: 'git@github.com:refinery/refinerycms-i18n', branch: 'master'
gem 'refinerycms-blog', git: 'git@github.com:refinery/refinerycms-blog', ref: '55175e954a84044af29d99092e3fe8a034d39442'

gem 'quiet_assets'

# Add support for refinerycms-acts-as-indexed
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']

# Add support for refinerycms-wymeditor
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.0']
gem 'seo_meta', git: 'git@github.com:parndt/seo_meta', branch: 'master'

gem 'paper_trail', git: 'git@github.com:airblade/paper_trail', branch: 'master'
Gemfile
======================
gem 'refinerycms-settings', git: 'git@github.com:refinery/refinerycms-settings', ref: 'master'
gem 'refinerycms-authentication'


# This has to be at the bottom!!!
gem 'devise-async'

# gem 'refinerycms-website_users', path: 'vendor/extensions'

**Comment by railsfactory-bhaskararao** [comment]
GIT
  remote: git@github.com:airblade/paper_trail
  revision: 84bedae4bcd43ddb5162d947c5f7925dda872636
  branch: master
  specs:
    paper_trail (4.0.0)
      activerecord (>= 3.0, < 6.0)
      activesupport (>= 3.0, < 6.0)
      request_store (~> 1.1)

GIT
  remote: git@github.com:parndt/seo_meta
  revision: b03f2b8c7874e2ff05423998e881f6bbc2dddd83
  branch: master
  specs:
    seo_meta (2.0.0.rc.1)
      railties (>= 3.0.0)

GIT
  remote: git@github.com:refinery/refinerycms
  revision: c42e835bbd7c72f07beb6c6410c478ad09546fe0
  ref: c42e835bbd7c72f07beb6c6410c478ad09546fe0
  specs:
    refinerycms (3.0.0)
      bundler (>= 1.2.2)
      refinerycms-authentication (= 3.0.0)
      refinerycms-core (= 3.0.0)
      refinerycms-images (= 3.0.0)
      refinerycms-pages (= 3.0.0)
      refinerycms-resources (= 3.0.0)
    refinerycms-authentication (3.0.0)
      actionmailer (>= 4.0.2, < 4.2)
      devise (~> 3.0, >= 3.2.4)
      friendly_id (>= 5.0.0.rc1)
      refinerycms-core (= 3.0.0)
    refinerycms-core (3.0.0)
      actionpack (~> 4.1.5)
      activerecord (~> 4.1.5)
      awesome_nested_set (~> 3.0.0)
      coffee-rails (~> 4.0.0)
      decorators (~> 1.0.0)
      jquery-rails (>= 2.3.0)
      jquery-ui-rails (~> 5.0.0)
      railties (~> 4.1.5)
      refinerycms-i18n (~> 3.0.0.dev)
      sass-rails (~> 4.0.0)
      truncate_html (~> 0.9)
      will_paginate (~> 3.0.2)
    refinerycms-images (3.0.0)
      dragonfly (~> 1.0.0)
      dragonfly-s3_data_store (~> 1.0.0)
      refinerycms-core (= 3.0.0)
    refinerycms-pages (3.0.0)
      awesome_nested_set (~> 3.0.0)
      babosa (!= 0.3.6)
      friendly_id (~> 5.0.1)
      globalize (~> 4.0.0)
      refinerycms-core (= 3.0.0)
      seo_meta (~> 2.0.0.rc.1)
    refinerycms-resources (3.0.0)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 1.0.0)
      dragonfly-s3_data_store (~> 1.0.0)
      refinerycms-core (= 3.0.0)

GIT
  remote: git@github.com:refinery/refinerycms-blog
  revision: 55175e954a84044af29d99092e3fe8a034d39442
  ref: 55175e954a84044af29d99092e3fe8a034d39442
  specs:
    refinerycms-blog (3.0.0)
      acts-as-taggable-on
      filters_spam (~> 0.2)
      friendly_id (~> 5.0.0)
      globalize (~> 4.0.0)
      jquery-ui-rails (~> 5.0.0)
      rails_autolink (~> 1.1.3)
      refinerycms-core (~> 3.0.0)
      refinerycms-settings (~> 3.0.0)
      refinerycms-wymeditor (~> 1.0.1)
      seo_meta (~> 2.0.0.rc.1)

GIT
  remote: git@github.com:refinery/refinerycms-i18n
  revision: ff93ad912c86eb2f1a07a77ac1c75133474f7fea
  branch: master
  specs:
    refinerycms-i18n (3.0.1)
      rails-i18n (~> 4.0.1)
      routing-filter (>= 0.4.0)

GIT
  remote: git@github.com:refinery/refinerycms-settings
  revision: 10c12da53e0c6a793497c43f6cdd2f17a97e9632
  ref: master
  specs:
    refinerycms-settings (3.0.0)
      friendly_id (~> 5.0, >= 5.0.1)
      refinerycms-core (~> 3.0, >= 3.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.1)
    actionmailer (4.1.6)
      actionpack (= 4.1.6)
      actionview (= 4.1.6)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.6)
      actionview (= 4.1.6)
      activesupport (= 4.1.6)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.6)
      activesupport (= 4.1.6)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    active_model_serializers (0.9.0)
      activemodel (>= 3.2)
    active_utils (2.2.3)
      activesupport (>= 2.3.11)
      i18n
    activeadmin (1.0.0.pre1)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
    activemerchant (1.44.1)
      active_utils (~> 2.2.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      json (~> 1.7)
      nokogiri (~> 1.4)
      offsite_payments (~> 2.0.0)
    activemodel (4.1.6)
      activesupport (= 4.1.6)
      builder (~> 3.1)
    activerecord (4.1.6)
      activemodel (= 4.1.6)
      activesupport (= 4.1.6)
      arel (~> 5.0.0)
    activeresource (4.0.0)
      activemodel (~> 4.0)
      activesupport (~> 4.0)
      rails-observers (~> 0.1.1)
    activesupport (4.1.6)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    acts-as-taggable-on (3.5.0)
      activerecord (>= 3.2, < 5)
    acts_as_indexed (0.8.3)
    addressable (2.3.8)
    annotate (2.6.5)
      activerecord (>= 2.3.0)
      rake (>= 0.8.7)
    arbre (1.0.3)
      activesupport (>= 3.0.0)
    arel (5.0.1.20140414130214)
    autoprefixer-rails (4.0.1)
      execjs
    awesome_nested_set (3.0.2)
      activerecord (>= 4.0.0, < 5)
    awesome_print (1.2.0)
    babosa (1.0.2)
    backbone-on-rails (1.1.2.0)
      actionmailer
      actionpack
      activemodel
      activeresource
      eco
      ejs
      jquery-rails
      railties
    bcrypt (3.1.9)
    better_errors (2.0.0)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.1.0)
      sass (~> 3.2)
    bootstrap-slider-rails (1.9.0)
      railties (>= 3.2, < 5.0)
    bourbon (3.2.4)
      sass (~> 3.2)
      thor
    builder (3.2.2)
    cancancan (1.9.2)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.3.1)
      capybara (>= 2.0.2, < 2.5.0)
      json
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    cliver (0.3.2)
    code_analyzer (0.4.5)
      sexp_processor
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.8.0)
    colored (1.2)
    colorize (0.7.3)
    connection_pool (2.1.0)
    coveralls (0.7.1)
      multi_json (~> 1.3)
      rest-client
      simplecov (>= 0.7)
      term-ansicolor
      thor
    database_cleaner (1.3.0)
    debug_inspector (0.0.2)
    decorators (1.0.3)
      railties (>= 3.0.19, != 3.2.9, != 3.2.8, != 3.2.7, != 3.2.6, != 3.2.5, != 3.2.4, != 3.2.3, != 3.2.2, != 3.2.10, != 3.2.1, != 3.2.0, != 3.1.9, != 3.1.8, != 3.1.7, != 3.1.6, != 3.1.5, != 3.1.4, != 3.1.3, != 3.1.2, != 3.1.1, != 3.1.0)
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-async (0.9.0)
      devise (~> 3.2)
    diff-lcs (1.2.5)
    docile (1.1.5)
    dragonfly (1.0.12)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack (>= 1.3.0)
    dragonfly-s3_data_store (1.0.5)
      dragonfly (~> 1.0)
      fog
    draper (2.1.0)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      request_store (~> 1.0)
    eco (1.0.0)
      coffee-script
      eco-source
      execjs
    eco-source (1.1.0.rc.1)
    ejs (1.1.1)
    erubis (2.7.0)
    excon (0.45.3)
    execjs (2.2.2)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faraday (0.9.0)
      multipart-post (>= 1.2, < 3)
    ffaker (1.25.0)
    ffi (1.9.8)
    filters_spam (0.5)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.29.0)
      fog-atmos
      fog-aws (~> 0.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.27, >= 1.27.4)
      fog-ecloud
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri (~> 1.5, >= 1.5.11)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.1.2)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.7.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.30.0)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-ecloud (0.1.1)
      fog-core
      fog-xml
    fog-json (1.0.1)
      fog-core (~> 1.0)
      multi_json (~> 1.0)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.2)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.0.1)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (0.4.5)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-sass (4.2.2)
      sass (~> 3.2)
    formatador (0.2.5)
    formtastic (3.1.3)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.4.1)
    friendly_id (5.0.5)
      activerecord (>= 4.0.0)
    geocoder (1.2.7)
    gherkin-ruby (0.3.2)
    globalize (4.0.3)
      activemodel (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
    growl (1.0.3)
    guard (2.12.5)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.5.0)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-spinach (0.0.3)
      guard (>= 1.1)
      spinach
    haml (4.0.5)
      tilt
    haml-rails (0.5.3)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 3.1, < 5.0)
      railties (>= 4.0.1)
    has_scope (0.6.0)
      actionpack (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)
    hashie (3.3.1)
    hike (1.2.3)
    hitimes (1.2.2)
    i18n (0.6.11)
    ice_cube (0.11.1)
    inflecto (0.0.2)
    inherited_resources (1.6.0)
      actionpack (>= 3.2, < 5)
      has_scope (~> 0.6.0.rc)
      railties (>= 3.2, < 5)
      responders
    ipaddress (0.8.0)
    jasmine (2.1.0)
      jasmine-core (~> 2.1.0)
      phantomjs
      rack (>= 1.2.1)
      rake
    jasmine-core (2.1.2)
    jbuilder (2.2.5)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.2)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.1)
    jwt (1.2.0)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    kgio (2.9.2)
    launchy (2.4.3)
      addressable (~> 2.3)
    let (0.1.3)
    letter_opener (1.3.0)
      launchy (~> 2.2)
    listen (2.10.0)
      celluloid (~> 0.16.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    maskedinput-rails (1.3.1.0)
    method_source (0.8.2)
    mime-types (2.4.3)
    mini_portile (0.6.1)
    minitest (5.4.3)
    money (6.4.0)
      i18n (>= 0.6.4, <= 0.7.0.beta1)
    multi_json (1.10.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nenv (0.2.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    netrc (0.8.0)
    nokogiri (1.6.4.1)
      mini_portile (~> 0.6.0)
    notiffany (0.0.6)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    offsite_payments (2.0.1)
      active_utils (~> 2.2.0)
      activesupport (>= 3.2.14, < 5.0.0)
      builder (>= 2.1.2, < 4.0.0)
      i18n (~> 0.5)
      json (~> 1.7)
      money (< 7.0.0)
      nokogiri (~> 1.4)
    omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-facebook (2.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-gplus (2.0.1)
      omniauth-oauth2 (~> 1.1)
    omniauth-oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      multi_json (~> 1.3)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    pg (0.17.1)
    phantomjs (1.9.7.1)
    poltergeist (1.5.1)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    polyamorous (1.2.0)
      activerecord (>= 3.0)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.2)
      pry (>= 0.9.10)
    pundit (1.0.1)
      activesupport (>= 3.0.0)
    quiet_assets (1.0.3)
      railties (>= 3.1, < 5.0)
    rack (1.5.2)
    rack-cache (1.5.1)
      rack (>= 0.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.1.6)
      actionmailer (= 4.1.6)
      actionpack (= 4.1.6)
      actionview (= 4.1.6)
      activemodel (= 4.1.6)
      activerecord (= 4.1.6)
      activesupport (= 4.1.6)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.6)
      sprockets-rails (~> 2.0)
    rails-i18n (4.0.5)
      i18n (~> 0.6)
      railties (~> 4.0)
    rails-observers (0.1.2)
      activemodel (~> 4.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_autolink (1.1.6)
      rails (> 3.1)
    rails_best_practices (1.15.4)
      activesupport
      awesome_print
      code_analyzer (>= 0.4.3)
      colored
      erubis
      i18n
      json
      require_all
      ruby-progressbar
    rails_serve_static_assets (0.0.2)
    rails_stdout_logging (0.0.3)
    railties (4.1.6)
      actionpack (= 4.1.6)
      activesupport (= 4.1.6)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    raindrops (0.13.0)
    rake (10.4.0)
    ransack (1.7.0)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.2)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.1.2)
      json (~> 1.4)
    redis (3.1.0)
    redis-actionpack (4.0.1)
      actionpack (~> 4)
      redis-rack (~> 1.5.0)
      redis-store (~> 1.1.0)
    redis-activesupport (4.1.5)
      activesupport (>= 3, < 5)
      redis-store (~> 1.1.0)
    redis-namespace (1.5.1)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (1.5.0)
      rack (~> 1.5)
      redis-store (~> 1.1.0)
    redis-rack-cache (1.2.2)
      rack-cache (~> 1.2)
      redis-store (~> 1.1.0)
    redis-rails (4.0.0)
      redis-actionpack (~> 4)
      redis-activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-store (1.1.7)
      redis (>= 2.2)
    refinerycms-acts-as-indexed (2.0.0)
      acts_as_indexed (~> 0.8.0)
      decorators (~> 1.0.0)
      refinerycms-core (~> 3.0.0)
    refinerycms-wymeditor (1.0.3)
      refinerycms-core (~> 3.0, >= 3.0.0)
    request_store (1.2.0)
    require_all (1.3.2)
    responders (1.1.2)
      railties (>= 3.2, < 4.2)
    rest-client (1.7.2)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    routing-filter (0.4.0.1)
      actionpack (< 4.2)
    rspec (3.1.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-rails (3.1.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    ruby-progressbar (1.7.0)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    sexp_processor (4.4.4)
    shellany (0.0.1)
    sidekiq (3.3.0)
      celluloid (>= 0.16.0)
      connection_pool (>= 2.0.0)
      json
      redis (>= 3.0.6)
      redis-namespace (>= 1.3.1)
    sidekiq_mailer (0.0.8)
      actionmailer (>= 3.0)
      activesupport (>= 3.0)
      sidekiq (>= 2.3)
    sidetiq (0.6.3)
      celluloid (>= 0.14.1)
      ice_cube (= 0.11.1)
      sidekiq (>= 3.0.0)
    simplecov (0.9.1)
      docile (~> 1.1.0)
      multi_json (~> 1.0)
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    slop (3.6.0)
    spinach (0.8.10)
      colorize
      gherkin-ruby (>= 0.3.2)
      json
    spinach-rails (0.2.1)
      capybara (>= 2.0.0)
      railties (>= 3)
      spinach (>= 0.4)
    spork (0.9.2)
    spring (1.2.0)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    term-ansicolor (1.3.0)
      tins (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    tins (1.3.3)
    truncate_html (0.9.3)
    turbolinks (2.5.2)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.5.3)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unicorn (4.8.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    warden (1.2.3)
      rack (>= 1.0)
    websocket-driver (0.4.0)
    will_paginate (3.0.7)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)
    workflow (1.2.0)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers
  activeadmin (= 1.0.0.pre1)
  activemerchant
  annotate
  autoprefixer-rails
  awesome_print
  backbone-on-rails
  better_errors
  binding_of_caller
  bootstrap-sass
  bootstrap-slider-rails
  cancancan
  capybara
  capybara-webkit
  carrierwave
  coffee-rails (~> 4.0.0)
  coveralls
  database_cleaner
  devise
  devise-async
  draper
  factory_girl
  factory_girl_rails
  ffaker
  fog (~> 1.29.0)
  font-awesome-sass
  geocoder
  growl
  guard-rspec
  guard-spinach
  haml
  haml-rails
  has_scope (~> 0.6.0.rc)
  jasmine
  jbuilder (~> 2.0)
  jquery-rails
  launchy
  let
  letter_opener
  maskedinput-rails
  omniauth
  omniauth-facebook
  omniauth-gplus
  paper_trail!
  pg
  poltergeist
  pry
  pry-rails
  pundit
  quiet_assets
  rails (= 4.1.6)
  rails_12factor
  rails_best_practices
  rb-fsevent
  redis
  redis-namespace
  redis-rack-cache
  redis-rails
  refinerycms!
  refinerycms-acts-as-indexed (~> 2.0, >= 2.0.0)
  refinerycms-authentication
  refinerycms-blog!
  refinerycms-i18n!
  refinerycms-settings!
  refinerycms-wymeditor (~> 1.0, >= 1.0.0)
  rspec-rails
  sass-rails (~> 4.0.3)
  sdoc (~> 0.4.0)
  seo_meta!
  sidekiq
  sidekiq_mailer
  sidetiq
  sinatra (>= 1.3.0)
  spinach-rails
  spork
  spring
  turbolinks
  uglifier (>= 1.3.0)
  unicorn
  will_paginate
  will_paginate-bootstrap
  workflow

**Comment by parndt** [comment]
Not keen on that sort of change to Refinery. What would be the point of it, then?

Seems like this issue is just a devise conflict and is the whole reason for extracting refinerycms-authentication-devise out.  In this case, Refinery should be told to use ActiveAdmin's authentication classes.

**Comment by bricesanchez** [comment]
@parndt Decoupling Refinery from its Backend could be great if i push data from a webservice or if i use RailsAdmin/ActiveAdmin for another part of the app.

**Comment by railsfactory-bhaskararao** [comment]
@parndt  & @bricesanchez  my app has devise also separately installed apart from refinerycms.
My understanding is activeadmin conflicting with refinery itself. because when I created sample app with refinerycms and activeadmin. I had same routes conflict.

is it possible to have devise configured to 2 gems, of-course same vrsion ?

Note: Devise is not installed seperately, it is with refinery itself.

**Comment by railsfactory-bhaskararao** [comment]
I  have deleted refineycms modules by running rails destroy on 
Refinery:
  refinery:authentication
  refinery:blog
  refinery:cms
  refinery:core
  refinery:dummy
  refinery:engine
  refinery:form
  refinery:i18n
  refinery:images
  refinery:pages
  refinery:resources
  refinery:settings
  refinery:wymeditor

and deleted file are 

	deleted:    app/decorators/controllers/refinery/.keep
	deleted:    app/decorators/models/refinery/.keep
	deleted:    app/views/sitemap/index.xml.builder
	deleted:    config/initializers/refinery/authentication.rb
	deleted:    config/initializers/refinery/blog.rb
	deleted:    config/initializers/refinery/core.rb
	deleted:    config/initializers/refinery/i18n.rb
	deleted:    config/initializers/refinery/images.rb
	deleted:    config/initializers/refinery/pages.rb
	deleted:    config/initializers/refinery/resources.rb
	deleted:    config/initializers/refinery/settings.rb

but when I navigated to http://localhost:3000/page/refinery/pages

I am able to see refinery working fine. Can someone tell me how to decouple refinerycms totall from my app.

Thanks in advance.

**Comment by parndt** [comment]
Remove it from the Gemfile
