### ISSUE TITLE
Fresh with prepend_path error 

### ISSUE THREAD

**Issue by mrozel** [refinery/refinerycms#3085]
Trying to get a refinery instance up and running to test it out... Following http://www.refinerycms.com/download with :
Rails 4.2.5
ruby-2.3.0

Partial stack below...

Bundle complete! 17 Gemfile dependencies, 85 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
        rake    db:create
    generate    refinery:cms --fresh-installation new my_new_application -m http://refinerycms.com/t/edge
/home/mac/.rvm/gems/ruby-2.1.0/gems/speakingurl-rails-1.1.5/lib/speakingurl-rails.rb:8:in `block in <class:Railtie>': undefined method `prepend_path' for nil:NilClass (NoMethodError)
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /home/mac/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /home/mac/projects/my_new_application/config/environment.rb:5:in `<top (required)>'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/mac/.rvm/gems/ruby-2.1.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
    ============================================================================
    Your new Refinery CMS application is now running on edge and mounted to /.
  ============================================================================
         run  bundle install

**Comment by bricesanchez** [comment]
Hello, this issue is knowned, please see : https://github.com/refinery/refinerycms/issues/3081#issuecomment-166306999
