### ISSUE TITLE
multiple XSS found in refinery CMS 

### ISSUE THREAD

**Issue by cor3sm4sh3r** [refinery/refinerycms#3097]
for more information about the vulnerabilities

contact me cor3sm4sh3r@gmail.com

**Comment by bricesanchez** [comment]
Hello @cor3sm4sh3r,

Thanks for reporting! 

Could you join us on Gitter : https://gitter.im/refinery/refinerycms ?

We will be able to chat privately in order to reproduce the vunerabilities and find a fix.

**Comment by parndt** [comment]
Thanks!
