### ISSUE TITLE
Please add a "source code" link to your rubygems page

### ISSUE THREAD

**Issue by jaredbeck** [refinery/refinerycms#3099]
On https://rubygems.org/gems/refinerycms-pages I do not see a "source code" link. Please log into rubygems and add it, perhaps linking to https://github.com/refinery/refinerycms or perhaps to https://github.com/refinery/refinerycms/tree/master/pages. Thanks.

**Comment by parndt** [comment]
Done

**Comment by jaredbeck** [comment]
Thanks!
