### ISSUE TITLE
rack-cache 1.6.0 breaks image upload in refinerycms-pages 3.0.1

### ISSUE THREAD

**Issue by jaredbeck** [refinery/refinerycms#3100]
**Expected behavior:** On `/refinery/pages/new`, click Add Image -> Upload -> Browse -> Save. Expect to see image inline, in editor.

**Observed behavior with rack-cache 1.6.0:** On `/refinery/pages/new`, click Add Image -> Upload -> Browse -> Save. See `alt` text in editor, instead of image.

**Workaround:** For now, my team has constrained our `rack-cache` version to `~> 1.5.1`.

Any ideas how to troubleshoot this further?

**Comment by jaredbeck** [comment]
The [rack-cache changelog][1] lists a few changes for 1.6.0, but does not [clarify which are breaking changes][2].

[1]: https://github.com/rtomayko/rack-cache/blob/master/CHANGES
[2]: http://keepachangelog.com/

**Comment by bricesanchez** [comment]
I've no idea yet, feel free to provide a pull request if you find a solution.

Thanks :)

**Comment by parndt** [comment]
@jaredbeck Is this still a problem with rack 1.6.1?
How about 1.7.0 (unreleased, but you can use the GitHub address for the gem)?

**Comment by jaredbeck** [comment]
> Is this still a problem with rack 1.6.1?

No. Also, it looks like 1.6.0 has been yanked. 

```
# https://rubygems.org/gems/rack-cache/versions
1.6.1 - February 11, 2016 (27.5 KB)
1.6.0 - January 29, 2016 (27.5 KB) yanked
1.5.1 - October 24, 2015 (26.5 KB) 
```

The changelog for 1.6.1 reads:

> Revert 'No longer read responses from cache when we already have them'

I don't know what they're talking about, but the fact that they reverted something indicates to me that they found a bug.

I think we can close this, thanks.
