### ISSUE TITLE
Please show the "Upgrading to 3" guide on guides index

### ISSUE THREAD

**Issue by jaredbeck** [refinery/refinerycms#3103]
I can't find this guide (https://github.com/refinery/refinerycms/blob/master/doc/guides/6%20-%20Updating%20Refinery/Upgrading%20to%20Refinery%203.0.md) on the guides index (http://www.refinerycms.com/guides). Thanks.

**Comment by bricesanchez** [comment]
@parndt Is it possible to update the Guides on the website (and show me how to do it) ?

**Comment by parndt** [comment]
@jaredbeck @bricesanchez this guide will not show up because it is written in markdown, whereas the website is expecting `.textile` files :smile:

**Comment by bricesanchez** [comment]
Closed in favor of #3202
