### ISSUE TITLE
Generating extension with image type attribute fails when trying to create a record with an image

### ISSUE THREAD

**Issue by dianaq12** [refinery/refinerycms#3109]
In release 3.0.1 I created a contacts extension with a photo attribute of type image.   When I try to create a new contact via the Refinery Admin UI and try to upload an image for my contact I get the following error:

```
ActionController::UnpermittedParameters - found unpermitted parameter: image:
  actionpack (4.2.5.1) lib/action_controller/metal/strong_parameters.rb:497:in `unpermitted_parameters!'
  actionpack (4.2.5.1) lib/action_controller/metal/strong_parameters.rb:339:in `permit'
   () usr/local/rvm/gems/ruby-2.1.2/bundler/gems/refinerycms-019f18356d6a/images/app/controllers/refinery/admin/images_controller.rb:144:in `image_params'
   () usr/local/rvm/gems/ruby-2.1.2/bundler/gems/refinerycms-019f18356d6a/images/app/controllers/refinery/admin/images_controller.rb:46:in `block in create'
   () usr/local/rvm/gems/ruby-2.1.2/bundler/gems/refinerycms-019f18356d6a/images/app/controllers/refinery/admin/images_controller.rb:44:in `each'
   () usr/local/rvm/gems/ruby-2.1.2/bundler/gems/refinerycms-019f18356d6a/images/app/controllers/refinery/admin/images_controller.rb:44:in `create'
.....
```
Here's the screenshot.  
<img width="1180" alt="refinery_error" src="https://cloud.githubusercontent.com/assets/128208/13029557/46bb718e-d244-11e5-8640-2a21243f4755.png">

After debugging I found that the problem is that when posting the image the image attribute is getting passed in as an array.  With strong parameters if you've got an array you need to define it as as array when calling permit.  So I modified the permitted_image_params method in ../admin/images_controller from this:
```ruby
def permitted_image_params
        [
          :image, :image_size, :image_title, :image_alt
        ]
end
```
to this:
```ruby
def permitted_image_params
        [
          { image: [] }, :image_size, :image_title, :image_alt
        ]
 end
```
Now I can successfully save new images.

**Comment by parndt** [comment]
We will need to patch the generator to handle an image type correctly.

**Comment by parndt** [comment]
This doesn't actually cause any issues, except where you have Rails set to raise an exception upon unpermitted parameters.  I am still preparing a patch.
