### ISSUE TITLE
When creating an extension the page part titles when editing the index page are getting display as the hash values

### ISSUE THREAD

**Issue by dianaq12** [refinery/refinerycms#3112]
In 3.0.1 I created an extension called "Contacts".  Once the extension was created when I try to edit the index page the page part titles look like "{:title=>"Body", :slug=>"body"}".  It seems like the title is getting taken directly out of the title attribute but this is what is getting stored in the database table refinery_page_parts:
<img width="1164" alt="page_parts_table" src="https://cloud.githubusercontent.com/assets/128208/13056466/573ee81a-d3ca-11e5-8016-fa63a6ed42a8.png">

This is what it looks like from the Admin UI:
<img width="1261" alt="contacts_admin_edit" src="https://cloud.githubusercontent.com/assets/128208/13056476/6c48d9c8-d3ca-11e5-8648-e80d135bfe1c.png">

Everything is working, it's just the tab labels aren't displaying correctly.

**Comment by bricesanchez** [comment]
Normally, i've fixed that : https://github.com/refinery/refinerycms/commit/6664fbbf7d5f69aee926368e7613cd256f64eff8

Is this commit help you?

**Comment by dianaq12** [comment]
Ok well it's sort of fixed now.  I pulled your commit and created a new extension called "Collection".     With your fix the entries in the page_parts table now have the slug value set like the standard pages "body" and "side_body" and the corresponding title value.   The admin page for the home page now displays the title of the page parts correctly. But now the page isn't working correctly :(    The body part of the page is getting overridden by the HTML for the list of child pages for the extension.  So the final page includes the list of child pages and "side_body" only.  The "body" part of the page does not get displayed.  

Here's what I've been able to work out:

method render_content_presenter in ../refinery/pages/content_pages_helper is calling fetch_template_overrides on the content_page and that's what's overriding the body section of the page. 

Here's a screenshot of my debugging session before calling fetch_template_overrides.  You can see that the body page part section is set correctly via @fallback_html :
<img width="938" alt="screen shot 2016-02-15 at 2 07 01 pm" src="https://cloud.githubusercontent.com/assets/128208/13062011/6b46da2c-d3f0-11e5-8d8c-818d384e0c6e.png">

But after calling fetch_template_overrides @override_html is now set to the list of child pages.  This should not happen because now I've lost the body content I entered via the Admin UI.
<img width="886" alt="screen shot 2016-02-15 at 2 07 39 pm" src="https://cloud.githubusercontent.com/assets/128208/13062107/dea8c9f8-d3f0-11e5-8750-df90f6e1d7d6.png">

If I go into the database and change the slug value in the page_parts table to something other than "body" then everything seems to work correctly.  So it seems like there is either an issue with the way the overrides are being applied on an extension or the extension can't call it's slug "body".  This was working before your fix because before your fix the slug value for the "body" page part was getting set to "title_body_slug_body".

I hope this helps.  Let me know if I can provide any further details.
