### ISSUE TITLE
How to add new menu in a admin pannel

### ISSUE THREAD

**Issue by sajjadmurtaza** [refinery/refinerycms#3116]

**Comment by anitagraham** [comment]
Perhaps you could explain a bit more what you want.

**Comment by sajjadmurtaza** [comment]
Actually in refinery(Admin pannel) i want to add new tab.

![tab](https://cloud.githubusercontent.com/assets/8552702/13218493/cc7b7834-d98b-11e5-80f3-104014dabaee.png)

**Comment by anitagraham** [comment]
What version of Refinery are you using? Recent versions have a vertical menu and no longer include the dashboard. Not that the version you are using matters.

The tabs you see reflect Refinery core plugins (files, images, pages) and any additional plugins and extensions  you are using (blog, client reports, industries, settings, slides).
