### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by deepj** [refinery/refinerycms#3120]
I think it would be more than useful having support of Rails 5 in near future.

**Comment by bricesanchez** [comment]
I've started a work on Rails 5.0 : https://github.com/refinery/refinerycms/tree/feature/rails-5

Feel free to contribute :)

**Comment by deepj** [comment]
@bricesanchez any hints how to run tests properly? Because I haven't getting the issues mentioned by you https://github.com/refinery/refinerycms/pull/3122

**Comment by bricesanchez** [comment]
@deepj What issues did you get?

**Comment by parndt** [comment]
Please continue discussion in the PR #3122
