### ISSUE TITLE
category folders not collapsing?

### ISSUE THREAD

**Issue by j2studio** [refinery/refinerycms#3126]
Hi, I ma looking to see if anyone else has issues with the category directories/folders not collapsing for them. I have over 200 articles (200+ more to come) and over a dozen directories and navigating the admin area with all folders expanded is kind of a pain.

Any help is appreciated.

![refinery-capture](https://cloud.githubusercontent.com/assets/931969/13606393/cee9778a-e519-11e5-8d07-96eb19336f4d.jpg)

**Comment by bricesanchez** [comment]
Could you copy/paste your `Gemfile.lock` ?

**Comment by bricesanchez** [comment]
@j2studio any news?

**Comment by bricesanchez** [comment]
I'm closing this issue because there no answer since 1 month. 

Feel free to reopen it if someone has the same problem.
