### ISSUE TITLE
Page bkgd image showing in editor

### ISSUE THREAD

**Issue by j2studio** [refinery/refinerycms#3127]
Wondering why the site page bkgd is showing in the WYSIWYG editor? Anyone else share the same issue?

![refinery-capture2](https://cloud.githubusercontent.com/assets/931969/13607047/74b124fe-e51c-11e5-853b-2d9c26e171f9.jpg)

**Comment by bricesanchez** [comment]
You probably have HTML divs and CSS in your WYSIWYG editor

**Comment by bricesanchez** [comment]
Is it fixing your problem?

**Comment by parndt** [comment]
If you added the CSS to `formatting.css` then this is imported by WYMeditor automatically to give your users an impression of site styles.  Normally you'd have font sizes and colours etc in here but a background colour sure does look out of place!

If you move the `body { }` style to another CSS file then your problem may be solved.  

Please let us know if that's not the case.
