### ISSUE TITLE
Resources migrations gone

### ISSUE THREAD

**Issue by amoody2108** [refinery/refinerycms#3130]
So something is going on with my resources. When navigating to the files tab in the admin panel I am hit with: 

`PG::UndefinedTable: ERROR:  relation "refinery_resources" does not exist
LINE 5:                WHERE a.attrelid = '"refinery_resources"'::re...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"refinery_resources"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum`

I'm pretty sure I could navigate to the files tab when I first made this refinery app. Any advice on getting resources properly loaded up?

**Comment by bricesanchez** [comment]
Could you copy / paste your Gemfile.lock file ?

**Comment by parndt** [comment]
If the migrations are missing then:

```
rails generate refinery:resources
rake db:migrate
```

Should fix it.. if they're in there then something else has gone wrong and please let us know so that we can reopen the issue :smile:
