### ISSUE TITLE
undefined method 'cache_page' with 3-0-stable

### ISSUE THREAD

**Issue by arnie05** [refinery/refinerycms#3139]
When config.cache_pages_full is set to true inside config/initializers/refinery/pages.rb :
It works with 2-1-stable but it doesn’t with 3-0-stable,
Error is : undefined method 'cache_page' for Refinery::PagesController

**Comment by bricesanchez** [comment]
i think you need this gem in your production group of the Gemfile : 
`gem 'actionpack-page_caching'`

**Comment by arnie05** [comment]
Thanks a lot, I submitted a pull request to add that in the guides.

**Comment by bricesanchez** [comment]
Thanks! 

I'm asking myself if we should add it in the core gemspec as a dependency or in the installer : https://github.com/refinery/refinerycms/blob/028b3b70f14773ad0a1c7e113f418e218e5f417e/templates/refinery/installer.rb

What do you think @parndt ?

**Comment by parndt** [comment]
I'm negative on adding more dependencies, I think this should just be documented in the initialiser where this setting is set?

**Comment by bricesanchez** [comment]
What about adding this gem in the installer.rb?

**Comment by parndt** [comment]
It's optional, though.  I'd favour the inline docs in the place where this is enabled.

**Comment by bricesanchez** [comment]
ok, i will create a PR for that.
