### ISSUE TITLE
More than 1 menu items are highlighted in admin area

### ISSUE THREAD

**Issue by thehappycoder** [refinery/refinerycms#3143]
There is an extension called reviews which has the following models: review, short_review. When I select short reviews in admin, both of them get highlighted.
![untitled](https://cloud.githubusercontent.com/assets/60022/14143397/52ca590a-f6ce-11e5-85ca-9cf22c0c894b.jpg)

**Comment by bricesanchez** [comment]
This is problably a problem in your review engine  `plugin.menu_match` definition.
Like in the page engine : https://github.com/refinery/refinerycms/blob/master/pages/lib/refinery/pages/engine.rb#L15

**Comment by thehappycoder** [comment]
I am actually using the defaults that were generated.

plugin.menu_match for both are like this:
reviews - %r{refinery/reviews(/.*)?$}
short_reviews - %r{refinery/reviews/short_reviews(/.*)?$}

**Comment by bricesanchez** [comment]
Normally `short_reviews` should not be in the plugin menu, it should be in the `reviews` sidebar inside the button "Add a new review"

**Comment by thehappycoder** [comment]
No, actually it has completely different attributes.

Ideally, I would make "Reviews" top menu and 2 submenus in it: video, short. But refinery doesn't let me create an extension with a general name, and I am not sure it's even possible to have nested menus.

**Comment by bricesanchez** [comment]
You could read the source code of https://github.com/refinery/refinerycms-blog to see how to use multiples models in one extension. 

The refinerycms engine generator is just a kickstarter for your app, feel free to change your code after and perhaps provide a PR to improve the engine generator.

**Comment by parndt** [comment]
Update the regular expression of reviews to exclude matches of short_reviews

**Comment by bricesanchez** [comment]
Is it ok for you @thehappycoder ?

**Comment by thehappycoder** [comment]
@bricesanchez 
The client decided not to use refinerycms for custom components because of too many engines, so this question is not relevant anymore. They will use it for blogging and pages only.

**Comment by bricesanchez** [comment]
Just in case, when you create an extension you don't have to create an engine by model.
