### ISSUE TITLE
I want to change the behavior of find_for_database_authentication in refinery User model.

### ISSUE THREAD

**Issue by sajjadmurtaza** [refinery/refinerycms#3150]
class << self
      # Find user by email or username.
      # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign_in-using-their-username-or-email-address
      def find_for_database_authentication(conditions)
        value = conditions[authentication_keys.first]
        where(["username = :value OR email = :value", { :value => value }]).first
      end
    end

**Comment by sajjadmurtaza** [comment]
I just want where(["username = :value OR email = :value", { :value => value.downcase }]).first

**Comment by bricesanchez** [comment]
You could create a decorator to override this method
