### ISSUE TITLE
Scoping nested page URL to root

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3155]
What I want is to scope some (not all) of nested pages of some parent-page to root, so it will be not like `example.com/parent/child`, but `example.com/child`. Is it possible in some easy way in Refinery? Now if I add custom slug for nested page, the url for it will be example.com/[parent-path]/[nested-page-path].
If I add '/' symbol in front of nested custom slug, nothing changes (which is sad, it could be possible implementation of such feature).

**Comment by bricesanchez** [comment]
`Refinery::Page.use_custom_slugs` config doesn't helped you?

See : https://github.com/refinery/refinerycms/blob/6726581761fc182ee5c33db266002383c505ab4b/pages/lib/generators/refinery/pages/templates/config/initializers/refinery/pages.rb.erb#L35

**Comment by sintro** [comment]
@bricesanchez, `Refinery::Page.use_custom_slugs` is exactly the way I`ve got the possibility to try my own slugs. But it seems like I have no way to assign the page "root-level" url if it is nested page of another one (for instance, if the page 'contacts' is nested page of 'about us' page, it is impossible to do the address 'example.com/contacts' for this page, it will always be 'example.com/about-us/[slug]')

**Comment by bricesanchez** [comment]
Hummm... i see. I don't know at this time how to do it if you don't move your page in the root of the tree.

Why do you need to do this ?

**Comment by sintro** [comment]
Just the wish to organize the pages in main menu in some submenus, but without some of submenu`s items to be actually in some nested url. The example with "Contacts" is almost the real-life case.
I can assume, the possible implementation for such feature could be using trailing '/' or even '../' chars in custom slug to move up in deep nested structures , so the Refinery will route this page in upper scope.

**Comment by ghoppe** [comment]
You could do this. Assuming `contacts` is the slug you want.
- Have your normal "Contacts" page set at the root of the tree. Under the Page Options **uncheck** "Display this page in the site menu"
- Make a new page in your menu hierarchy underneath "about-us". In the advanced options put `/contacts` in the "Forward this page to another website or page" field.

**Comment by sintro** [comment]
@ghoppe, Nice workaround, thanks!
