### ISSUE TITLE
Extending custom extension (adding fields)

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3160]
Is there any way to do something like
```
generate refinery:engine:add_fields event status:integer
```
So the refinery automatically will add necessary migrations and update locales for previously created by user extension "Event"?
It is also make sense command like
```
generate refinery:engine:remove event status
```

**Comment by bricesanchez** [comment]
You should run this command in the root folder of your main app : 

```ruby
rails generate refinery:engine event status:integer
```

**Comment by bricesanchez** [comment]
@sintro can i close this issue?

**Comment by sintro** [comment]
Actually, I just tried to do this with my custom engine, and looks like it is just overwriting whole the extension so it will have only new fields, but not appends them.

**Comment by parndt** [comment]
Sorry, it's require too many workarounds to support this. Happy for someone else to try but I'm closing this issue. Thanks!
