### ISSUE TITLE
Restyaboard integration

### ISSUE THREAD

**Issue by reidharry** [refinery/refinerycms#3163]
I'm looking to integrate Refinery CMS with [Restyaboard](https://github.com/RestyaPlatform/board)

Can I get the integration document, if any?

**Comment by bricesanchez** [comment]
What do you mean by integration? 

Do you need a REST API or a shared auth?

**Comment by bricesanchez** [comment]
There is a working progress REST API for Refinery CMS : https://github.com/refinerycms-contrib/refinerycms-api

You can work on it to create your integration.
