### ISSUE TITLE
Pages and engine generator : caching strategy

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms#3172]
> Page caching
> Rails' page_caching gem works by creating a file on the file system. Heroku has an ephemeral file store, so while page caching may appear to work, it won’t work as intended. You should instead use action or fragment caching, or alternatively use Rack::Cache as a reverse proxy to avoid requests to your apps at all.

Source: https://devcenter.heroku.com/articles/caching-strategies#page-caching

According to Heroku, we should probably move from `actionpack-page_caching` to `actionpack-action_caching` : 

https://github.com/refinery/refinerycms/blob/master/pages/app/controllers/refinery/pages_controller.rb#L88-L90

I also note that we do not create a caching strategy when we use the engine generator, we should add a strategy by default.

**Comment by bricesanchez** [comment]
After reading this : https://signalvnoise.com/posts/3113-how-key-based-cache-expiration-works

We should use key-based cache expiration instead of `actionpack-page_caching` or `actionpack-action_caching` in order to be future proof.

**Comment by bricesanchez** [comment]
It should be added to menus, page tree and sections.

**Comment by parndt** [comment]
@bricesanchez are you still interested in this?

**Comment by bricesanchez** [comment]
Yes! I have to work on the section /menu presenter to add cache key

**Comment by parndt** [comment]
Can I close this issue in favour of you opening a pull request, or would you like it left open?

**Comment by bricesanchez** [comment]
I can close it, it will be part of a backlog.
