### ISSUE TITLE
Images are not found after moving a Refinery Installation to a new server

### ISSUE THREAD

**Issue by andywenk** [refinery/refinerycms#3181]
Hi there,

I am not sure why, but after moving a whole RefineryCMS 3.0.3 installation to a new server, including a sync of the images and database, the uploaded images via the CMS are not showing anymore. As the image url's have a structure like /system/images/W1siZiIsIjIwMTQvMDgvMzEvMTBfNTJfMTJfNzI0X0lNR18wMzE3LmpwZyJdLFsicCIsInRodW1iIiwiMjI1eDI1NT4iXSxbInAiLCJzdHJpcCJdXQ/IMG_0317.jpg I am wondering if this url has to be recreated. Or is there something else I have to do? The behaviour is unexpected here ... 

can be seen here: http://sn.ro72.de/

Happy about any help.

Thanks and all the best

Andy

**Comment by bricesanchez** [comment]
Is it happens only on images files ?
If no, do you have the same `dragonfly_secret ` than before in core, images and resource?

Is resources files are still available ?
If yes, do you have `imagemagick` on this new server ?

**Comment by andywenk** [comment]
@bricesanchez you made my day. I completely forgot that imagemagick is required. Stupid I am.

But let me take the chance to ask how one would setup dragonfly for refinery. Is there an example somewhere? The secrets are all not used (commented) and I would love to change the URL format. Is that still possible in a running system.

Thanks so much and all the best

Andy

**Comment by bricesanchez** [comment]
You're welcome!

For my part, i uncomment all secrets for Dragonfly, i don't know if it's the best practice but it works.

I don't know if you can change the URL format, it's probably more a Dragonfly config than a Refinery config.

**Comment by andywenk** [comment]
@bricesanchez ok thanks a lot - I will give that a try ;-)
