### ISSUE TITLE
rubydocs broken

### ISSUE THREAD

**Issue by kholbekj** [refinery/refinerycms#3184]
http://www.rubydoc.info/github/refinery/refinerycms is broken.

Some quick googlefoo suggests this could happen if a file has a whitespace in it's name, but I'm not sure how to search github for that.

**Comment by kholbekj** [comment]
So I've found the problem, which is 
`images/spec/support/shared\ contexts/`
`images/spec/support/shared\ examples/`

Running yard server with underscore instead of spaces fixes the issue. Not sure about side effects though.

**Comment by bricesanchez** [comment]
Nice catch! Thanks!
It has no side on the specs.

I've created a PR and i hope it will fix our problem on rubydocs : #3185

**Comment by parndt** [comment]
@kholbekj thank you very much!
