### ISSUE TITLE
Plugins not being hidden when disabled for user

### ISSUE THREAD

**Issue by Znow** [refinery/refinerycms#3186]
Hi

I've pulled down a brand new Refinery installation.

All though, if I disable i.e. the "Files" plugin for my user, it wont get hidden in the menu.

![image](https://cloud.githubusercontent.com/assets/265719/15535344/2afd4f02-226d-11e6-89f8-2af4acad450e.png)

**Comment by bricesanchez** [comment]
Are you the first user on this installation? If yes you're may have the :superuser role which has all rights even if plugins are disable.

**Comment by Znow** [comment]
Hi, i am, all though in another installation, an old project which has been upgraded to latest Refinery, has the same problem.

Kind regards

**Comment by bricesanchez** [comment]
Ok. 

So it will be nice to have something like a message when the user is superadmin.

Perhaps we should expose the Role feature in admin views

**Comment by bsodmike** [comment]
In past projects those non-user accessible tabs are disabled via CSS, by inferring the user's roles.

**Comment by bricesanchez** [comment]
@bsodmike i'm not sure to understand. 
A plugin tab should be disabled if you have `:admin` role and you don't have access to this plugin tab. right?

**Comment by bsodmike** [comment]
Hi @bricesanchez, sorry, ignore my previous comment.  I have double checked this against an edge install of Refinery and it's fine.

> So it will be nice to have something like a message when the user is superadmin.
> Perhaps we should expose the Role feature in admin views.

Agreed, and it would make sense that only Superadmins can modify roles as well?

**Comment by bsodmike** [comment]
Deja vu, I believe this functionality is already there by enabling `config.superuser_can_assign_roles`.

```
# refinerycms-authentication-devise
app/views/refinery/authentication/devise/admin/users/_form.html.erb
57:  <% if current_refinery_user.has_role?(:superuser) && Refinery::Authentication::Devise.superuser_can_assign_roles %>
```
