### ISSUE TITLE
Separate Images collection

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3188]
Is it possible to make a sort of private images collection for custom extension? The images, uploaded and attached to any item of this extension will not be visible in common "Images" tab. 
As I can assume from reading the source code, now the Refinery::Images does not give the possibility to make any categorization, and so if I want to create custom extension ability to attach multiple images, which I don\`t want to be visible in Images tab, I have either to hardly modify the Refinery::Images, or to create brand new model to keep the included files (something like Attachment, with its own dragonfly `dragonfly_accessor `, settings and controller actions for managing the uploaded files). Am I right?

**Comment by bricesanchez** [comment]
I've developed an extension for resources categorization : https://github.com/bisscomm/refinerycms-resource-categories

It needs specs.
It could be adapted to images.

**Comment by anitagraham** [comment]
I have an extension which has two separate sets of images (photos, drawings). They're not part of the images collection.

Yes, you're right with your ideas. Sounds like I should get back to work on a Dragonfly extension that any extension (including images) can use.
