### ISSUE TITLE
Need to be fixed

### ISSUE THREAD

**Issue by PsevdoNeferet** [refinery/refinerycms#3191]
Doesn't work correctly some options - such as adding links and images. Adding script in html text in admin version also doesn't work. Tho' it all perfectly works on older version of Refinery CMS

**Comment by bricesanchez** [comment]
We needs more informations to be able to fix the problem such as :

* Could you copy/paste your Gemfile.lock ?
* Do you have a step by step to reproduce?
* Do you have an error stracktrace to share?
* Do you have screenshots?

Thanks!

**Comment by PsevdoNeferet** [comment]
Hello,
The problem occures when I'm trying to add images or links in backend part of my web-site. I use default tools of RefineryCMS - click on image's icon on pages' editor, but a form for downloading pictures doesn't open (see attached screenshots).

As for using script-tag in my html-text - the problem has solved - I've just forgotten to add whitelist elements to project's config.
Thanks Вторник,  7 июня 2016, 14:12 +03:00 от Brice Sanchez <notifications@github.com>:
>
>We needs more informations to be able to fix the problem such as :
>*  Could you copy/paste your Gemfile.lock ?
>*  Do you have a step by step to reproduce?
>*  Do you have an error stracktrace to share?
>*  Do you have screenshots?
>Thanks!
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Наталья Саломатина

**Comment by bricesanchez** [comment]
@PsevdoNeferet i don't see attached pictures, sorry. Did you try a latest version of `refinerycms-wymeditor` ?

**Comment by PsevdoNeferet** [comment]
refinerycms-wymeditor (1.0.6) - is it a latest version?

**Comment by PsevdoNeferet** [comment]
Screenshots are there
![screenshot1](https://cloud.githubusercontent.com/assets/19793181/16265614/f1be6884-3888-11e6-89b2-517ff12418a9.png)
![screenshot2](https://cloud.githubusercontent.com/assets/19793181/16265615/f1c0a9b4-3888-11e6-9579-02c9bc345d92.png)

**Comment by bricesanchez** [comment]
The latest version of `refinerycms-wymeditor` is 1.0.7 since yesterday.

I've stated a new dummy app and images tab is ok for me.

Could you use the `3-0-stable` branch instead of `master` branch ?

Do you have any error in the browser console?

**Comment by PsevdoNeferet** [comment]
Ok, thanks)
No, there are no any error messages

2016-06-22 18:41 GMT+04:00 Brice Sanchez <notifications@github.com>:

**Comment by bricesanchez** [comment]
Is you error solved ? 

Did you try with another browser ?

**Comment by PsevdoNeferet** [comment]
yes, thanks

2016-06-23 17:28 GMT+04:00 Brice Sanchez <notifications@github.com>:

**Comment by bricesanchez** [comment]
Which solution helped you?

**Comment by PsevdoNeferet** [comment]
The latest version of refinerycms-wymeditor works perfectly

**Comment by bricesanchez** [comment]
Thanks for the feedback :)
