### ISSUE TITLE
Exporting existing uploaded images in Refinery to Amazon S3

### ISSUE THREAD

**Issue by Znow** [refinery/refinerycms#3194]
I have an existing Rails RefineryCMS application, which have been running for quite some time. It has alot of image and document uploads, which always have been uploaded to the local filesystem.

But we are moving to Heroku, then this will be a problem, since Heroku doesn't persist these files.

So, we need to get all the existing images and document exported to a Amazon S3.

How could we achieve this?

Would it be plain simple as just copying over the existing files from the current production environment to the S3 bucket?

Kind regards

**Comment by bricesanchez** [comment]
I've never do that before but i think we could copy images from local server to Amazon S3 bucket and set up Amazon S3 credentials on your app. 

It should work, let me know!
I will probably rewrite Heroku/Amazon S3 guides soon :)

**Comment by stefanspicer** [comment]
I've done this before.  I've never had any issues.  You should be fine @Znow

**Comment by Znow** [comment]
@bricesanchez @stefanspicer Thanks alot, I'll try it out tomorrow or sometime and let you now if I fail ;)
