### ISSUE TITLE
Page translations seeds problem

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3197]
Looks like the seeds.rb has issue with generation page translations for different frontend_locales (https://github.com/refinery/refinerycms/blob/master/pages/db/seeds.rb#L47)
After launching db:seed I still have three default pages with only one 'en' locale in `page_translations` table, however I even do not have this locale in `frontend_locales` option
Here is my i18n.rb:

``` ruby
Refinery::I18n.configure do |config|
  config.default_locale = :ru

  config.current_locale = :ru

  config.default_frontend_locale = :ru

  config.frontend_locales = [:ru]

  config.locales = {:ru => 'Русский'}
end
```

Meanwhile other refinery extensions, like refinerycms-blog, successfully creates its page translation with 'ru' locale, but I didn`t test if it will create multiple page_translations if I will set something like `config.frontend_locales = [:ru, :en]`

**Comment by parndt** [comment]
@sintro did you first clear your database?

```
$ rake db:drop
$ rake db:create
$ rake db:migrate
$ rake db:seed
```

**Comment by bricesanchez** [comment]
@sintro Is your problem fixed?

**Comment by sintro** [comment]
Honestly, forgot about this issue, but as I can remember, that didn\`t solve the problem.
