### ISSUE TITLE
Select tag with multiple option failed

### ISSUE THREAD

**Issue by AlbaHoo** [refinery/refinerycms#3206]
Hi there, 
 
I have select tag in the content_for Body,

When i add multiple attribute into select tag and save the page, "multiple" is disappeared, how can i add multiple attrubute?

**Comment by bricesanchez** [comment]
Hello @AlbaHoo,

What happens if you add this?

```ruby
# config/initializers/refinery/pages.rb
  # You can add new HTML attributes not already supported by Loofah::HTML5::WhiteList::ALLOWED_ATTRIBUTES
  # For more information on whitelist see ALLOWED_ATTRIBUTES 
  # (https://github.com/flavorjones/loofah/blob/v2.0.3/lib/loofah/html5/whitelist.rb#L152)
  # config.add_whitelist_attributes = ["kind", "srclang", "placeholder", "controls", "multiple"]
```

See: https://github.com/refinery/refinerycms/blob/master/pages/lib/generators/refinery/pages/templates/config/initializers/refinery/pages.rb.erb#L74-L77

**Comment by AlbaHoo** [comment]
Thanks so much. @bricesanchez

**Comment by bricesanchez** [comment]
You're welcome! I will add it in the default config
