### ISSUE TITLE
Sitemap multilanguage problem

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3215]
There are problem with sitemap generation when multiple locales are enabled.
The problem is in two places:
**1.**
https://github.com/refinery/refinerycms/blob/master/core/app/views/refinery/sitemap/index.xml.builder#L11
When this `page_url` (prepared as Hash) goes to `refinery.url_for(page_url)`, it has `locale` key with locale, set in my browser (which is always will be `:ru`), and when the `RouteFilter` tries to generate url for current ::I18n.locale, it uses **exactly** params[:locale] (look here https://github.com/refinery/refinerycms-i18n/blob/master/lib/refinery/i18n-filter.rb#L23). Probably, when sitemap.xml is called by search bots, there will be no :locale key in params, but I am not sure. The possible solution can be using modified line:
```
page.url.merge({:only_path => false, locale: locale})
```
This way, url_for will get modified params[:locale], as it is currently set buy `@locales.each do |locale|` loop. And the line`::I18n.locale = locale` can be removed.
**2.**
More serious problem takes place when the url_for gets **String** as `page_url`, which happens when the page with redirection is precessing (or even root page of site). In this case, the module `RoutingFilter::RefineryLocales` is not fired at all, so for all the locales in @locales array there will be absolutely identical urls. I don`t know how to solve this problem best, but there is at least stupid way to duplicate some code from here https://github.com/refinery/refinerycms-i18n/blob/master/lib/refinery/i18n-filter.rb#L30 to here https://github.com/refinery/refinerycms/blob/master/core/app/views/refinery/sitemap/index.xml.builder#L14, and this is obviously ugly solution. Any suggestions?

**Comment by sintro** [comment]
I just solved the problem with less duplications, but I think it is still not the best solution. All changes I did in `sitemap\index.xml.builder`, here is how it looks now:
```
xml.instruct!

xml.urlset "xmlns" => "http://www.sitemaps.org/schemas/sitemap/0.9" do

  @locales.each do |locale|
    ::I18n.locale = locale
    ::Refinery::Page.live.in_menu.includes(:parts).each do |page|
     # exclude sites that are external to our own domain.
     page_url = if page.url.is_a?(Hash)
       # This is how most pages work without being overriden by link_url
       page.url.merge({:only_path => false, locale: locale})
     elsif page.url.to_s !~ /^http/
       # handle relative link_url 09addresses.
       raw_url = [request.protocol, request.host_with_port, page.url].join
       filter = RoutingFilter::RefineryLocales.new
       filter.around_generate({}) do
         raw_url
       end
     end

     # Add XML entry only if there is a valid page_url found above.
     xml.url do
       xml.loc refinery.url_for(page_url)
       xml.lastmod page.updated_at.to_date
     end if page_url.present? and page.show_in_menu?
    end
  end

end
```

**Comment by bricesanchez** [comment]
Could you provide us a PR ? we will be able to see the changes and try to improve it.

**Comment by sintro** [comment]
Sure, will do it today
