### ISSUE TITLE
Rethinking of templates system

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3221]
Hello!
The step towards release of 4.0.0 was made, and I want bring up for discussion the problem of 'page types' in particular and whole page templates system in common.
Firstly, there is still broken functionality of page types in refinerycms, which is discussed already here https://github.com/refinery/refinerycms/issues/3152 with some suggestions on how to fix and improve it. 
The main idea in that suggestions is to give admin the possibility to make the pages of some type, which will just create the common page with preset number of page_parts and also automatically choose correct page template.
The truth, in my opinion, is that there are always a significant number of page templates will be listed in common select_box (in advanced zone of page creation menu), which will never be used more than in one page. The example is "Contacts" page with custom template (located in views/refinery/pages) and needed page parts "Address", "Phone", "Email", "placeId" (to output Google Map), and this template is hardly dependent on specific page parts, and without the possibility described in https://github.com/refinery/refinerycms/issues/3152 no admin or editor can recreate the contacts page after accidental deleting it (just because without looking at source code of web-application he can not know how to name needed page_part with address, phone and email).
Thus, looks like there are two types of page templates: which can be picked by admin, and which can be created only by special menu (like here https://github.com/refinery/refinerycms/issues/3152). We can easily hide special templates (like Contacts) from select_box, leaving there only page templates, which can be really used by editors to create common pages (with some differents in design). And the "Special templates" will be listed only in common admin pages menu as "Create with template" button, and the pages, created by this button, will not have the ability to change its template (because there is many specific page parts). 
1. If you think that this idea makes sense, the main tasks are:
2. Modifying the current templates listing system
3. Creating the mechanism of marking templates as "Public" or "Special" (probably, some array in initializers/pages.rb)
4. Creating the handy "Special" pages creation menu. It can be shown, for example, like this:
![Templates select menu](http://picplus.ru/img/1607/18/05b9a838.jpg)

**Comment by stefanspicer** [comment]
@sintro I hear you, I think this is definitely an issue, and we've actually taken a stab at solving this as apart of refinery glass.  I'm interested to know what you think.  It follows the assumption (that we've found to be true) that most admins don't need to be able to create these "Special" pages so having some interface (a dropdown) for them will only be confusing.  We went back to a sort of page template whitelist (similar to a feature that was removed from refinery).  For example, I would configure ['basic-page', 'landing-page'] and then non-superusers would only see those 2 in the page template dropdown.  For only one option I just use a hidden field instead.

I think this is a simple approach that would accomplish what you're looking for, yes?

**Comment by bricesanchez** [comment]
My biggest concern is on page template update.

When i create a page "A" and i assign the template "A" with 2 page parts (`:body` and `:side_body`) and then i want to assign the template "B" with 2 other page parts (`:body`, `:custom_side_body`).

What happens to `:side_body`? Is it hidden? Is it deleted?
Is `:custom_side_body` automatically created or is it created after a confirm dialog (in the case, i choose the wrong template)?

For my experience, my devs create page and page parts and the webmaster never add or change pages configuration so i don't know if this feature is useful.
