### ISSUE TITLE
InvalidAuthenticityToken for sending form

### ISSUE THREAD

**Issue by kreker92** [refinery/refinerycms#3225]
I have page with form. In old version I could insert ruby var with authenticity code. Can I somehow insert code before showing code. 
I have only idea to insert it by JS but it's not good idea

Edit config config.authenticity_token_on_frontend in core.rb doesn't help.

**Comment by bricesanchez** [comment]
Did you found a solution?

**Comment by kreker92** [comment]
Just like that:
var forms = $('form');
    if(forms.length == 0) return;

    var authToken = $('meta[name="authenticity_token"]').attr('content');
    forms.each(function() {
        $(this).find('input[type="submit"]').parent().append('<input type="hidden" name="authenticity_token" value="'+ authToken +'" />');
    });

**Comment by kreker92** [comment]
Just like that:
```
var forms = $('form');
if(forms.length == 0) return;

var authToken = $('meta[name="authenticity_token"]').attr('content');
forms.each(function() {
    $(this).find('input[type="submit"]').parent().append('<input type="hidden" name="authenticity_token" value="'+ authToken +'" />');
});
```

**Comment by bricesanchez** [comment]
Thanks for your answer!
