### ISSUE TITLE
Required attribute should be whitelisted by default?

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3226]
How about adding the `required` attribute (HTML5 form validation) to whitelist by default here? 
https://github.com/refinery/refinerycms/blob/c793da02180489f44f491804fe61ebfd7c127f58/pages/lib/refinery/pages/configuration.rb#L27

**Comment by bricesanchez** [comment]
As i see it's not in the Loofah list: https://github.com/flavorjones/loofah/blob/v2.0.3/lib/loofah/html5/whitelist.rb#L152

So we could add it in the `self.add_whitelist_attributes` if it sanitized.

**Comment by bricesanchez** [comment]
Closed in favor of #3236
