### ISSUE TITLE
Cant generate anything

### ISSUE THREAD

**Issue by kreker92** [refinery/refinerycms#3227]
I've generate  new project and install some refinery gems.
I've already ended my project but I couldn't authenticate my form on page.
So I've found refinery-fomrs gema and install it.
Then I need to generate my form and it doesnt answer. It just wait something.
I've tried to generate controller and it has the same result.
Like:
`user@server:~/site$ rails g controller Qwe a:integer`

Gemfile:
```
# Refinery CMS
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'bugfix/allow-data-attr-3-0-rebase'
gem 'refinerycms-i18n'

# Optionally, specify additional Refinery CMS Extensions here:
gem 'refinerycms-acts-as-indexed', ['~> 3.0', '>= 2.0.1']
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-authentication-devise', '~> 1.0'
gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'master'
gem 'refinerycms-search', github: 'refinery/refinerycms-search', branch: 'master'
gem 'refinerycms-page-images', '~> 3.0.0', github: "refinery/refinerycms-page-images", branch: "master"
gem 'refinerycms-forms', github: 'refinery/refinerycms-forms', branch: 'master', group: :development

```

**Comment by bricesanchez** [comment]
'bugfix/allow-data-attr-3-0-rebase' branch has been merged into `3-0-stable`. Please use this now :

```ruby
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: '3-0-stable'
```

**Comment by kreker92** [comment]
Thanks! But It still has the same effect

**Comment by bricesanchez** [comment]
Did you tried to generate another project to see if the problem is your internet connection, ruby environment or the project himself?

**Comment by kreker92** [comment]
I had the same when tries to install refinery the first time.
After problems with wymeditor I've create new clean project and now it has the same problem with generating.
So I need to try again and find the step when generation breaks.

**Comment by bricesanchez** [comment]
Could you copy/paste the command you are using?

**Comment by kreker92** [comment]
I've inited app in git.
Then clone into the new dir and it starts to generate
Generate code was: rails generate refinery:form callback name:string email:string site_url:string phone:string comment:text --authors 'Author'
