### ISSUE TITLE
Uncaught TypeError: undefined is not a function - init_sortable_menu

### ISSUE THREAD

**Issue by sajjadmurtaza** [refinery/refinerycms#3228]
I'm using `gem 'refinerycms', '~> 2.0.0'` `ruby '2.2.3' and gem 'rails', '3.2.22'`
But when i edit any page then i'm facing follwing issue. Can someone guide me what will be the issue?

> Uncaught TypeError: undefined is not a function

>init_sortable_menu
> init_refinery_admin
> jQuery.Callbacks.fire
> jQuery.Callbacks.self.fireWith refinery.js:436  jQuery.extend.readyrefinery.js:950 DOMContentLoaded

**Comment by sajjadmurtaza** [comment]
@bricesanchez - anyone start work on it?

**Comment by bricesanchez** [comment]
@sajjadmurtaza No sorry, 2.0 branch is deprecated. We concentrate our efforts on 3.1 and 4.0 version. You should try to upgrade to 2.1.5 version and see if it fix your problem. If not, you will have to dig into the problem and try to find a solution, we will accept a pull request for this version.

**Comment by sajjadmurtaza** [comment]
I have resolved by changing jquery-ui version with 1.10.3 .
