### ISSUE TITLE
Need documentation update

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3231]
There is a problem now, caused by updating the 'master' branch to refinery 4.0.0.dev.
When you are trying to install fresh refinery template project, using the line from github's readme (`rails new app_name -m http://refinerycms.com/t/edge`), you will get a bunch of errors, because almost all of dependencies are not compatible with 4.0.0.dev version of refinerycms.
Further initialization of project fails, and you need to correct Gemfile (gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', **branch: '3-0-stable'**, not 'master'), then launch `rails generate refinery:cms --fresh-installation` command to finish the process.

**Comment by bricesanchez** [comment]
#3238 should fix this issue. Thanks for this report and a special thanks to you for your "global" review of this project!
