### ISSUE TITLE
Duplication of admin menu items (autoloading problem, probably)

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms#3232]
There common problem happens in my work with refinerycms, when I make some changes in source code (mostly - in some extension's code), I am getting this in admin's panel:
<img width="155" alt="2016-07-24 23 52 58" src="https://cloud.githubusercontent.com/assets/1379593/17087321/57abcdd2-5218-11e6-9e44-4474e91b4d94.png">
Almost all the items are duplicated (sometimes x3, x4 and more). There is no such problem in production, and this problem disappears after restarting the development server, but it is still quite annoying bug. Does anyone have any suggestions why this can happens?

**Comment by bricesanchez** [comment]
Thanks for the report, it's a known bug but it's not fixed: #3087
