### ISSUE TITLE
undefined method `action' for Refinery::Admin::BaseController:Module

### ISSUE THREAD

**Issue by sajjadmurtaza** [refinery/refinerycms#3241]
I'm unable to delete, when i'm clicking on delete link - i'm facing following error

> NoMethodError in Refinery::Admin::BaseController#error_404

> undefined method `action' for Refinery::Admin::BaseController:Module

**Comment by bricesanchez** [comment]
Hello,

We need more informations to be able to fix the problem such as :
*  Could you copy/paste your Gemfile.lock ?
*  Do you have a step by step to reproduce?
*  Do you have an error stracktrace to share?
*  Do you have screenshots?

Thanks!

**Comment by sajjadmurtaza** [comment]
Please look at screenshots.

> NoMethodError (undefined method `action' for Refinery::Admin::BaseController:Module):

![error_1](https://cloud.githubusercontent.com/assets/8552702/18301140/a6f6c930-74e8-11e6-9ef4-1c10e7a51518.png)
![error_2](https://cloud.githubusercontent.com/assets/8552702/18301139/a6f5c4fe-74e8-11e6-95c4-b9f6341f8e67.png)

**Comment by bricesanchez** [comment]
Hello! Could you update refinerycms to at least 2.1.5 ?

**Comment by sajjadmurtaza** [comment]
I have tried but I'm facing too much issue  because there is many extension extend from engine.

**Comment by parndt** [comment]
Could you update to the latest 2.0.x version?

**Comment by sajjadmurtaza** [comment]
@parndt  Thanks for your response. But my issue is that when i'm updating refinery_cms, after update the extensions are not updating because they are using previous refiery_cms version. For example `gem 'refinerycms', '~> 2.0.10'` updated from 2.0.0.

After that i want to update refinerycms-core.
 `gem 'refinerycms-core', '~> 2.0.10', :path => 'vendor/engines'`

> Could not find gem 'refinerycms-core (~> 2.0.10)' in source at `vendor/engines`.
Source contains 'refinerycms-core' at: 2.0.8 ruby

**Comment by parndt** [comment]
why do you have `refinerycms-core` in `vendor/engines`?

**Comment by sajjadmurtaza** [comment]
The is refinerycms-core a example, i have also `gem 'refinerycms-titans', :path => 'vendor/extensions'` and other own custom extensions.

**Comment by zeeshanshafiq** [comment]
Add  "//= require jquery_ujs"  to load file for ajax request. Add this to your admin.js file or include in file you are loading under layout.
