### ISSUE TITLE
Pretty-Urls support for chinese Pinyin

### ISSUE THREAD

**Issue by oolzpishere** [refinery/refinerycms#3243]
Hi, I need to change friendly_id support for Chinese Pinyin. 
I use this chinese_pinyin gem. 
Then I create page_decorator model to override method normalize_friendly_id. 
But after that, I will lose some method inside FriendlyIdPath class.
```
Refinery::Page.class_eval do
  def normalize_friendly_id(value)
      Pinyin.t(value.to_s).parameterize
  end
end
```

**Comment by bricesanchez** [comment]
Hello,

i don't think you should "change `friendly_id` support for `chinese_pinyin`" but you should check if `friendly_id` could translate chinese hanzi to pinyin or better extend `friendly_id` capabilities to support chinese_pinyin. It's more a job to do in Friendly ID not in Refinery.

Any thoughts @parndt ?

**Comment by oolzpishere** [comment]
@bricesanchez 
Thank you Brice. 
I will do more reserch about friendly_id.

**Comment by bricesanchez** [comment]
You're welcome!
