### ISSUE TITLE
Unable to access refinery backend pages 

### ISSUE THREAD

**Issue by ITDevMohsin** [refinery/refinerycms#3246]
Hi,

**My issue is:**

If I logged in using my refinery login, and I try to visit: `http://localhost:3000/refinery/pages` pages section that is under refinery it says:

```
No route matches {:action=>"show", :controller=>"refinery/pages", :id=>nil, :locale=>:en, :path=>["home", "page-not-found"]}
Extracted source (around line #46):              
        message << " missing required keys: #{missing_keys.sort.inspect}" unless missing_keys.empty?

        raise ActionController::UrlGenerationError, message
      end

```

Could anyone please have a look into this matter.

Thanks,

**Comment by ITDevMohsin** [comment]
@bricesanchez Sir, could you please look into this matter please?

Thank you.

**Comment by ITDevMohsin** [comment]
@parndt @bricesanchez 

Any update guys? Please?

Thanks.!

**Comment by parndt** [comment]
The code you've posted isn't contained in Refinery anywhere that I can find:
```
No route matches {:action=>"show", :controller=>"refinery/pages", :id=>nil, :locale=>:en, :path=>["home", "page-not-found"]}
Extracted source (around line #46):              
        message << " missing required keys: #{missing_keys.sort.inspect}" unless missing_keys.empty?

        raise ActionController::UrlGenerationError, message
      end
```

How can we reproduce this using a default installation of Refinery?

**Comment by ITDevMohsin** [comment]
Let me explain you.

When I try to visit: `http://localhost:3000/refinery/pages`, it returns me ambigous error like below:

And the line in which error is coming:

file is: `refinery/admin/pages/_page.html.erb`

 <span class='actions'>
      <%= action_icon(:preview, page.url,   t('.view_live_html')) %>
      <%= action_icon(:add,     add_url,    t('new',    scope: 'refinery.admin.pages' ) ) %>
      <%= action_icon(:edit,    edit_url ,  t('edit',   scope: 'refinery.admin.pages' ) ) %>
      <%= action_icon(:delete,  delete_url, t('delete', scope: 'refinery.admin.pages' ), delete_options ) if page.deletable? %>
    </span>

error is in this line: `<%= action_icon(:preview, page.url,   t('.view_live_html')) %>`

If I add comment to this line, the page renders smoothly.

But I need to add preview links as well that will take admin to front end page url that he will created in backend (normal behavior)

![test](https://cloud.githubusercontent.com/assets/21135288/18532043/f8a7ca94-7af2-11e6-93af-bd7504752870.png)

So, the problem here is that, I just did everything as normally everyone does that but I am having this issue with no reason. 

My GEM File:

```
source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', '~> 3.4.0'
gem 'puma'
gem 'rails_12factor', group: :production
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'fog-aws'
gem 'mini_magick'

gem 'refinerycms'
gem 'refinerycms-authentication-devise', '~> 1.0.4'
gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'faker'

gem 'make_resourceful'
gem 'rubocop', '~> 0.42.0'

group :development, :test do
  gem 'pry'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

```

routes file:

```
Rails.application.routes.draw do
  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
  Refinery::Core::Engine.routes.prepend do
  end
end
```

**Comment by ITDevMohsin** [comment]
@parndt 

Basically, I am not able to understand what exactly is missing in terms of pages and why it seems broken ever.

The output you are referring to is from the code that is not outputting the preview links url so admin can access them to view page links by clicking from pages in backend.

**Comment by bricesanchez** [comment]
@ITDevMohsin is it fixed ?

**Comment by ITDevMohsin** [comment]
@bricesanchez Yes, I somehow managed to fix it myself without waiting for extensive long delays in replies. 

Thanks anyways.

**Comment by parndt** [comment]
@ITDevMohsin I'm glad that you managed to fix your issue by yourself, but I wanted to point out that everyone working on this project is doing so as a volunteer, without compensation, and in any time available to them outside of their normal work and family life requirements.  So there's no real need for unconstructive comments like the implication we weren't able to be attentive enough ☹️, it just makes people less willing to offer their help for free in future.

**Comment by ITDevMohsin** [comment]
@parndt Well, I really appreciate your efforts in maintaining this CMS system and doing that without compensation really means a lot to me as well as I was also part of volunteer job long time ago. I really found you guys so helpful but thing is that we cant put our client on hold when they invest major stack of budget on the product that actually you guys are maintaining. 

Thanks much for all your replies so far. Really matter a lot to me. :)

**Comment by simi** [comment]
@ITDevMohsin if you need professional support, I think some maintainers will be available as paid contractors.

*@parndt is there any donate program?*

**Comment by ITDevMohsin** [comment]
@simi Thank you, I am willing to pay if there are any paid contractors who can assist routine issues easily. If you do know, please let me know, I will be obliged.

Also if there are any donate program options too, I can denote and will appreciate the support as well.

Thanks!!

**Comment by parndt** [comment]
@simi maybe we could set up something like https://opencollective.com?
