### ISSUE TITLE
ActiveRecord::UnknownPrimaryKey (Unknown primary key for table refinery_users in model Refinery::User.):

### ISSUE THREAD

**Issue by sajjadmurtaza** [refinery/refinerycms#3247]
Hello refinerycms team!

Suddenly I'm facing ActiveRecord::UnknownPrimaryKey (Unknown primary key for table refinery_users in model Refinery::User.): error after updating Gemfile.

> ActiveRecord::UnknownPrimaryKey (Unknown primary key for table refinery_users in model Refinery::User.):
>  vendor/cache/ruby/2.1.0/gems/activerecord-3.2.13/lib/active_record/reflection.rb:366:in `primary_key'
>  vendor/cache/ruby/2.1.0/gems/activerecord-3.2.13/lib/active_record/reflection.rb:216:in`association_primary_key'
>  vendor/cache/ruby/2.1.0/gems/activerecord->3.2.13/lib/active_record/associations/association_scope.rb:47:in `block in add_constraints'
>   vendor/cache/ruby/2.1.0/gems/activerecord->3.2.13/lib/active_record/associations/association_scope.rb:39:in`each'

**Comment by parndt** [comment]
Please try updating to the latest patch release e.g. in your situation based on #3241 this would be `2.0.10`

**Comment by bricesanchez** [comment]
@sajjadmurtaza Is it fixed for you ?

**Comment by sajjadmurtaza** [comment]
Yes - Thanks
