### ISSUE TITLE
Uncaught ReferenceError: init_interface is not defined admin.js

### ISSUE THREAD

**Issue by dasibre** [refinery/refinerycms#3248]
Switching between site view and admin view, admin view layout is broken. Navigation panel disappears, in order to fix, i have to refresh page.

inspecting page, console shows

Uncaught ReferenceError: init_interface is not defined admin.js

init_refinery_admin = function(){
  **init_interface();**
  init_flash_messages();
  init_submit_continue();
  init_modal_dialogs();
  init_tooltips();
  init_ajaxy_pagination();

Uncaught ReferenceError: onOpenDialog is not defined

dialogFeatures: {
      width: 866
    , height: 455
    , modal: true
    , draggable: true
    , resizable: false
    , autoOpen: true
    , **open: onOpenDialog**
    , close: onCloseDialog

My ruby version 2.2.5

My gems 

gem 'rails', '4.2.6'
# Refinery CMS

gem 'refinerycms', '~> 3.0'
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.1']
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-authentication-devise', '~> 1.0'
 gem 'refinerycms-inquiries', ['~> 3.0', '>= 3.0.0']

**Comment by bricesanchez** [comment]
Are you able to reproduce this error on a new "vanilla" refinery website?

**Comment by bricesanchez** [comment]
Is it fixed for you?

**Comment by bricesanchez** [comment]
Fixed by #3269
