### ISSUE TITLE
Turbolinks 5 uses different data attributes

### ISSUE THREAD

**Issue by veger** [refinery/refinerycms#3268]
When switching from Refinery to my website, Javascripts are not properly loaded/activated.

After some investigation at the [turbolinks 5 documentation](https://github.com/turbolinks/turbolinks#disabling-turbolinks-on-specific-links), the data attribute to disable turbolinks is `data-turbolinks`, whereas refinery uses `data-no-turbolink`

Using a decorator to override `Refinery::SiteBarHelper.site_bar_switch_link` fixes the issue.

I am willing to create a PR (assuming turbolinks 5 is (going to be) supported), but I do not know how to [test](https://github.com/refinery/refinerycms/blob/master/contributing.md#making-a-pull-request) this...

**Comment by bricesanchez** [comment]
I can confirm this issue and you can provide a pull request. I don't know to test this too but perhaps @parndt yes?

**Comment by bricesanchez** [comment]
Thanks @veger!
