### ISSUE TITLE
NoMethodError: undefined method `slug' for #<Refinery::PagePart:0x4552230>

### ISSUE THREAD

**Issue by john-carmona-plgic** [refinery/refinerycms#3274]
I am having problem with `rake db:seed`.

**Error Trace**

    rake aborted!
    NoMethodError: undefined method `slug' for #<Refinery::PagePart:0x4552230>
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/refinerycms-pages-3.0.5/app/models/refinery/page_part.rb:54:in `set_default_slug'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:162:in `block in halting'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `block in call'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `each'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations.rb:334:in `valid?'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:58:in `valid?'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:83:in `perform_validations'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:37:in `save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:21:in `save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:286:in `block in save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:285:in `save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/globalize-5.0.1/lib/globalize/active_record/instance_methods.rb:152:in `block in save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/globalize-5.0.1/lib/globalize.rb:26:in `with_locale'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/globalize-5.0.1/lib/globalize/active_record/instance_methods.rb:151:in `save'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/has_many_association.rb:41:in `insert_record'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:501:in `block (2 levels) in _create_record'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:408:in `replace_on_target'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:403:in `add_to_target'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:499:in `block in _create_record'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:183:in `block in transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:182:in `transaction'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:498:in `_create_record'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/has_many_association.rb:180:in `_create_record'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:153:in `create'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/collection_proxy.rb:290:in `create'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/refinerycms-pages-3.0.5/db/seeds.rb:8:in `<top (required)>'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
    E:/ruby/paramountwebsite/db/seeds.rb:3:in `<top (required)>'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
    C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
    C:/RailsInstaller/Ruby2.3.0/bin/rake:22:in `load'
    C:/RailsInstaller/Ruby2.3.0/bin/rake:22:in `<main>'
    Tasks: TOP => db:seed

**seeds.rb**

    Refinery::Pages::Engine.load_seed

**Gemfile**

    source 'https://rubygems.org'

    gem 'tzinfo-data'
    gem "nokogiri", ">= 1.6.7.rc"

    gem 'refinerycms-i18n'
    gem 'refinerycms'
    gem 'refinerycms-wymeditor'
    gem 'refinerycms-authentication-devise'
    gem 'refinerycms-settings'
    gem 'yaml_db'
    gem 'httparty'
    gem 'cloudinary'

    gem 'rails', '4.2.3'
    
    group :development, :test do
      gem 'pg'
    end

    group :production do
      gem 'pg'
      gem 'rails_12factor'
      gem 'puma'
      gem 'dragonfly-s3_data_store'
    end

    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'

    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'
    gem 'sdoc', '~> 0.4.0', group: :doc

    group :development, :test do
      gem 'byebug'
      gem 'web-console', '~> 2.0'
      gem 'spring'
    end

    group :production do
        gem 'fog-aws'	
    end

**Ruby Version:** `ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]`
**Rails Version:** `Rails 4.2.3`

**Comment by bricesanchez** [comment]
I can't reproduce your error. Did you solve it?

**Comment by bricesanchez** [comment]
Closed due to inactivity and not able to reproduce

**Comment by hnnsgstfssn** [comment]
Got this after an upgrade but 
```
rake refinery_pages:install:migrations db:migrate
```
fixed it for me.

I recon running `rake refinery_pages:install:migrations` before seeding should work.
