### ISSUE TITLE
Rails 5 support - is there a plan for it? -> YES

### ISSUE THREAD

**Issue by thebravoman** [refinery/refinerycms#3277]
For a fews days I've been trying to migrate to rails 5 and because of refinerycms it was quite difficult. 

We have at least these three issues - 
https://github.com/refinery/refinerycms/issues/3178
https://github.com/refinery/refinerycms/issues/3257
https://github.com/refinery/refinerycms/issues/3280
For some of the issues I have workaround with patches and forks for my app.

I would like to kindly ask if you plan on a rails5 support and have you discussed any timeframe?

**Comment by yfractal** [comment]
refinerycms is really great, but it doesn't work well with rails 5 :(.

**Comment by thebravoman** [comment]
I just saw the branch for rails 5 and it says:

Updated 4 months ago by parndt 

I have a simple request - if you could please give us some information on your plans.

What I am about to do now is fork, remove everything that I do not need (which is about 70-80%) and used the forked version to keep my simple page editing working in rails 5. But this will work only for me and is not reasonable if you plan to have it.

Or if you give us some directions based on your plans for rails5 and why is it taking so long probably we could help with migrating parts of the code?

**Comment by bricesanchez** [comment]
Hi @thebravoman, Thanks for working on the Rails 5 port, i was busy on real-life projects so i didn't work on the port since November.

We could work together on it? 
Do you have a gitter account?

**Comment by thebravoman** [comment]
Yes I do have. Same username.

**Comment by digitalextremist** [comment]
@bricesanchez @thebravoman can we perhaps have a checklist posted at the very least:
- [ ] Just so we know.
- [ ] What is needed.

**Comment by thebravoman** [comment]
What kind of check list?

I would really like to have it working, but I lack the needed understanding
to single handedly migrate it.

 It is currently not working with rails 5 and after 3 days of debugging and
fixing a few months ago I just postponed it until we have the time to
remove refinery from our dependencies.

**Comment by digitalextremist** [comment]
Ah, that was my solution as well @thebravoman -- except at the start of the project, so it was easier.

**Comment by bricesanchez** [comment]
We made a great progress of the Rails 5 feature, you can test it here #3122

**Comment by bricesanchez** [comment]
Fixed with #3122
