### ISSUE TITLE
Adding the engine removes the csrf_token from the session in Rails 5 

### ISSUE THREAD

**Issue by thebravoman** [refinery/refinerycms#3280]
I have an app for rails 5.0.1
Without refinerycms the 
actionpack/lib/action_controller/metal/request_forgery_protection.rb is called with a session that contains the [:_csrf_token] in method

```
def real_csrf_token(session)
        session[:_csrf_token] ||= SecureRandom.base64(AUTHENTICITY_TOKEN_LENGTH)
        Base64.strict_decode64(session[:_csrf_token])
      end
```
But it we add refinery to the gemfile, to the config/routes and to the config/initializer than this same method in request_forgery_protection is called with session[:_csrf_token] equal to nil. So no authorization is possible

**Comment by thebravoman** [comment]
When the engine is present this gets called on a post request to the user sign in page.

>> ActionPack::Request::Session calling delegate method: []= with args: ["warden.user.user.key", [[1], "$2a$10$skyfdelGdUPubfLrbOY7Ju"]]
>> ActionPack::Request::Session calling delegate method: delete with args: ["_csrf_token"]

So something somewhere from the engine is deleting the _csrf_token.

**Comment by thebravoman** [comment]
I was looking at https://github.com/refinery/refinerycms-authentication-devise for ideas

but it results in the following.
```
Bundler could not find compatible versions for gem "friendly_id":
  In snapshot (Gemfile.lock):
    friendly_id (= 5.2.0)

  In Gemfile:
    friendly_id

    refinerycms-authentication-devise (~> 1.0.4) was resolved to 1.0.4, which depends on
      friendly_id (~> 5.1.0)

```

**Comment by bricesanchez** [comment]
Did you fixed your error?

**Comment by bricesanchez** [comment]
I close this issue due to inactivity and i'm not able to reproduce the error.
