### ISSUE TITLE
Full page cache invalidation/updates

### ISSUE THREAD

**Issue by nm-harry** [refinery/refinerycms#3282]
Using the [Full page cache docs](http://www.refinerycms.com/guides/full-page-cache-with-apache) I've configured Refinery (3.0.0) to create cached pages that are then served by nginx to speed web requests up a little, and take the load off the app. 

Nginx configuration similar to:
```
location / {
  root /srv/cms/public/refinery/cache/pages;
  try_files $uri.html @local;
  expires 60m;
}
```

I've tested updating pages in the CMS editor and the cached pages do not get cleared from the page cache in `public/refinery/cache/pages`. The only solution I can see is restarting refinery each time I update a page, which is not feasible, and appears at odds with being a CMS.

Is there something I'm missing from a Refinery version > 3.0.0 or anything I can do to change this behaviour?

**Comment by bricesanchez** [comment]
Did you find a solution?

**Comment by nm-harry** [comment]
@bricesanchez I ended up not using the Refinery caching and just using an nginx reverse caching proxy for all requests except admin pages. We don't get a huge amount of traffic, but it handles bursts well. I'd be happy to share an nginx config if that would be of use?

**Comment by bricesanchez** [comment]
@nm-harry it will be awesome!

**Comment by nm-harry** [comment]
@bricesanchez It's similar to this. I've removed some specific config info, and haven't included the general `nginx.conf`. This caches all requests for HTML but not the refinery admin pages, or POST requests. 

https://gist.github.com/nm-harry/d512599242ee849f542d7b60df0d65b0

**Comment by parndt** [comment]
It's supposed to be deleting the file upon a page update, perhaps it's silently failing?
