### ISSUE TITLE
Picture tag with webp/native fallback

### ISSUE THREAD

**Issue by rmfarrell** [refinery/refinerycms#3283]
I'm trying to serve high-performance images which serves webp images with a jpg fallback. something like this:

```
<picture>
  <source type='image/webp' srcset='
    /img/index/2000.webp 2000w,
    /img/index/1500.webp 1500w,
    /img/index/900.webp 900w,
    /img/index/450.webp 450w'>
  <img src='/img/index/900.jpg' srcset='
    /img/index/2000.jpg 2000w,
    /img/index/1500.jpg 1500w,
    /img/index/900.jpg 900w,
    /img/index/450.jpg 450w'
    alt='Alt text wow'>
</picture>
```

but it looks like output it being sanitized to remove the `<picture>` tags and `srcset` attributes. How can I fix this?

**Comment by parndt** [comment]
@bricesanchez ^

**Comment by bricesanchez** [comment]
Hi @rmfarrell, it looks like `picture` and `srcset` are not whitelisted. You could easily doing that by add them to the page config initializer : 

https://github.com/refinery/refinerycms/blob/master/pages/lib/generators/refinery/pages/templates/config/initializers/refinery/pages.rb.erb#L69-L77

**Comment by rmfarrell** [comment]
Thanks!
