### ISSUE TITLE
WMEditor not loading (backend admin Pages/Blog etc.)

### ISSUE THREAD

**Issue by ycrepeau** [refinery/refinerycms#3286]
I have some trouble (not always) with WMEditor when using the backend.

I strongly suspect this is due du Turbolinks. When the page loads, the

```javascript
$(document).ready(...)
```

event is not trigged. I assume WMEditor has setup some init methods that should be called when the page loads. So, at this point, I have created a coffescript file loaded when an admin-backend is used. It looks like this:

```coffeescript
setup = ->
  $(document).foundation();
  init_refinery_admin

$ ->
  console.log "Common_Admin Loading page...!  " + Date.now()%10000
  document.addEventListener "turbolinks:load", () ->
    console.log "Common_Admin turbolinks:load "  + Date.now()%10000
    setup();
```

It does the trick 99% of the time but from time to time I still have WYMEditor not loading and error messages in the console (WYMEditor undefined).

Any suggestion?

**Comment by bricesanchez** [comment]
Did you find a solution?

**Comment by ycrepeau** [comment]
I have put a solution in my original message. Simply calling a custom setup() method with both page.ready ($->) and turbolinks:load events. 

In the setup() method, I call init_refinery_admin (which is a method RefineryCMS gem provides). 

The issue is that's not enough.  There is some JavaScript code added "on the fly" to the DOM during the loading of the page, assuming such JS code will be executed later (because the <script>...</script> is added at the end of the page itself. Such a code does not rely on a specific event (aka $(document).ready()) but simply by being present in the DOM when the page finishes loading. 

That makes a fix very hard to find. Calling JS at the top of a page to add a <script> element added at the bottom and expecting such added JS code is not very elegant. It very hard to repackage in a method that could be called with the turbolinks:load event is triggered. 

This issue makes the site manager crazy. The WYSYWIG editor and the language picker don't work properly. (The site is based in Montréal QC and uses both French and English.)

**Comment by bricesanchez** [comment]
Could you copy/paste me your Gemfile.lock?

I don't have this bug and i have sites based in Québec QC and uses both French and English too.
