### ISSUE TITLE
Update from 0.9 version to 3.0

### ISSUE THREAD

**Issue by BohdanChaban** [refinery/refinerycms#3292]
Hello guys. I got old application with rails 1.9 and Refinery 0.9. I updated rails to 4.2 version and Refinery to 3.0 by guide on your site. But after update appeared a lot of errors. Do you have guide for that update? Has anyone collided with such case?

**Comment by johanb** [comment]
That's quite a big upgrade. Have you considered upgrading to intermediate releases first ?

**Comment by bricesanchez** [comment]
Did you find a solution?

**Comment by bricesanchez** [comment]
Closed due to inactivity
