### ISSUE TITLE
development.rb: `rails generate refinery:cms`

### ISSUE THREAD

**Issue by pmn4** [refinery/refinerycms#3293]
Hello, I have the following line in my development.rb:
``` ruby
  config.action_mailer.preview_path = "#{Rails.root}/test/mailers/previews"
```
after running `rails generate refinery:cms --fresh-installation`, it becomes:
``` ruby
  config.action_mailer.preview_path = "#{Rails.root}
/test/mailers/previews"
```
and the script stops running on a syntax error.

I removed the line, ran the script, then added it back in, but thought I would let y'all know.

looking forward to using the product!

**Comment by bricesanchez** [comment]
I'm not able to reproduce. Did you find a solution?

**Comment by paa001** [comment]
I have similar problem on install with ruby 2.4.1

![bbb0f8f95d](https://user-images.githubusercontent.com/4222096/29412892-368536ac-8363-11e7-9225-d8bbf3ab4d94.jpg)

But, with ruby 2.3 everything is fine

**Comment by bricesanchez** [comment]
Did you try to use the latest Rails 4.2.9 version ?

**Comment by bricesanchez** [comment]
@paa001  I confirm it's a Rails bug, who was fix in 4.2.8: https://stackoverflow.com/questions/44476001/ruby-2-4-1-warning-constant-fixnum-is-deprecated

**Comment by paa001** [comment]
@bricesanchez Precisely, I used an older version of the rails. Thank you

**Comment by bricesanchez** [comment]
@paa001 i still can't reproduce your error on Refinery 3.0.5 and Rails 4.2.9, do you use master branch? or Rails 5 PR ?
