### ISSUE TITLE
autocomplete="off" sanitized

### ISSUE THREAD

**Issue by Obi-TOB** [refinery/refinerycms#3294]
refinerycms 3-0-stable:

In a page I include an input tag in a form with an html attribute: autocomplete="off"

This get's sanitized.

`-- SANITIZED CONTENT WARNING --
Refinery::Pages::SectionPresenter#wrap_content_in_tag
HTML attributes and/or elements content has been sanitized`

`<input id="keywords" class="form-control" autocomplete="off" name="keywords" type="search" placeholder="Produkt ..." /></div>`
gets
`<input id="keywords" class="form-control" name="keywords" type="search" placeholder="Produkt ..."></div>`

Any nice idea how I can add this to the (Loofah?) whitelist?

Best,
Thomas

**Comment by bricesanchez** [comment]
Modify your ‘pages.rb‘ initializer to add more HTML tags and attributes in the whitelist: https://github.com/refinery/refinerycms/blob/master/pages/lib/generators/refinery/pages/templates/config/initializers/refinery/pages.rb.erb#L69-L77
