### ISSUE TITLE
Support Bootstrap by adding classes to sections

### ISSUE THREAD

**Issue by javinto** [refinery/refinerycms#3305]
In order to support the Bootstrap grid system in the front-end, sections require class names to be added. Example HTML output:

```
<section id="body_content" class="row">
   <section id="body" class="col flex-last col-lg-8 col-sm-12">...</section>
   <section id="side_body" class="col flex-first col-lg-3 col-sm-12">...</section>
</section>
```

It would be wonderful if the Page and SectionPresenter would support this. 

I can image a custom show.html page to look like this:

`= render '/refinery/content_page', sections_html: {body_content: {class: 'row'}, body: {class: 'col col-lg-8'}, side_body: {class: 'col col-lg-4'}}
`

Besides class names this would make it possible to register data-attributes as well.

Any comments on this?

**Comment by javinto** [comment]
Having said this, by using SCSS there is no need for extra classes. The above could be realised like:

```
#body_content {
  @extend .row;
}

#body {
  @extend .col;
  @extend .flex-last;
  @extend .col-lg-8;
  @extend .col-sm-12;
}

#side_body {
  @extend .col;
  @extend .flex-first;
  @extend .col-lg-3;
  @extend .col-sm-12;
}
```

But that leaves out the support of data-attributes. Any needs for that?

**Comment by bricesanchez** [comment]
> In order to support the Bootstrap grid system in the front-end

Refinery CMS is Frontend Framework agnostic. We prefer to let the ability to the developer to use the framework he wants. So we can't support Bootstrap on Frontend.


> Having said this, by using SCSS there is no need for extra classes.

Nice to see you found a full CSS solution :)


> But that leaves out the support of data-attributes. Any needs for that?

I don't think there are needs for that but you could easily do this :

```erb
<% content_for :body do %>
  <div class="my-awesome-css-class" data-my-attribute="test">
    <p>test</p>
  </div>
<% end %>

<%= render '/refinery/content_page' %>
```
