### ISSUE TITLE
When trying to use the Add Image function in the WYSIWYG editor...

### ISSUE THREAD

**Issue by bill-siftlocal** [refinery/refinerycms#3321]
<img width="1189" alt="screen shot 2017-10-22 at 3 34 36 pm" src="https://user-images.githubusercontent.com/27164084/31865597-3e513ec0-b73f-11e7-9d82-53c0b638ef5d.png">

**Comment by bricesanchez** [comment]
Hi @bill-siftlocal, i'm can't reproduce your error. Could you send me a step by step to reproduce? Do you have any error in the browser console or in the logs? Which browser do you use?
