### ISSUE TITLE
click on preview button in rails 5 disables all buttons

### ISSUE THREAD

**Issue by aiomaster** [refinery/refinerycms#3328]
Hi,
I discovered a problem with rails 5 and the preview button.
The problem is, that rails 5 has the `disable_with`-feature enabled by default:
https://github.com/rails/rails/commit/3822a322a82a19a9341a21a0cb1e36653da09c46

This means, that a click on a submit button disables all submit buttons on a form. It is used to prevent double clicks, I think.
Problem is, that the preview button in refinery is a bit special and opens the preview in a new tab.
This is working ok, but if you switch back to the backend tab you can't click any of the form buttons anymore, cause they are disabled by that feature.
One way to workaround this is to disable this rails feature globally like:
`config.action_view.automatically_disable_submit_tag = false`
It is good enough for us, cause we have our own logic to prevent double clicks and that stuff.

Another way for refinery could be to add the `data: { disable_with: nil }` to every form button to prevent that behaviour. Problem is, that it could be usefull to have that feature available for the "save" and "save and continue" buttons.
Another option could be to trick around a little with javascript and try to remove the `disable` attribute from the input buttons, but it is hard (I tried a little), cause you have to do it after rails does the disable magic.

Any other suggestions?

**Comment by enatividad** [comment]
I am also getting this problem.

I used `config.action_view.automatically_disable_submit_tag = false` to solve the problem

**Comment by bricesanchez** [comment]
Hi @aiomaster and @enatividad, i confirm the bug report, thanks for your help!

I've made a PR, could you review and test it ? #3330 

Thanks !
