### ISSUE TITLE
Preview Button in Firefox is not Working

### ISSUE THREAD

**Issue by enatividad** [refinery/refinerycms#3329]
Preview Button Does Not Work on Firefox.

I am using Rails 5.1.4 and Firefox Quantum Web Browser. I have already worked-around the issue in #3328 . However, Preview button is still not working (clicking it does not open a new tab).

**Comment by bricesanchez** [comment]
Hi @enatividad, thanks for the report! I've found a quick fix for the FF problem, i don't really like it but it works : #3330
