### ISSUE TITLE
Not working out of the box for me 

### ISSUE THREAD

**Issue by mices** [refinery/refinerycms#3331]
I followed the instructions but I get an ordinary Rails screen when I point my browser to localhost:3000 There's no index file in my public directory Pointing my browser to localhost:3000/refinery causes a routing error, No route matches [GET] "/refinery" I'm running Ubuntu 16.04 under crouton on an Acer C710 Chromebook I do a lot of rails developing on this environment without any problems

**Comment by bricesanchez** [comment]
Hello,

We need more informations to be able to fix the problem such as :
* Could you tell us the Refinery CMS version you use?
* Could you copy/paste your Gemfile/Gemfile.lock ?
* Do you have a step by step to reproduce?
* Do you have an error stracktrace to share?
* Do you have screenshots?

Thanks!

**Comment by mices** [comment]
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.4)
      actionpack (= 5.1.4)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.4)
      actionview (= 5.1.4)
      activesupport (= 5.1.4)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.4)
      activesupport (= 5.1.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.1.4)
      activesupport (= 5.1.4)
      globalid (>= 0.3.6)
    activemodel (5.1.4)
      activesupport (= 5.1.4)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (5.1.4)
      activemodel (= 5.1.4)
      activesupport (= 5.1.4)
      arel (~> 8.0)
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    acts_as_indexed (0.8.3)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    arel (8.0.0)
    awesome_nested_set (3.1.3)
      activerecord (>= 4.0.0, < 5.2)
    babosa (1.0.2)
    bcrypt (3.1.11)
    bindex (0.5.0)
    builder (3.2.3)
    byebug (9.1.0)
    capybara (2.17.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (>= 2.0, < 4.0)
    childprocess (0.8.0)
      ffi (~> 1.0, >= 1.0.11)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    crass (1.0.3)
    decorators (2.0.3)
      railties (>= 4.0.0, < 5.2)
    devise (4.4.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
    diffy (3.2.0)
    dragonfly (1.1.4)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack (>= 1.3)
    erubi (1.7.0)
    execjs (2.7.0)
    ffi (1.9.18)
    font-awesome-sass (4.7.0)
      sass (>= 3.2)
    friendly_id (5.2.3)
      activerecord (>= 4.0.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    globalize (5.1.0.beta2)
      activemodel (>= 4.2, < 5.2)
      activerecord (>= 4.2, < 5.2)
      request_store (~> 1.0)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.1.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.9.0)
    mini_mime (1.0.0)
    mini_portile2 (2.3.0)
    minitest (5.11.1)
    multi_json (1.13.1)
    mysql2 (0.4.10)
    nio4r (2.2.0)
    nokogiri (1.8.1)
      mini_portile2 (~> 2.3.0)
    orm_adapter (0.5.0)
    public_suffix (3.0.1)
    puma (3.11.0)
    rack (2.0.3)
    rack-test (0.8.2)
      rack (>= 1.0, < 3)
    rails (5.1.4)
      actioncable (= 5.1.4)
      actionmailer (= 5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      activemodel (= 5.1.4)
      activerecord (= 5.1.4)
      activesupport (= 5.1.4)
      bundler (>= 1.3.0)
      railties (= 5.1.4)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-i18n (5.0.4)
      i18n (~> 0.7)
      railties (~> 5.0)
    railties (5.1.4)
      actionpack (= 5.1.4)
      activesupport (= 5.1.4)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    refinerycms (4.0.1)
      refinerycms-core (= 4.0.1)
      refinerycms-images (= 4.0.1)
      refinerycms-pages (= 4.0.1)
      refinerycms-resources (= 4.0.1)
    refinerycms-acts-as-indexed (3.0.0)
      acts_as_indexed (~> 0.8.0)
      decorators (~> 2.0)
      refinerycms-core (>= 3.0.0, < 5.0)
      stringex (~> 2.5.2)
    refinerycms-authentication-devise (2.0.0)
      actionmailer (>= 5.0.0, < 5.2)
      devise (~> 4.0, >= 4.3.0)
      friendly_id (~> 5.2.1)
      refinerycms-core (>= 3.0.0, < 5.0)
    refinerycms-core (4.0.1)
      actionpack (>= 5.1.0, < 5.2)
      activerecord (>= 5.1.0, < 5.2)
      awesome_nested_set (~> 3.0, >= 3.0.0)
      coffee-rails (~> 4.0, >= 4.0.0)
      decorators (~> 2.0, >= 2.0.0)
      font-awesome-sass (>= 4.3.0, < 5.0)
      jquery-rails (~> 4.3, >= 4.3.1)
      jquery-ui-rails (~> 5.0, >= 5.0.0)
      railties (>= 5.1.0, < 5.2)
      refinerycms-i18n (~> 4.0, >= 4.0.0)
      sass-rails (>= 4.0, < 5.1)
      truncate_html (~> 0.9)
      will_paginate (~> 3.1, >= 3.1.0)
      zilch-authorisation (~> 0, >= 0.0.1)
    refinerycms-i18n (4.0.1)
      rails-i18n (~> 5.0.0)
      routing-filter (>= 0.4.0)
    refinerycms-images (4.0.1)
      activemodel-serializers-xml (~> 1.0, >= 1.0.1)
      dragonfly (~> 1.1, >= 1.1.0)
      globalize (>= 5.1.0.beta1, < 5.2)
      refinerycms-core (= 4.0.1)
    refinerycms-pages (4.0.1)
      activemodel-serializers-xml (~> 1.0, >= 1.0.1)
      awesome_nested_set (~> 3.1, >= 3.1.0)
      babosa (!= 0.3.6)
      diffy (~> 3.1, >= 3.1.0)
      friendly_id (>= 5.1.0, < 5.3)
      globalize (>= 5.1.0.beta1, < 5.2)
      refinerycms-core (= 4.0.1)
      seo_meta (~> 3.0, >= 3.0.0)
      speakingurl-rails (~> 8.0, >= 8.0.0)
    refinerycms-resources (4.0.1)
      activemodel-serializers-xml (~> 1.0, >= 1.0.1)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 1.1, >= 1.1.0)
      globalize (>= 5.1.0.beta1, < 5.2)
      refinerycms-core (= 4.0.1)
    refinerycms-wymeditor (2.0.0)
      refinerycms-core (>= 4.0.0.dev, < 5.0)
    request_store (1.4.0)
      rack (>= 1.4)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    routing-filter (0.6.1)
      actionpack (>= 4.2, < 5.2)
      activesupport (>= 4.2, < 5.2)
    ruby_dep (1.5.0)
    rubyzip (1.2.1)
    sass (3.5.5)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.8.0)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
    seo_meta (3.0.0)
      railties (>= 5.0.0)
    speakingurl-rails (8.0.2)
      railties (>= 3.1)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    stringex (2.5.2)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    truncate_html (0.9.3)
    turbolinks (5.1.0)
      turbolinks-source (~> 5.1)
    turbolinks-source (5.1.0)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)
    uglifier (4.1.3)
      execjs (>= 0.3.0, < 3)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (3.5.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    will_paginate (3.1.6)
    xpath (3.0.0)
      nokogiri (~> 1.8)
    zilch-authorisation (0.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  capybara (~> 2.13)
  coffee-rails (~> 4.2)
  jbuilder (~> 2.5)
  listen (>= 3.0.5, < 3.2)
  mysql2 (>= 0.3.18, < 0.5)
  puma (~> 3.7)
  rails (~> 5.1.4)
  refinerycms (~> 4.0)
  refinerycms-acts-as-indexed (~> 3.0, >= 3.0.0)
  refinerycms-authentication-devise (~> 2.0)
  refinerycms-wymeditor (~> 2.0, >= 2.0.0)
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.16.1

I didn't clone it I downloaded the zip today from github
I followed the instructions on github

**Comment by mices** [comment]
4.0.1

**Comment by bricesanchez** [comment]
I've never started a rails project by dowloading a zip source.

Could you try following this guide and see if it works
: https://www.refinerycms.com/guides/getting-started

**Comment by mices** [comment]
That was an error I didn't download anything Yes I followed the instructions but I'm using mysql so i ran `refinerycms app_name -d mysql` After starting the server and navigating to localhost:3000 I get a page that says "Yay! You’re on Rails!" and this can't be fixed by removing index file from public because there is none

**Comment by bricesanchez** [comment]
Ok @mices, thanks for the update. You could use postgresql instead of mysql, it works very well!
