### ISSUE TITLE
Bcrypt stops first installation on win2012r2 server.

### ISSUE THREAD

**Issue by ThorkilG12** [refinery/refinerycms#3345]
Hi. I'm new to this. Have installed Refinery today, and I'm stucked.

Where can I get a mentor that I can skype to and get some hand-on help ?

**Comment by bricesanchez** [comment]
Hi, Did you try solutions on this issue: https://github.com/codahale/bcrypt-ruby/issues/142 ?

**Comment by bricesanchez** [comment]
Is your problem fixed @ThorkilG12 ?
