### ISSUE TITLE
How could I do a processing on page

### ISSUE THREAD

**Issue by thebravoman** [refinery/refinerycms#3346]
I would like to do some custom preprocessing on the page content. 

For example if the page contains the string
{{ some_content }}

than this some_content will be replaced with a desired HTML. 

I could not found a documentation about this and if this was possible. 

What would be the correct way to approach it?

**Comment by bricesanchez** [comment]
Hi @thebravoman ! I'm exactly doing this in our official website: 
https://github.com/refinery/website/search?utf8=%E2%9C%93&q=project_infos&type=

**Comment by thebravoman** [comment]
Nice. Let's try it.
