### ISSUE TITLE
Images/Resources not found

### ISSUE THREAD

**Issue by leopirolo** [refinery/refinerycms#3348]
Hello there,

I'm implementing RefineryCMS onto an already existing Rails app.
All is running fine but I have a problem with the images/resources on my distant Debian server.

- When I upload a file, a new ::Refinery::Image/Resource object is created.
- The file is successfully uploaded into the `/public/system/refinery/(images|resources)` folder.
- The *:url* method is giving me `/system/images/W1siZiIsIjIwMTgvMDIvMjcvM3BhY3dueDlxdF9hcHJSa0JQcl83MDB3XzAuanBnIl1d/aprRkBPr_700w_0.jpg?sha=71594d1d45d762c1` but this leads me to a 404 page.

- It works fine on my OSx computer (tested in development and in production environments).
  - Versions:
    - Rails 5.1.5
    - Ruby 2.4.1
    - RefineryCMS 4.0.1

Am i missing something?
Thanks!
L.

**Comment by leopirolo** [comment]
Seems like the word *system* was generating this issue.

I fixed it changing `config.dragonfly_url_format` in both `/config/initializers/refinery/images.rb` and `/config/initializers/refinery/resources.rb` files.

**Comment by bricesanchez** [comment]
Hi @leopirolo,

Which version of Refinery do you use? Are you able to reproduce this error on a dummy app ?

**Comment by leopirolo** [comment]
Hello @bricesanchez,

My apologies, the problem was with my Nginx config file and not with Refinery...

Bests,
L.

**Comment by bricesanchez** [comment]
@leopirolo thanks for your update!
