### ISSUE TITLE
Seeds issue

### ISSUE THREAD

**Issue by webhive** [refinery/refinerycms#3364]
In your seeds file ``slug`` column used
https://github.com/refinery/refinerycms/blob/master/pages/db/seeds.rb#L54

While it was already removed inmigrations
https://github.com/refinery/refinerycms/blob/master/pages/db/migrate/20170703015418_remove_translated_columns_to_refinery_pages.rb#L4

Finally it caused this

```
...
** Execute db:schema:dump
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment 
** Invoke db:load_config 
** Execute db:abort_if_pending_migrations
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'slug' in 'field list': INSERT INTO `refinery_pages` (`slug`, `link_url`, `menu_match`, `deletable`, `lft`, `rgt`, `created_at`, `updated_at`) VALUES (NULL, '/', '^/$', 0, 1, 2, '2018-04-30 11:16:38', '2018-04-30 11:16:38')
...
```

**Comment by bricesanchez** [comment]
Hi @webhive, thanks for your report.

`slug` is removed from the untranslated table but it is present in the translated table `refinery_page_translations` : https://github.com/refinery/refinerycms/blob/master/pages/db/migrate/20100913234708_create_refinerycms_pages_schema.rb#L54

It should be handle by Globalize and seeds should works.

I see you use `Mysql2`, perhaps there is an error between this adapter and Globalize.

**Comment by bricesanchez** [comment]
We test against `mysql2` too, so it's weird. Could you give me more informations of your Refinery version?

**Comment by webhive** [comment]
```
gem 'rails', '~> 5.1.4'
gem 'devise', '~> 4.3'
gem 'devise-token_authenticatable', '~> 0.5.x', '<= 1.0.0'
gem 'friendly_id', '~> 5.2.0'
gem 'mysql2', '>= 0.3.18', '< 0.5'
...
gem 'refinerycms', '~> 4.0.0'
gem 'refinerycms-authentication-devise', '~> 2.0'
gem 'dragonfly-s3_data_store'
```

**Comment by bricesanchez** [comment]
@webhive did you find a solution?

**Comment by webhive** [comment]
I did some manual seed file updates. But now I dont use refinery anomore. So seems you can close this issue.

**Comment by bricesanchez** [comment]
I'm sorry to read you don't use Refinery anymore, i hope you will try it again soon with the upcoming new admin UI and Mobility feature.
