### ISSUE TITLE
refinerycms-images references refinerycms-dragonfly which doesn't exist

### ISSUE THREAD

**Issue by josh-m-sharpe** [refinery/refinerycms#3370]
https://github.com/refinery/refinerycms/blob/4.0.2/images/refinerycms-images.gemspec#L22

https://rubygems.org/search?query=refinerycms-dragonfly

```
source 'https://rubygems.org'

ruby File.read('.ruby-version').chomp

gem 'rails', '~> 5.1.6'

gem 'pg'
gem 'puma'
gem 'refinerycms', '4.0.2'
gem 'i18n', '0.9.5'
gem 'sass-rails'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'capybara'
  gem 'selenium-webdriver'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end
```

```
$ bundle
...etc...
Fetching refinerycms-images 4.0.2
Downloading refinerycms-images-4.0.2 revealed dependencies not in the API or the lockfile (refinerycms-dragonfly (~> 1.0)).
Either installing with `--full-index` or running `bundle update refinerycms-images` should fix the problem.

In Gemfile:
  refinerycms was resolved to 4.0.2, which depends on
    refinerycms-images
```

**Comment by bricesanchez** [comment]
Hi @josh-m-sharpe !

Thanks for your report! You're right `refinerycms-dragonfly` gem is not released on Rubygems but it should be available in `refinerycms` gem.

I don't know why your bundler try to fetch an external gem.

Should we release `refinerycms-dragonfly` gem on rubygems @parndt ? @anitagraham ?

**Comment by anitagraham** [comment]
Yes, I think we should.

**Comment by parndt** [comment]
Released: https://rubygems.org/gems/refinerycms-dragonfly

@anitagraham I tried to make you an owner of the gem but rubygems.org doesn't recognise your email address.
