### ISSUE TITLE
Move CMS content from one environment to production

### ISSUE THREAD

**Issue by metaflowio** [refinery/refinerycms#3375]
Hi,
I am contemplating using refinery cms in a new project. However I can't seem to find a guide or a presentation on how you envision moving content from one environment (staging, dev, etc.) to a production ready version. Is there some sort of sync possible ? Sorry, this might not be the place place to discuss this, but I could not find anything anywhere else ?

Thx.

**Comment by bricesanchez** [comment]
Hi @metaflowio, 

It's probably more a Rails/Deploy question than a Refinery question. Did you read some guides on Rails or Heroku-like platform?

**Comment by metaflowio** [comment]
Hi @bricesanchez, I am sorry but I beg to differ. And to answer your question, yes I have read guides, I have a large experience running production systems on Rails/Heroku.

As far as I can see, the only way to push/migrate content from a given environment (let's say staging), to a production environment is to basically dump the postgres db and override your production environment database with your staging one (in that case), and this of course is a big no no, way to risky to override an entire production db all at once.

The only other solution I could see, would be to extract only the right data tables / rows form the staging postgres and push only those to production, but it will force us to gain a very strong understanding of how Refinery is architectures and it's entire data schemas, which to be honest kinds of defeats the purpose of using an already built CMS.

I believe that it is relevant for a CMS to address those concerns and they are shared by most of the organization deploying content into production. Let me take an straightforward example that I have seen dozens of time across multiple companies that I have been involved with:
- you have a public front end with content to describe your application
- you have been working at upgrading a significant portion of your application
- and of course you want to prepare some new marketing content to advertise those new features

The issue you face is that you most likely cannot start building those new content page in production as they would need to point to application page that don't exists yet (or embedded demo that are not yet live into production).

However all those app pages you need for your marketing have already been deployed into a staging or pre-production environment for weeks while you QA and UAT are running. This is indeed the best place to start building those new marketing pages on your CMS, as you will be able to test the pages end to end.

And what you want to be able to do from there is to "select" those new pages on your staging CMS and push them towards your production CMS as this would be a much more trustworthy process than having some marketing intern re-copy all those modifications made on staging to production. And of course, implicating your IT team to override your entire production DB is of course out of the question as you cannot guarantee that content has not changed at all on production, and anyways a db override would require downtime, which for many modern services are just unacceptable.

So if you tell me that this is out of scope for Refinery, I can accept that, but then I believe it would make Refinery not suitable for a proper production environment. However if you have specific guides or approach in mind that I have not considered, I would very much appreciate a few pointers. Thank you for your time.

**Comment by bricesanchez** [comment]
> So if you tell me that this is out of scope for Refinery, I can accept that, but then I believe it would make Refinery not suitable for a proper production environment. However if you have specific guides or approach in mind that I have not considered, I would very much appreciate a few pointers. Thank you for your time.

Refinery is suitable for a production environment. 

There are multiples ways to move content from one environment to another. It depends your project. 
Even if it's probably not the bulletproof way, i usually use database dumps, migrations and seeds.

If you have a better idea to improve the workflow, we will be happy to help you!
