### ISSUE TITLE
update dragonfly initializer to be compatible with dragonfly s3 datastore

### ISSUE THREAD

**Issue by kluucreations** [refinery/refinerycms#3376]
s3_datastore initialization is passing invalid opts into s3_data_store.
Update field names so that config values can be picked up succesfully

**Comment by robbyrussell** [comment]
Hey there -- was this released in 4.0.3?

**Comment by robbyrussell** [comment]
We ran into a problem upgrading a Rails 4 Refinery site to Rails 5 and bumping up Refinery in the process with the S3/Dragonfly configurations. We found the fix for this would resolve our config problem but wasn't in latest Rubygem releases. We're tracking 4-0-stable for now

**Comment by parndt** [comment]
@robbyrussell curious.. maybe I didn't release it properly :sob: 

By the way thank you *so* much for Oh My Zsh!

**Comment by parndt** [comment]
@robbyrussell it's released as refinerycms-dragonfly 1.0.1 - please let me know how you get on
