### ISSUE TITLE
Interference between Marketable Pages & ActiveStorage (Rails 5.2)

### ISSUE THREAD

**Issue by Obi-TOB** [refinery/refinerycms#3383]
RefineryCMS (with Rails 5.2. support) in combination with SpreeCommerce 3.6.2:

When mounting Refinery in root
```
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/shop'
  mount Refinery::Core::Engine, at: '/'
end
```

marketable_page routes interfere with ActiveStorage, i.e. the Refinery route matches and  Refinery::PagesController takes over request:
```
Started GET "/rails/active_storage/disk/eyJf [...] g.jpeg" for 127.0.0.1 at 2018-07-20 21:31:58 +0200
Processing by Refinery::PagesController#show as JPEG
  Parameters: {"content_type"=>"image/jpeg", "disposition"=>"inline; filename=\"ror_bag.jpeg\"; filename*=UTF-8''ror_bag.jpeg", "path"=>"rails/active_storage/disk/eyJ [..] g", "locale"=>"en"}
```
I'm not really sure why this happens as the ActiveStorage routes are above the Refinery routes:
```
rake routes | grep 'pages#show\|rails'
[...]
rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
[...]
marketable_page GET    /*path(.:format)                           refinery/pages#show
[...]
```
Removing the mount point for Refinery or moving it to a different path however resolves the issue.

I resolve this now by a hacky route constraint in Refinery, however I would be interested why this happpens and how to resolve it 'right'.
```
def append_marketable_routes
  Refinery::Core::Engine.routes.append do
    get '*path', :to => 'pages#show', constraints: lambda { |req| !req.env["REQUEST_URI"].starts_with? "/rails/active_storage/" }, :as => :marketable_page
  end
end
```

**Comment by bricesanchez** [comment]
Hi @Obi-TOB ! Thanks for you bug report! 

We do not use ActiveStorage so we did not see this bug, did you tried to add the keys `rails` and `active_storage` to your `friendly_id_reserved_words` config in `config/initilizers/refinery/pages.rb`

https://github.com/refinery/refinerycms/blob/master/pages/lib/refinery/pages/configuration.rb#L64

**Comment by Obi-TOB** [comment]
Hi @bricesanchez!

I tried this:
```
  config.friendly_id_reserved_words = ["index", "new", "session", "login", "logout", "users", "refinery", "admin", "images"]
  config.friendly_id_reserved_words << ["rails", "active_storage", "rails/active_storage"]
```
bit it did not help. I would think these `friendly_id_reserved_words`  prohibit that someone saves pages with slugs containing these words. However they don't seem to change the behavior of routes.

I think this is more an ActiveStorage issue than a refineryCMS issue. See https://github.com/rails/rails/issues/31228

Although I do not think that a route constraint is a good solution, however I don't see that anyone has come up with a better solution so far, so if you want me to prepare a pull request I can do so.

**Comment by bricesanchez** [comment]
It's also used in this method `https://github.com/refinery/refinerycms/blob/911cde3a56e7c3060f0ddbe559f6f2ff3b2db2b1/pages/lib/refinery/pages/engine.rb#L56`

@parndt Could you help us to understand how this method works, it's pretty hard to understand and i'm not sure if it still works? :D

**Comment by parndt** [comment]
That method is pretty complex, huh? But it isn't anything to do with this. The method you're after is this one:

https://github.com/refinery/refinerycms/blob/911cde3a56e7c3060f0ddbe559f6f2ff3b2db2b1/pages/lib/refinery/pages/engine.rb#L49-L53

**Comment by parndt** [comment]
I would say that the best way to fix this is to add constraints like @Obi-TOB recommends. Maybe it can be
```ruby
constraints: -> { |req| !req.env['REQUEST_URI'].include?('/active_storage') }
```

**Comment by parndt** [comment]
What might also work is mounting Spree _after_ Refinery as, from memory, in a routes file the routes that are declared last override routes declared before that point. However, that won't fix our underlying issue.

What we could also do is expose a configuration value in pages config like:

```
config.reserved_paths = %w(/active_storage)
```

Then we can use it like this:

```ruby
constraints: -> { |request| Refinery::Pages.config.reserved_paths.any? { |path| !request.env['REQUEST_URI'].start_with?(path) } }
```

**Comment by parndt** [comment]
Also see this https://github.com/rails/rails/issues/31228#issuecomment-352900551

**Comment by bricesanchez** [comment]
Hi @parndt, thanks for your answers!

I like to add `reserved_paths` config. It looks better than https://github.com/rails/rails/issues/31228#issuecomment-352900551

@Obi-TOB Would you like to provide a Pull Request?
