### ISSUE TITLE
Switch to chrome headless instead of phantomjs

### ISSUE THREAD

**Issue by aiomaster** [refinery/refinerycms#3391]
I noticed a lot of random fails in the feature tests (on travis they were just executed up to 3 times until they hopefully work). Maybe you should consider to use selenium with a real browser like chromium. phantomjs is abondoned and has a very old rendering engine, so it would really be cool to update the test suite to chrome headless and maybe get rid of some of the random failing tests.

**Comment by bricesanchez** [comment]
Hi @aiomaster, 

You're right, we should use another solution, could you provide us a PR ? 

:)

**Comment by bricesanchez** [comment]
@aiomaster I've created a PR for this feature

**Comment by aiomaster** [comment]
Impressive, thanks a lot!
