### ISSUE TITLE
heroku install generates invalid Gemfile

### ISSUE THREAD

**Issue by paranoidminotaur** [refinery/refinerycms#3396]
```
[!] There was an error parsing `Gemfile`: Illformed requirement ["ruby-head"]. Bundler cannot continue.

 #  from /Users/allan.michaels/Projects/nohamlikebham/Gemfile:79
 #  -------------------------------------------
 #  # The Ruby version is specified here so that Heroku uses the right version.
 >  ruby "ruby-head"
 #  
 #  -------------------------------------------
         run  bundle exec spring binstub --all
```

I'm encountering this when attempting to follow the instructions under 'Install on Heroku'

Specifically `refinerycms myapp --heroku`

This can be worked around by correcting ruby version in the Gemfile within the created project, but it was confusing as far as the flow of the guide was concerned.

**Comment by bricesanchez** [comment]
Which ruby manager do you use ? 
Which refinery version do you use?

**Comment by paranoidminotaur** [comment]
rvm and 4.0.2

**Comment by paranoidminotaur** [comment]
thanks @bricesanchez
