### ISSUE TITLE
dragonfly/s3/heroku

### ISSUE THREAD

**Issue by paranoidminotaur** [refinery/refinerycms#3397]
Feel free to close, but am I missing something obvious?  I have done _every_ step in the heroku setup, and I'm still not able to get the app to use s3 for image/file uploads.  Heroku config vars are set correctly.  I've tried forcing with `Refinery::Core.config.s3_backend = true` in production.rb.  

All uploads are going into ephemeral storage.

The only way the app will even _attempt_ to write to s3 is if I uncomment the lines that set the datastore config in the images initializer, and change `config.s3_datastore = Refinery::Dragonfly.s3_datastore` to `config.s3_datastore = true`, but then I get errors that the bucket_name hasn't been set on the S3DataStore (from deep in refinery-dragonfly)

Also, the s3 guide mentions adding dragonfly config to the core initializer, but the core initializer now says that dragonfly has its own initializer, though there is no `initializers/refinery/dragonfly.rb` in the generated app.

I'm using Ruby 2.4.3 and rails 5.1.6.

**Comment by bricesanchez** [comment]
Did you see this https://github.com/refinery/refinerycms/pull/3392 ?

**Comment by paranoidminotaur** [comment]
Is this fix on master, or do I need to specify 4-2-stable?

**Comment by bricesanchez** [comment]
This fix is also on `4-2-stable` branch, i think we should release a 4.0.3 soon.

**Comment by paranoidminotaur** [comment]
Thanks @bricesanchez
