### ISSUE TITLE
Consider upgrade to jquery-ui-rails (= 6.0.x)

### ISSUE THREAD

**Issue by jkeam** [refinery/refinerycms#3399]
jquery-ui-rails is tied to version 5.  Would be nice to get support for 6.

**jquery-ui-rails releases**
6.0.1 - December 01, 2016 (171 KB)
6.0.0 - November 29, 2016 (171 KB)
5.0.5 - May 12, 2015 (160 KB)

**Comment by bricesanchez** [comment]
Hi @jkeam,

It's already done on master branch : https://github.com/refinery/refinerycms/blob/master/core/refinerycms-core.gemspec#L35

**Comment by jkeam** [comment]
:) didn't think to try master.  Excellent!

**Comment by Mbuckley0** [comment]
@bricesanchez Is it possible to get a new release out with this fix in it so that new versions of rails are supported?
