### ISSUE TITLE
Refinery doesn't do well with uppercase urls

### ISSUE THREAD

**Issue by xnagpa** [refinery/refinerycms#3407]
When I save refinery page with custom slug like "FUSRODAH", 
Refinery saves refinery_page_translations.slug field like "fusrodah". 

Then when I  try to GET my_site/FUSRODAH I'm getting 'Can't find record with friendly_id "FUSRODAH"' error.

From my point of view there are two ways to improve that: 

1) In refinerycms-pages change lib/refinery/pages/finder.rb
Set slug to downcase  like this.
```
    class FinderBySlug < Finder
      def initialize(slug, conditions)
        @slug = slug.downcase
        @conditions = default_conditions.merge(conditions)
      end
```

2) Stop refinery from saving refinery_page_translations.slug in downcase.

**Comment by bricesanchez** [comment]
Is this link fixing your problem?

**Comment by parndt** [comment]
Is this happening in the latest master branch with the mobility gem, or in 4.0.x?
