### ISSUE TITLE
Auto-generated custom extension specs not running

### ISSUE THREAD

**Issue by m0dm0dm0d** [refinery/refinerycms#3408]
Given a freshly generated extension called `SomeExtension` containing a model called `SomeModel` we've got problems running auto-generated specs like this one

```
    # find me in ./vendor/extensions/some_extension/...
    require 'spec_helper'
     
      module Refinery
        module SomeExtension
          describe SomeModel, type: :model do
            describe "validations", type: :model do
              subject do
                FactoryBot.create(:some_model,
                :title => "Refinery CMS")
              end 
      
              it { should be_valid }
              its(:errors) { should be_empty }
              its(:title) { should == "Refinery CMS" }
            end 
          end 
        end 
      end
```

Calling it via `rspec vendor/extensions/some_extension/spec/models` 

results in 

`uninitialized constant Refinery::SomeExtension::SomeModel`.

Assuming a freshly generated custom extension, what's the correct "refinery way" or workflow of running specs?

refinery 4.0.2
rails 5.2.1

Thanks in advance!

**Comment by bricesanchez** [comment]
Did you try to run `bundle exec rake` ?

**Comment by parndt** [comment]
Please re-open this with more information, including how you ran this and a sample project that has the issue - thanks!
