### ISSUE TITLE
Can not use amazon s3 with refinerycms 4.0.2 and dragonfly data store s3

### ISSUE THREAD

**Issue by ttmthanh** [refinery/refinerycms#3409]

**Comment by ttmthanh** [comment]
I tried using environment variable but still not setup amazon s3. The computer "No such key" when I access the picture and the picture does not show even though the config is correct.

**Comment by bricesanchez** [comment]
Hi @ttmthanh, it's fixed on 4.0.3 but not yet released on Rubygems, @parndt could you release it? Thanks!

**Comment by parndt** [comment]
@bricesanchez sure, it's on my list. Thanks 👍

**Comment by parndt** [comment]
@ttmthanh @bricesanchez I've just pushed version 4.0.3 based on the latest in the 4-0-stable branch.  An enjoyable weekend was the blocker 😄 thanks for waiting.

**Comment by ttmthanh** [comment]
I follow this and code but aws not active :( .
I use `gem 'refinerycms', github: 'refinery/refinerycms', branch: '4-0-stable'` and use enviroment variable for dragonfly.rb and production.rb

**Comment by bricesanchez** [comment]
@ttmthanh  What is your stacktrace error?

**Comment by ttmthanh** [comment]
@bricesanchez Just I can't connect and upload to amazon s3, please show me the steps to connect it

**Comment by ttmthanh** [comment]
@bricesanchez Please help me check: https://github.com/refinery/refinerycms/issues/3410

**Comment by ttmthanh** [comment]
@bricesanchez @parndt Please help me check #3410

**Comment by bricesanchez** [comment]
@ttmthanh I've answer you in #3410
