### ISSUE TITLE
Can we remove dragonfly-s3_data_store dependency?

### ISSUE THREAD

**Issue by veger** [refinery/refinerycms#3411]
When I install refinerycms-dragonfly I automatically pull in AWS S3 support (dragonfly-s3_data_store, and some other dependencies), even if I leave the configuration disabled and never going to use AWS S3 in my project.

Can we remove the (forced) dependency from the gem (and maybe put a a comment next to the [`self.s3_datastore`](https://github.com/refinery/refinerycms/blob/master/dragonfly/lib/refinery/dragonfly/configuration.rb#L61) to include this dependency when you put this setting to true?

**Comment by bricesanchez** [comment]
Hi @veger !

Sure ! Could you provide a pull request ?

Thanks !

**Comment by veger** [comment]
I was a bit busy and away for a while, but I finally made the PR

**Comment by veger** [comment]
PR got merged :tada:
