### ISSUE TITLE
Why I have error when I trying override refinery/admin/images/_form.html.erb

### ISSUE THREAD

**Issue by ttmthanh** [refinery/refinerycms#3422]
I want to add tooltips for image, so I rake override this file and change. Then i got error. I don't understand! Please help me...
![image](https://user-images.githubusercontent.com/22828586/51311181-e7467f00-1a7a-11e9-8ec7-208906a21ef5.png)

**Comment by lanzhiheng** [comment]
![image](https://user-images.githubusercontent.com/8858472/51333430-a1101080-1ab8-11e9-8d6a-2845dc2e7251.png)

I have checked the routes, I think the `image` relevant helper does not contain the `admin_image_crop_path`, Do you have defined it? Or could you provide the routes information to me?

```
bin/rails routes | grep images
```

**Comment by ttmthanh** [comment]
My routes does not contain the admin_image_crop_path. Why??? :(

**Comment by lanzhiheng** [comment]
In addition, I think the template engine which you are using is not ERB.  Did you use other template engine syntax to rewrite the partial?

**Comment by ttmthanh** [comment]
I'm using slim.

**Comment by lanzhiheng** [comment]
Why do you have `admin_image_crop_path` in the code ? I run 

```
bin/rails refinery:override view=refinery/admin/images/_form
```

to rewrite the partial. But I just can get the ERB template, Not the same as yours.  I also haven't the `admin_image_crop_path` in my partial. How did you do that ?  🤔

**Comment by lanzhiheng** [comment]
![image](https://user-images.githubusercontent.com/8858472/51335048-0e717080-1abc-11e9-88c0-5e1158d2035b.png)

My fault. `admin_image_crop_path` was added recently. I am using the version 4.0.3 . So I can't get this template.

**Comment by lanzhiheng** [comment]
It is strange, You should have the `admin_image_crop_path ` helper, because of this file https://github.com/refinery/refinerycms/blob/master/images/config/routes.rb.

I am not sure is it the preload cause this issue. Can you stop your server and run

```
bin/spring stop
```

after that restart your server and check it again ?

**Comment by ttmthanh** [comment]
I will check it. Thanks.
And if i do not try override, i will not get error.
I just change _form.html.erb -> _form.html.slim and rewrite
