### ISSUE TITLE
Failed migration 

### ISSUE THREAD

**Issue by anitagraham** [refinery/refinerycms#3423]
Refinery master branch
Rails 5.2

Creating a new refinery install the following migration failed
20190126111829_add_translated_title_to_refinery_resources.refinery_resources.rb with "undefined method `create_translation_table!' for #<Class:0x0000555a862cf728>".

I moved the file to another folder and all other migrations completed.

_Hello all, btdubs._

Oh...just ran the db:seed and got a related error (perhaps)
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "refinery_page_translations" does not exist
LINE 8:                WHERE a.attrelid = '"refinery_page_translatio...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"refinery_page_translations"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/var/www/fouronsix/db/seeds.rb:10:in `<top (required)>'
```

I guess I need to dig a little deeper
```

**Comment by bricesanchez** [comment]
Hi @anitagraham ! 

There is no more Globalize gem on master branch, old generated migrations for translations will probably fail on a rails db:migrate: 

https://github.com/refinery/refinerycms/search?q=create_translation_table&type=Code

**Comment by anitagraham** [comment]
Thanks Brice.  In the end I restarted the whole project and it was OK. 
I think the root of the problem was that the refinery build failed when there was no pg role 'anita', so that underlying assumption from rails failed.  
Anyway that's all fine now.

**Comment by mischa-s** [comment]
@bricesanchez is there a recommended path forward for apps which are using those autogenerated tables?

**Comment by bricesanchez** [comment]
@mischa-s Is this guide could help you https://github.com/shioyama/mobility/wiki/Table-Backend ?

**Comment by mischa-s** [comment]
thanks I'll have a a go at it
