### ISSUE TITLE
Cannot access newly created ressource in custom extension

### ISSUE THREAD

**Issue by andneuma** [refinery/refinerycms#3431]
Hello everybody,

I've create a custom refinery extension ('some_extension'). I added a ressource called 'bar. Now I added another ressource like the documentation suggested using `rails g refinery:engine foo title:string description:text --extension some_extension --namespace bar`.

I've added the ressource in the extensions routes.rb file like so

```
  # Frontend routes
  namespace :some_extension do
    # Needed for layer preview
    resources :bar, :only => [:show]
  end 

  # Admin routes
  namespace :some_extension, :path => '' do
    namespace :admin, :path => "#{Refinery::Core.backend_route}/some_extension" do
      resources :foo
      resources :bar, :except => :show do
        collection do
          post :update_positions
        end 
      end 
    end 
  end 
end
```

Everything is layed out correctly. Problem is that accessing any of the routes via the admin interface results in `'admin' tried to access 'refinery/some_extension/admin/foo' but was rejected.`. As far as I dived into the core code the AuthenticationManager module blocks the requests. In contrast to 'bar' ressource 'foo' does not appear in the plugin access settings within user settings menu. Am I missing something or is that some sort of bug? I could not find any hint within the docs about the expected behaviour concerning custom extensions' ressources, also none of the config files gave me any direction.

best,
Andi

**Comment by anitagraham** [comment]
I think you created your second resource with the wrong command.
It should be `rails g refinery:engine foo title:string description:text --extension some_extension --namespace some_extension`

**Comment by andneuma** [comment]
Hey @anitagraham Thanks for the hint. It's working now
