### ISSUE TITLE
Issue with uploading to S3

### ISSUE THREAD

**Issue by mepiphany** [refinery/refinerycms#3447]
ruby: 2.6.3
rails: 5.1.7
refinery: 4.0.2

I am trying to upload the images to amazon s3 and I can't get it to work. It only uploads locally. I have followed https://www.refinerycms.com/guides/amazon-s3-for-uploads

Inside core.rb

```
config.s3_backend = true
config.s3_access_key_id =  ENV["S3_KEY"]
config.s3_secret_access_key = ENV["S3_SECRET"]
config.s3_bucket_name = ENV["S3_BUCKET"]
```
Inside production.rb

```
Refinery::Core.config.s3_backend = true
```
And yes, I have set up ENV for the Heroku on those 3 values.
I would love to get some help with this.

thank you

**Comment by bricesanchez** [comment]
Hi @mepiphany !

Do you have any error in the logs ?

**Comment by mepiphany** [comment]
Thank you @bricesanchez thank you for replying, I don't get any error, the file gets saved locally

**Comment by dev-epiphany** [comment]
I was able to fix it by reinitializing the config files, thanks

**Comment by anitagraham** [comment]
Hi Michael,

It looks as though that document needs a rewrite…. I will try and get it done soon-ish.

 

Here is a currently running config

 

# config/initializers/refinery/dragonfly.rb
Refinery::Dragonfly.configure do |config|
  # Configure S3
  config.s3_datastore = true
  config.s3_bucket_name = Rails.application.credentials.aws[:s3_bucket_name]
  config.s3_access_key_id = Rails.application.credentials.aws[:s3_access_key_id]
  config.s3_secret_access_key = Rails.application.credentials.aws[:s3_secret_access_key]
  config.s3_region = Rails.application.credentials.aws[:s3_region]
  config.s3_root_path = nil
  config.s3_storage_path = nil
  config.s3_url_scheme = "https"
  config.s3_url_host = "mybucketname.s3.amazonaws.com"
end

 

Notes:
The config now happens in the refinerycms-dragonfly gem (integrated into refinery, so you don’t need add it to your gems).
I am using the Rails encrypted credentials, but you can quite happily get the variables from your environment as you are doing now.
You only need region if you are not using the default region
Refinery::Core.config.s3_backend = true has been replaced by config.s3_datastore = true
 

If you are still having troubles try checking that the config values are being set as you expect.

 

-- 

Anita Graham

anita@joli.com.au

0411 645 149

**Comment by marcelino056** [comment]
i Upgrade to Refinery 4 and i get the same issue, thanks so much @anitagraham for the contribution

```
Refinery::Core.config.s3_backend = true has been replaced by config.s3_datastore = true
```

Also i'll like to point other problem that i face after the upgrade in case somebody else have same situation. Old images where not found, and i just add `config.dragonfly_url_format = '/system/images/:job/:basename.:ext' `  to the  refinery core initializer.
