### ISSUE TITLE
Unable to install refinerycms engine in rails-6 w/ ruby-2.7.0

### ISSUE THREAD

**Issue by taylorp0994** [refinery/refinerycms#3469]
I ran `rails _6.0.0_ new app-name` with ruby-2.7.0 to create a new rails 6 app. Then, I added `gem 'refinerycms', '~> 4'` to the Gemfile and ran `bundle install`; however, I get an error:

```
Bundler could not find compatible versions for gem "sass-rails":
  In snapshot (Gemfile.lock):
    sass-rails (= 5.1.0)

  In Gemfile:
    sass-rails (~> 5)

    refinerycms (~> 4) was resolved to 4.0.0, which depends on
      refinerycms-core (= 4.0.0) was resolved to 4.0.0, which depends on
        sass-rails (< 5.1, >= 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

I get past that error by changing `sass-rails` from `~> 5` to `< 5.1` in the Gemfile, but then I get another error on `bundle install`:

```
Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 6.0.2.1)

  In Gemfile:
    rails (~> 6.0.0) was resolved to 6.0.2.1, which depends on
      actionpack (= 6.0.2.1)

    refinerycms (~> 4) was resolved to 4.0.0, which depends on
      refinerycms-core (= 4.0.0) was resolved to 4.0.0, which depends on
        actionpack (< 5.2, >= 5.1.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Is there a version of refinerycms that is compatible with Rails 6? I see in the marketing materials that refinerycms is a "Ruby on Rails CMS that supports Rails 6.0+", so I'm confident this is the case. I'm just struggling to get this up and running as a brand new refinerycms developer. Am I missing something here?

**Comment by taylorp0994** [comment]
refinerycms seems to install fine/without issue when I use the "edge"/GitHub source version. Is there a versioned release in the works?

```
gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'
```

**Comment by taylorp0994** [comment]
I see in the changelog that, in fact, there is an unreleased v5. What is the timeline for getting this released?

https://github.com/refinery/refinerycms/blob/master/changelog.md#500-unreleased

**Comment by hdmr14** [comment]
I waiting for these updates released, since last year.
Maintainers not release it over about 2 years...so project looks like dead.

**Comment by bricesanchez** [comment]
This project is not dead, it is mainly in maintenance mode, feel free to contribute and provide pull request for bugfixes and new features.

**Comment by hdmr14** [comment]
Thanks for your reply!
OK, I'll understand and respect this project status.

So, how about release plan to v5?
There's some problems?

**Comment by bricesanchez** [comment]
@hdmr14, I think the real problem to release a new version stands in this unfinished PR: https://github.com/refinery/refinerycms/pull/3465

**Comment by mikehale** [comment]
I ran into this problem too. However I was able to get a working install by cloning the example repo: https://github.com/refinery/refinerycms-example-app

**Comment by taylorp0994** [comment]
closed for inactivity
