### ISSUE TITLE
Update CMS can introduce errors into config files 

### ISSUE THREAD

**Issue by anitagraham** [refinery/refinerycms#3473]
### Present
Refinerycms (4.1.0 db8bb6b)
Rails 6.0.2.2

```
rails generate refinery:cms --update
...
[2020-04-26T11:12:54] WARN  Rails : DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper. 
...
        rake  railties:install:migrations db:create db:migrate db:seed
rake aborted!
SyntaxError: /private/var/www/cs2020/config/environments/development.rb:76: syntax error, unexpected end-of-input, expecting end
```

Looking at `config/environments/development.rb` it now has a syntax error it didn't have before.  

```
config.logger = ActiveSupport::Logger.new("log/#{Rails.env}
  end.log")
```
and a missing `end`.

In `core/lib/generators/refinery/cms/cms_generator.rb` the method `ensure_environments_are_sane!` edits the action_mailer configuration.

### Past
In the past I've noted that this config can look odd as the modification is repeated each time the generator is run, and old configs are nested inside a new ones several levels deep.

For example, I was able to pull this from another app
```
# config/environment/development.rb
 # Don't care if the mailer can't send.
  if config.respond_to?(:action_mailer)
  if config.respond_to?(:action_mailer)
  if config.respond_to?(:action_mailer)
  if config.respond_to?(:action_mailer)
  if config.respond_to?(:action_mailer)
  if config.respond_to?(:action_mailer)
              config.action_mailer.raise_delivery_errors = false
  end
  end
  end
  end
  end
  end
```

### Back to the present:

The action to ensure an environment is sane matches `%r{^\s.+?config\.action_mailer\..+([\w\W]*\})?}` against the contents of the `config/<environment>.rb`, then wraps the match in ` if config.respond_to?(:action_mailer) ... end`.

The match includes an optional final `([\w\W])*\}` that means wrapping the action mailer section and -  if anything following has a closing brace - ,  everything up to and including that brace.

And so, in my case we see that the `end` is inside an interpolated string - confusing - and that the file is missing that `end`.

If the config file doesn't have a `}` anywhere past the action mailer section, the match works perfectly and wraps ya conditional around the setting.

I am happy to fix the issue if I can understand what is intended here. 

1. Why do we do this over and over again?  If an action_mailer config is already present should we just leave it alone?
2.  Can we limit the search to the end of the current config?

In the short term I guess I can move the sections of my config file around.

Thanks for any ideas, explanations etc.

Anita

**Comment by bricesanchez** [comment]
Hi @anitagraham 

>  If an action_mailer config is already present should we just leave it alone?

I think you're right and this is a bug.

**Comment by Znow** [comment]
Also have this, I removed the additional duplicate lines.
