### ISSUE TITLE
SyntaxError: Unexpected token: name (selectedCropRatio)

### ISSUE THREAD

**Issue by aapljack** [refinery/refinerycms#3484]
After a upgrade from Rails 5.1.6.2 to Rails 5.2.4.2 and a upgrade from Ruby 2.3.1 to Ruby 2.5.8, we bumped our RefineryCMS gem to '4-1-stable'. After doing this and merging in a branch with a migration that involved adding an image to a section of the CMS, we are getting the following error when trying to deploy and run this migration.
```
rake aborted!
ExecJS::RuntimeError: SyntaxError: Unexpected token: name (selectedCropRatio)
/data/applegate_web/shared/bundled_gems/ruby/2.5.0/bundler/gems/refinerycms-0c5fd3b04d6d/core/app/assets/config/refinery_core_manifest.js:19
```
I believe it might be this line in the migration that is causing issues..
`add_column :refinery_home_sliders, :mobile_image_id, :integer`

Is this something that needs to be patched in the gem or is there another work around to get this going?

**Comment by anitagraham** [comment]
Are you running a version of js that recognises `let` and other additions to javascript? 

The error looks as though it is coming from `refinery/image_crop.js`, and the first mention of  `selectedCropRatio` is  simply `let selectedCropRatio`

I would look at upgrading execJs (mine is at 2.7.0)
