### ISSUE TITLE
Can not stop refinery from sanitizing the content. 

### ISSUE THREAD

**Issue by thebravoman** [refinery/refinerycms#3486]
Hi, 

I can not find a way to stop refinery from sanitizing the content. I've removed the WYMEDITOR long time ago, but refinery is still sanitizing the content. How can I completely turn it off? 

I can not find a way and I would like to suggest a feature for improvement of the documentation if there is such a feature already or for implementing this feature. 

Thanks

**Comment by anitagraham** [comment]
I have a PR in the wings to suppress the warning messages, but it does not suppress sanitizing the content itself.

I suppose it could be another option

 

Anita Graham

anita@joli.com.au

0411 645 149

**Comment by thebravoman** [comment]
Another option would be great. We have the case where if you type
```
   <div></div>
```
thank this gets sanitized
while if you type (without the leading spaces
```
<div></div>
```
it does not get sanitized. It took hours to figure it out and an option to just say - "please don't do anything with the input" would be great. 

Our use case is that we do not use refinery for end users. We use it only for admin and we don't need the additional sanitize. Actually it is not helping us.

**Comment by anitagraham** [comment]
I recently wrote this to suppress the detailed sanitization  messages. 

```ruby
# app/presenters/section_presenter.rb
class SectionPresenter < Refinery::Pages::SectionPresenter
  private
  def wrap_content_in_tag(content)
    content_tag(:section, content_tag(:div, sanitize_content(content), class: :inner), id: id)
  end

  def sanitize_content(input)
    output = sanitize(input, scrubber: CustomScrubber.new(Refinery::Pages::whitelist_elements,
                                                          Refinery::Pages::whitelist_attributes))
    logger.warn "\n-- Some page content sanitized --\n" if input != output
    output
  end
end
```

I'm sure you could adapt it to your needs

**Comment by anitagraham** [comment]
P.S. I am not sure where some of the HTML that gets sanitized comes from. Some from wymeditor and some from Rails/refinery.  I know it is generated - not deliberately written that way.
