### ISSUE TITLE
Security Issue Report

### ISSUE THREAD

**Issue by mlr0p** [refinery/refinerycms#3494]
Hello, we have discovered a security issue within this project. Do you have a preferred security contact that we could reach out to discuss this issue? Thank you very much!

**Comment by bricesanchez** [comment]
Hi @mlr0p, Thanks for reporting! @parndt will be your best contact :)

**Comment by parndt** [comment]
thanks @mlr0p  Please send an email to `Philip Arndt <git@p.arndt.io>`

**Comment by mlr0p** [comment]
Thank you, we will be in contact soon :)

**Comment by parndt** [comment]
Thanks @mlr0p :smile: I can confirm that we've been in touch over email about this.
