### ISSUE TITLE
Rails Server Error With New Install

### ISSUE THREAD

**Issue by TruePath** [refinery/refinerycms#3497]
After running refinerycms proj_name and changing to the directory (installing 4.0.3) if I try to run bin/rails server I get the following error:

> => Booting Puma
=> Rails 5.1.7 application starting in development
=> Run `rails server -h` for more startup options
Exiting
/opt/local/lib/ruby3.0/gems/3.0.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:109:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)

Hope this helps and maybe there is a workaround currently since that makes it very hard to get started with development.

**Comment by parndt** [comment]
Ah, I don't think we have done any work to support Ruby 3.0 yet. Does this work on Ruby 2.7.x?

**Comment by TruePath** [comment]
Haven't tried that.  Unfortunately, my current setup doesn't make that easy so go ahead and close the thread since that's likely the answer.   Thanks for letting me know!

**Comment by parndt** [comment]
Thanks for the amazingly fast reply @TruePath ! Also I see that it's basically the same as #3488 so at least we can track it there.

One day more things will work with it and I'll get to use Ruby 3.0 😂
