### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by SampsonCrowley** [refinery/refinerycms#3499]
[Current link in readme (http://stable-demo.refinerycms.com/refinery)](http://stable-demo.refinerycms.com/refinery) is a 404 and root path is an apache setup page

**Comment by parndt** [comment]
@djones hey, so our generously provided demo hosting ran out with the provider we were using, so I guess we should 302 redirect to refinerycms.com for now for this link ^ and https://demo.refinerycms.com until we have a solution

Thanks @SampsonCrowley ❤️

**Comment by djones** [comment]
OK I've setup the redirects but they only work on http not https. Linked above is a PR to simply remove the mention of the live demo from the readme so folks don't go to something that is broken.

**Comment by parndt** [comment]
Thank you very much ❤️

**Comment by Matho** [comment]
Hi @SampsonCrowley 

I have deployed Refinery CMS example app ( https://github.com/refinery/refinerycms-example-app ) to my server. You can find it at http://refinerycms.matho.sk/refinery 

The credentials are:
username: demo
password: demo

@parndt I have sent you email with more info to your git email address.

**Comment by parndt** [comment]
@djones we can have the demo working again if we point `demo.refinerycms.com` to `87.244.210.58` - hosting kindly provided by @Matho above (thanks!) 🎉

**Comment by djones** [comment]
OK the DNS is updated. Currently it shows "404 page not found".

**Comment by parndt** [comment]
Awesome thanks @djones -- @Matho you may need to update the hosts on your end to accept the new DNS?

**Comment by Matho** [comment]
HI @parndt  @djones I have set the demo domain to config on the server. Now it is available at 
http://demo.refinerycms.com

The credentials are the same:
username: demo
password: demo

I have deleted the refinerycms.matho.sk record from config, so now this (old) domain will return 404.

The repository deployed to demo.refinerycms.com can be found at https://github.com/Matho/refinerycms-example-app. And tutorial how I have dockerized and prepared auto deploy for the demo app is available at https://github.com/Matho/refinerycms-docker-auto-deploy

The database is restored 2 times per day.

**Comment by parndt** [comment]
Thank you @Matho 👏 🎉 🙇

**Comment by parndt** [comment]
One enhancement might be to prefill the username and password fields with `demo` but other than that, it seems to be working well 😄 thanks

**Comment by Matho** [comment]
@parndt I did redeploy, the form is now prefilled with demo:demo credentials

**Comment by parndt** [comment]
> @parndt I did redeploy, the form is now prefilled with demo:demo credentials

nice one, thank you!!

**Comment by Matho** [comment]
Hi @djones  and @parndt 

I'm migrating my mini raspberry pi cluster running at my home to Hetzner provider from Germany. 

Due to this migration, we need to change the ip for demo.refinerycms.com from old value 87.244.210.58 to new value 159.69.192.189

Could you change the DNS, please? Website on vps from Hetzner will be much faster and will have better uptime. 

Once you do the change, it will show 404 status. It is ok, currently it is down to do not trigger letsencrypt errors. I will activate it, once you do the change.

Thanks!

**Comment by parndt** [comment]
@Matho fine with me but I don't have DNS access - @djones can you please help here? 😄

**Comment by djones** [comment]
@Matho done!

**Comment by Matho** [comment]
@djones @parndt  It is running on new infra now. Thanks.
