### ISSUE TITLE
URI.unescape is obsolete

### ISSUE THREAD

**Issue by RandieM** [refinery/refinerycms#3500]
Hey there,

I am hoping to upgrade my RefineryCMS app to Ruby 2.7.3, but I get this warning message:
`.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/refinerycms-1b73e0b5e1ce/pages/app/presenters/refinery/pages/menu_presenter.rb:92: warning: URI.unescape is obsolete`

Would it be possible to change this obsolete method to something else, e.g. `CGI.unescape` ? I am happy to submit a PR, if this helps.

Thanks.

**Comment by anitagraham** [comment]
Good idea.

**Comment by RandieM** [comment]
Hi @anitagraham,

Thanks for your answer.

What exactly does "good idea" refer to? Changing the obsolete method or submitting the PR? Or may be both?

**Comment by anitagraham** [comment]
Both! 

 

-- 

Anita Graham

***@***.***

0411 645 149

 

 

From: RandieM ***@***.***>
Reply to: refinery/refinerycms ***@***.***>
Date: Tuesday, 29 June 2021 at 11:40 pm
To: refinery/refinerycms ***@***.***>
Cc: Anita Graham ***@***.***>, Mention ***@***.***>
Subject: Re: [refinery/refinerycms] URI.unescape is obsolete (#3500)

 

Hi @anitagraham,

Thanks for your answer.

What exactly does "good idea" refer to? Changing the obsolete method or submitting the PR? Or may be both?

**Comment by parndt** [comment]
We'd love a PR for this please @RandieM 😄

**Comment by RandieM** [comment]
Here is the relevant PR: https://github.com/refinery/refinerycms/pull/3503

**Comment by parndt** [comment]
Resolved by #3503 thank you!
