### ISSUE TITLE
undefined method 'browser_title'

### ISSUE THREAD

**Issue by jimjimovich** [refinery/refinerycms#887]
In a freshly pulled clone of master:

bundle install
rake db:migrate
rails s

I set up a new account, then try to go to localhost:3000/  or to the edit page form and get the following error:

undefined method `browser_title' for #Refinery::Page::Translation:0xbeedad0

Extracted source (around line #4):

1: <head>
2:   <meta charset='<%= ::Refinery::Application.config.encoding %>' />
3:   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
4:   <title><%= browser_title(yield(:title)) %></title>
5:   <%= raw "<meta name=\"description\" content=\"#{@meta.meta_description}\" />" if @meta.meta_description.present? -%>
6:   <%= raw "<meta name=\"keywords\" content=\"#{@meta.meta_keywords}\">" if @meta.meta_keywords.present? -%>
7:   <%= csrf_meta_tag if ::Refinery::Setting.find_or_set(:authenticity_token_on_frontend, true)-%>

**Comment by djones** [comment]
Helped me. Thanks @dwaynemac
